### ISSUE TITLE
`ts` as an alias for `typescript` in fenced code blocks

### ISSUE THREAD

**Issue by borekb** [typora/typora-issues#1004]
This would be a nice shortcut to the longer `typescript` keyword:

~~~md
```ts
let a = 1;
```
~~~

**Comment by vassudanagunta** [comment]
Not a good idea to introduce a "shortcut" that won't be recognized by other Markdown tools. The point of a standard is portability.

**Comment by abnerlee** [comment]
We will recognize "ts" ad alias of "typescript" since Github can also recognize this

**Comment by vassudanagunta** [comment]
I don't think GitHub cares so much about portability... They only render Markdown people put in repos and in GitHub comments.  Typora edited files will be opened in other tools (Pandoc, Jekyll, Hugo, etc). If these tools don't support "ts", then Typora would be subverting portability. Can we confirm that first?

People are moving *toward* standard and portable Markdown... even GitHub is adopting CommonMark because Markdown has gotten too messy with too many flavors.

I also think clarity is more important than saving a few keystrokes.

**Comment by AlexPasternak** [comment]
If ts just expands into typescript by Typora, then everybody wins. You get convenience and portability.

**Comment by borekb** [comment]
I don't think syntax highlighting in fenced code blocks is "standard" by any means, for example, Pandoc doesn't understands either `typescript` or `ts`.

I write documents for GitHub, GitHub supports it and I'd prefer the shorter version. I'm not sure why Typora would be forcing me to something longer just for the sake of some hypothetical interoperability with tools I don't use 😄. But I'm new to it, maybe the philosophy is different, I don't know, thanks for considering it.

**Comment by borekb** [comment]
It seems that `ts` is safe:

- GitHub: [supports `ts`](https://github.com/github/linguist/blob/21babbceb1532793695ee903d7e5e4ec7c98ba39/lib/linguist/languages.yml#L4630)
- Jekyll: [supports `ts`](https://github.com/jneen/rouge/blob/95ea3c9db44a23ade3637333296e1ab36a556839/lib/rouge/lexers/typescript.rb#L15)
- Hugo: [supports `ts` via Pygments](http://pygments.org/docs/lexers/)

**Comment by abnerlee** [comment]
supported in new release
