### ISSUE TITLE
Capitalise H in GitHub

### ISSUE THREAD

**Issue by boardfish** [typora/typora-issues#1024]
Picked this up today, it's absolutely awesome to see such a minimal Markdown editor. I may even start to use it on Linux, but at least on the macOS version, the default theme is named Github rather than GitHub. I can imagine there may be a few more issues such as these in the user documentation and such.

**Comment by celestialphineas** [comment]
I found it's an interesting design flaw (or perhaps a feature?) of Typora. It seems that you cannot designate a theme's name in upper case or lower case at all. It's a technical problem, rather than a spelling mistake of Abner. All Typora themes in its "themes" folder must have filenames in lower case, and Typora simply capitalizes its initial letter and shows it in its UI in a kinda straightforward manner.
Well, he did not make it on purpose or out of ignorance after all. But a theme naming solution is surely in need.

**Comment by abnerlee** [comment]
I will close this since we did not design any logic to support this. 
Currently our logic is `github.css` -> Github, `git-hub.css` -> GitHub.
If we change our logic it will bring backward compatibility issue.

We can explain like this, the theme is named "Github", looks like, but not a same thing with `GitHub`
