### ISSUE TITLE
Improper handling of simply line returns.

### ISSUE THREAD

**Issue by robmuh** [typora/typora-issues#1113]
`vim`  with `set list` on:

![screen shot 2017-12-18 at 12 35 56 pm](https://user-images.githubusercontent.com/3749067/34119534-7ef00014-e3f0-11e7-96d6-46695b1e5b5b.png)

Typora in `GitHub` style:

![screen shot 2017-12-18 at 12 36 20 pm](https://user-images.githubusercontent.com/3749067/34119558-8a7f85b2-e3f0-11e7-887d-864e43bdc2d5.png)

Same content on GitHub:

![screen shot 2017-12-18 at 12 37 05 pm](https://user-images.githubusercontent.com/3749067/34119567-911ea466-e3f0-11e7-8161-a9144bb17e99.png)

**Comment by abnerlee** [comment]
This is current spec. If we render them in one line, users won't know there's "\n" between them

**Comment by robmuh** [comment]
Which spec are you referring to? Are you saying that GitHub is not following the Markdown spec? Or are you choosing to follow your own spec (in which case I would really like to know because that decision would prevent me from ever buying your product).

**Comment by abnerlee** [comment]
> Are you saying that GitHub is not following the Markdown spec? 

No.

We also consider them as one line when export/print, but when editing, the "\n" are displayed just like when you write in this textarea. You could use custom CSS to make them hide the line break.

**Comment by abnerlee** [comment]
Also, in github, single line break seems to be kept, e.g.: 

this
is
one
paragraph

**Comment by robmuh** [comment]
So it is a style thing then. I do not export to GitHub so, yes, the line
breaks are kept (and visible from raw mode) but are not visible when
rendered by going to that markdown file with the GitHub browser.​



*“Mr. Rob” Muhlestein*
*/^(Founder|Facilitator|Janitor|C\w\w?O)$/*
Content and community provide opportunity
SkilStak Coding Arts <https://skilstak.io>
rob@skilstak.com
704-310-6778
robs.io

**Comment by vassudanagunta** [comment]
@abnerlee I get why you do it this way. But it is confusing. Sometimes Typora acts like a WYSIWYG editor, but sometimes it acts like *source code mode* even when not in source code.

Is there a better way of doing this? Options:

1. Keep it as is, which violates the WYSIWYG expectations of some or most users.
2. Only render the single line-breaks in source code mode
3. Only render the single line-breaks when the paragraph has focus (similar to how you do so for other things like bold/italics and links) and in source code mode.

Maybe this issue should be merged with #1026 as the underlying problem is the same. Option 3 might be the best for both of them.

**Comment by robmuh** [comment]
Thank you @vassudanagunta for articulating what I could not. Either way is fine. I just needed to know what to expect. Often the WYSIWYG is so good I will even screen shot it.

**Comment by vassudanagunta** [comment]
It turns out this is a dupe of #364. I'm going to restate my point above there.
