### ISSUE TITLE
Setup detected as ransomware by Trend Micro

### ISSUE THREAD

**Issue by dphi76** [typora/typora-issues#1191]
The setup file for Typora is detected as a ransomware program by Trend Micro Security Agent.

Windows 10 Pro 64-bit
Typora 0.9.9.12 (assuming that is the latest as shown in the change log today)

![image](https://user-images.githubusercontent.com/33334011/35465485-3cc9e8fa-02b1-11e8-8f4a-bb20d56965eb.png)

**Comment by abnerlee** [comment]
You can check in https://www.virustotal.com/en/file/8a19a04b865319a50c264f377b56b69bb670a4b897f645cc0984402de9b4d65f/analysis/

Please report to Trend Micro if you have doubt on this result

**Comment by dphi76** [comment]
Sorry, I should have been more clear: I don't have any suspicion that Typora is, in fact, ransomeware. But if the setup file is triggering that warning, my IT person won't let me install Typora on our machines.

**Comment by abnerlee** [comment]
I see, in that case, I also recommend you to report to Trend Micro for this "false positive" case, you should be able to report to them from Trend Micro software, so that they will correct this in new update.

Also you could try install Typora on another PC or VM, and copy the Typora folder under "Program Files"  to your target PC. And bind connection between markdown files and Typora manually.
