### ISSUE TITLE
Chinese characters cannot be saved correctly

### ISSUE THREAD

**Issue by zhihengwang** [typora/typora-issues#123]
当文件以纯英文字符的内容保存过一次后，这个文件中输入的任何中文字符都会被保存为“?”，即无法保存中文部分。用其他文本编辑器正确保存一次中文后，又可正常可保存中文。
而文件从第一次编辑时就一直含有中文内容的情况下，不会出现乱码。

Once a file has been saved when it contains English characters only,  any of Chinese characters typed latter could not be saved correctly, Typora will save all of those Chinese characters as question marks.

**Comment by phoenix0401** [comment]
用英语再发一遍吧

**Comment by leewi9** [comment]
Yes, it'll be great if we can discuss in English so other people can
understand and participate.  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 18 2016, at 2:59 pm, phoenix0401 &lt;notifications@github.com&gt;
wrote:  

> 用英语再发一遍吧

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/typora
/typora-issues/issues/123#issuecomment-211233666)![](https://github.com/notifi
cations/beacon/AKVKoOrxBjCB3rdLHGb-3bts5mObkF3Tks5p4yvFgaJpZM4IJXRL.gif)

**Comment by abnerlee** [comment]
Should be fixed in new release
