### ISSUE TITLE
Make dark theme (night) printable

### ISSUE THREAD

**Issue by a-dzik** [typora/typora-issues#1248]
Hi, 

I'm using the dark theme - Night. 
However It's bad for printing. Somehow the background is white, yet the font isn't changed - it's still light grey. 

I tried to fiddle with `@media print { }` but without luck. Any ideas how to make the default printing font just black?

**Comment by abnerlee** [comment]
@a-dzik what is the Typora/OS version?

**Comment by a-dzik** [comment]
Typora 0.9.9.12.5 on OSX 10.11.5

**Comment by abnerlee** [comment]
Please try the latest version

**Comment by D-ominik** [comment]
I'm using the latest version 1.7 and still the text prints dark gray instead of black. Also no luck with adding `@media print { }` styles to the theme (even with adding !important). I think there are some styles added while printing, right?

Where can I customize these styles to print black? It doesn't make any sense at all to print text gray.

**Comment by XeroHero** [comment]
I am using the theme GitHub and it is exporting and printing fine. I previously had issues with the "Night" theme, I'm still unsure as to why this is happening, but at least now I'm able to print out the MarkDown texts I create and edit clearly for all to read...

Hope this will help anyone stumbling upon this problem as well. 
Thanks!

Version: 1.12.4 for Linux (x64 Snap)
