### ISSUE TITLE
Open static md link in same window or tab.

### ISSUE THREAD

**Issue by vndsrswt** [typora/typora-issues#1251]
For multiple md file it would be a great thing to have any kind of link opening in same windows compare to another new window.

**Comment by vassudanagunta** [comment]
@vndsrswt See #1000. In that proposal, clicks on references and in the sidebar do not open a new tab or window, because most people expect such clicks to be navigation. New tab/window is achieved by meta-key override. If you like that, vote it up! If not, comment over there please. 

Please close this as it is a duplicate issue.

**Comment by abnerlee** [comment]
merge in https://github.com/typora/typora-issues/issues/1000
