### ISSUE TITLE
Problems using the dollar sign

### ISSUE THREAD

**Issue by Fastidious** [typora/typora-issues#1298]
Create a new document. Type:

$400 is certainly more than $300.

See what happens?

**Comment by abnerlee** [comment]
Please disable `inline math` in preference panel

**Comment by joallard** [comment]
@abnerlee I would suggest re-opening this issue for UX reasons. Also, this workaround prevents having sentences with dollars and using inline math.

(I'm not sure whether this comes from the CMD spec, but) I would expect inline math to only trigger if (1) the opening sign has a space before, and (2) the closing sign has a space after.

I'm thinking there's prior art to this reflection, but I think math delimiters should be `$$` instead of just `$`.

**Comment by abnerlee** [comment]
@joallard Your request is about #63

`$$` is treated as "block math" in many other Markdown engine or by default setting of MathJax

**Comment by joallard** [comment]
@abnerlee Thanks for the reply. I'd opine that this is about a slightly different issue, namely that the single, unrestricted `$` as a default is a UX issue. But as a workaround, I'll turn mine off I guess.

**Comment by cbrum11** [comment]
@joallard I'm going to agree with you here.  My work around for inline math and dollar signs in a document is to wrap the money text with inline code ticks.  Not the most elegant, but it does the job.
