### ISSUE TITLE
restore prior sessions state on OS X

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#153]
On OS X it is standard now that along with auto-save, an app will save and restore its state when closed and re-opened, as if it were never closed. This includes at least the reopening of documents that were open when Typora was exited.

**Comment by AlexPasternak** [comment]
The current workflow for reopening the app on Mac is really broken. Steps:

1. Start document, resize window to size you want (I park it on the right side of the screen, for example), save it. Quit the app.
1. Restart the app. It opens with a new, blank file in the same size and position as your previous document. Huh, that's not what I want, I want to keep working with my *old doc*.
1. Use Open Quickly... to load up the doc I was working on before. There it is in the list, this is going to be great!
1. The doc opens up with the top part of the window offscreen, making it much harder to resize or move. The new useless file is still where it is.

Every time, I then have to:

1. Close the pointless file
1. Use a window manager or keyboard shortcut to change the window size
1. Finally resume actual work, where I wanted to before, instead of jumping into it as soon as app is open.

<img width="1396" alt="screen shot 2016-06-16 at 1 05 31 pm" src="https://cloud.githubusercontent.com/assets/1819485/16125771/1b54364e-33c3-11e6-850c-ed7a8ca88d88.png">

**Comment by abnerlee** [comment]
@AlexPasternak 

Well, so shortly speaking, you also want typora restore previous session after restart, is this correct ?

**Comment by abnerlee** [comment]
@AlexPasternak 

And "The doc opens up with the top part of the window offscreen" is a bug, could you also describe how to reproduce it?

**Comment by AlexPasternak** [comment]
The steps to repro that bug are exactly the ones I typed above. Although I tried it on another machine just now and the window was not offscreen after Quick Open, so it may be related to a multi-monitor setup. Perhaps when a monitor was connected, above the primary one, and then is no longer available. I'm not at the office now, so can't try to repro, but will update if I get more details.

And yes, consider this also a +1 for restoring session, which is why I posted it here.

OS X 10.11.5, btw.

**Comment by AlexPasternak** [comment]
I can still repro this with the newest version, here's my display layout if that helps. The app opens on the primary screen. I cannot see the top of the 2nd new window, just as in screenshot above.

<img width="228" alt="monitors" src="https://cloud.githubusercontent.com/assets/1819485/16238503/ae8520b0-37ae-11e6-8f23-db6cfad68d9a.png">

**Comment by vassudanagunta** [comment]
@abnerlee, IMHO, first priority is for Typora to re-open files that were open on previous close. For example, I keep unfinished notes/docs open. When I am forced to restart Typora (e.g. Typora update, crash, computer reboot) I don't remember which ones I've not finished yet.

Second priority would be for it to re-open them with the same window size and position, *as if Typora were never closed*. 

Currently the one thing Typora does on restart is preserve the state of any *unsaved* files. If it can do that, I'm hoping it's not much work to do the same for all open files.

**Comment by abnerlee** [comment]
OS X has this feature provided by the operating system. It is a bug that typora does not support this, we will fix this in next version up.

**Comment by abnerlee** [comment]
Fixed in new version

**Comment by AlexPasternak** [comment]
I see no improvement in behavior described in this thread in 0.9.9.6. @vassudanagunta stated the priorities exactly right before, but neither of these things happen. I.e., last opened file is not opened at restart, and then when you do open that file (e.g., using Shift-Cmd-O), that file is opened in a different screen position. The only state restored is that a new blank document is opened where your previously opened document was.

This behavior is better in other apps. E.g., TextMate restores open file and position. Microsoft Word doesn't reopen the file, but when you pick it from recent files picker shown at startup, it's opened in the same exact position as before. Etc.

Is something like a reboot necessary to see a change in Typora behavior?

**Comment by abnerlee** [comment]
@AlexPasternak first open system preference -> general, then you should uncheck "close windows before quit", after that typora will restore previous session

**Comment by vassudanagunta** [comment]
@AlexPasternak, works perfectly for me. I quit Typora and reopened it. The two documents on screen before were returned to their prior sizes and positions, and a third that was minimized reappeared in the Dock! Works perfectly.

The only thing that isn't perfect seems to be a macOS issue: restored windows aren't restored to their previous Desktop if you have more than one. Apple apps fail to do that too, so not a Typora bug.

**Comment by AlexPasternak** [comment]
Thanks @abnerlee, you're 100% correct and Typora now works perfectly in this regard. Rock on!
