### ISSUE TITLE
Mac shortcut for "Format->Code", ⌘⇧' , does not work

### ISSUE THREAD

**Issue by gandalfsaxe** [typora/typora-issues#1548]
Pressing ⌘⇧' does nothing. But I can still select it from the menu.

PS: What's with shortcuts randomly not working? Not the first time :) #1424

**Comment by abnerlee** [comment]
It is working in my test. Could you tell me how to reproduce this?

**Comment by gandalfsaxe** [comment]
My Macbook is currently in for repairs, so I can't try right now.

I'll write an update here if I can reproduce it when I get it back.

**Comment by gandalfsaxe** [comment]
Sorry, my bad. I see in my OP that I thought it was ⌘⇧', not ⌘⇧`. That is, I thought the backpack was apostrophe. So no problem.

**Comment by luisspuerto** [comment]
It's not working here... even using the [grave accent](https://en.wikipedia.org/wiki/Grave_accent) `` ` `` . 

![](http://g.recordit.co/fdXdMCtqwB.gif) 

The problem using such a symbol is that at least in my keyboard it expect an additional character to work. Either a vocal to be the accent of a space to be a single symbol. The true is that they aren't symbols on their own but complements. Perhaps in some keyboards they are, but not for example in one with Spanish layout. 

![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/spanish_notebook.png)

The same happens with the strike shortcut `^~`. In my keyboard to put `^` I need to press ``shift + ` `` keys and to get the [tilde](https://en.wikipedia.org/wiki/Tilde) alone I have to press `alt + Ñ`. Pretty awkward combination. 

I recommend that you change those shortcuts to more conventional characters or at least you gives the option to customize. 

For example inline code could be `shift + cmd + k` and strike `cmd + ctrl + s`. But please don't use special characters because oftentimes they are in awkward places in different layouts. 

PS/ I live in Finland, my wife has a computer with a Finnish/Swedish layout and sometimes things could go really really awkward. 


![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/swedish_notebook.png)
