### ISSUE TITLE
characters get bigger when use multiple monitors

### ISSUE THREAD

**Issue by Zhangyanbo** [typora/typora-issues#156]

**Comment by leewi9** [comment]
that's because your monitor is bigger  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On May 11 2016, at 5:23 pm, Zhang Yanbo &lt;notifications@github.com&gt;
wrote:  

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/typora
/typora-issues/issues/156)![](https://github.com/notifications/beacon/AKVKoFG4
g7e8Pbrq1QtyWvbcSo6dN6ovks5qAaABgaJpZM4Ib41b.gif)

**Comment by abnerlee** [comment]
seems duplicate with https://github.com/typora/typora-issues/issues/133
