### ISSUE TITLE
Suggestions on Lists

### ISSUE THREAD

**Issue by adiamoc** [typora/typora-issues#157]
Is it possible to have a option like continue with last list?
The numbering/listing restarts from 1./• if I add a math block between them.

Thanks!

**Comment by vassudanagunta** [comment]
Markdown doesn't support numbered lists continuing after an intervening paragraph. But what Markdown does support are list items with multiple paragraphs. You can make the second paragraph of a list item a math block. Since this paragraph is part of the list item, it doesn't break the list and numbering will continue.

If you think about it, this is really what you want, because the match block belongs to the list item above it, right? Otherwise it doesn't make sense for it to be in the middle of a list.

To add extra paragraphs to a list item, instead of typing `ENTER` type `CMD`-`ENTER` or `CTRL`-`ENTER`. Then insert your match block.

**Comment by vassudanagunta** [comment]
There is a flaw in Typora: Normally when you enter multiple paragraphs for a list, and you want to start the next numbered item, you simply press `ENTER` twice. But this does not work when the paragraph is a math block. There are two workarounds: Type the next list item before inserting the math block, then go back to insert the match block.  The other workaround is to use source code more.

**Comment by abnerlee** [comment]
Typora now supports ordered lists starting with given number, e.g:

3. list start from 3
4. something

So this is already supported by now
