### ISSUE TITLE
URL containing punctuation ()@+_. not parsed correctly

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#1590]
Given a URL with @ character, Typora does not understand that the whole thing is a link. I think the app should borrow some proven library's URL parsing, rather than rolling its own, so that these types of issues do not occur.

Sample URL: https://medium.com/@aacaeirojr/scaling-scrum-when-multiple-teams-are-working-on-one-single-product-5b0412adfdcd

<img width="651" alt="screen shot 2018-06-28 at 1 53 11 pm" src="https://user-images.githubusercontent.com/1819485/42051755-e5cd6020-7ada-11e8-9822-8291fd0583ba.png">

**Comment by abnerlee** [comment]
> Example is Wikipedia URL for Java Language which fails due to containing ( and )
>
> [Wikipedia Java (Language)](https://en.wikipedia.org/wiki/Java_(programming_language))

**Comment by vassudanagunta** [comment]
This breaks Typora's own Change Log as linked in the menu: `Typora:Help:Change Log`

**Comment by andronocean** [comment]
I just encountered this myself pasting in a Medium link. It only happens when Typora does URL autolinking, and you can make it behave by wrapping the URL in `<` and `>` brackets:
<img width="609" alt="url_parsing_typora" src="https://user-images.githubusercontent.com/26490481/50025790-b9ba7180-ffb4-11e8-8711-127e0e1c9ca0.png">

(This is per the CommonMark spec, and Help > Markdown Reference encourages this.)

If you were to fix the autolink parsing, perhaps the best path would be to mimic Github's autolink extension: https://github.github.com/gfm/#autolinks-extension- 

It has a nice set of rules that handles cases like the Wikipedia parenthesis issue, yet avoids greedily matching trailing punctuation (so I can write "Do I want to visit www.github.com?" without including the `?` in the URL).

**Comment by AlexPasternak** [comment]
@abnerlee, here's another example of a valid URL that doesn't get shown correctly by Typora. Didn't want to open up another issue, though, as it seems very similar. GitHub obviously renders it correctly.

https://wiki.sei.cmu.edu/confluence/display/java/NUM00-J.+Detect+or+prevent+integer+overflow

<img width="727" alt="2019-01-25 11 20 47 am" src="https://user-images.githubusercontent.com/1819485/51758230-49af0900-2093-11e9-9f4d-209b2f631fe8.png">

**Comment by Synchronyx** [comment]
Seems a similar issue with the apostrophe.
`[Open this file](C:/x'folder/can't open this file.md)`

It returns
> Cannot open location C:\x'folder\can , do you mean http://C:/x%27folder/can ?

I think he doesn't like more than 1 apostroph in a link.

ps: I'm new to github sorry if this was not the place to post.

**Comment by abnerlee** [comment]
should be fixed in latest version
