### ISSUE TITLE
Open source Typora

### ISSUE THREAD

**Issue by anujbhatt** [typora/typora-issues#16]
Thanks for this editor -- I've been using it for a while and it's been great. 

Open sourcing this will only make things better! :)

**Comment by waahto** [comment]
I strongly agree with this. Even if Typora is going to cost something in the future.

**Comment by leewi9** [comment]
Typora is absolutely an amazing markdown tool, but it has so many bugs and things needs to improve, it would be better if it could be open sourced, if it's for money reason don't worry I'm sure people will make donate.

**Comment by b-long** [comment]
The donation idea is excellent, IMHO.  Maybe open source and start the donation campaign simultaneously?  Plus, you never know what you might learn from a pull request.  Any maintainer (or reader of pull request code) may gain skills, which can certainly bring financial reward.  I looked for an editor for hours yesterday, and tried a variety.  Typora was the first that offered the features that I need : 

1. Ability to run locally
2. A file finder
3. Canonical shortcuts (e.g. `CMD + O` for open, `CMD + B` for bold text.)
4. Preview output immediately

Added bonus, it looks very pretty 👍 Nice job!

**Comment by Menci** [comment]
+1

**Comment by smallx** [comment]
+1

**Comment by fiskr** [comment]
+1

**Comment by pgolebiowski** [comment]
+1

**Comment by felipehw** [comment]
+1
I will happily support with money a free (libre) software Typora :D

**Comment by leewi9** [comment]
and Open Source will surely speed up bug fix in Typora, and bring an 
even more great improvement in the user experience.

**Comment by leewi9** [comment]
and open source will surely speed up bug fix in Typora, and bring great improvement on the user experience.

2016年9月28日 +0800 21:20 felipehw <notifications@github.com>，写道：

**Comment by Noettore** [comment]
+1

**Comment by nateswart** [comment]
I would love to support Typora, both financially and with contributions. Please consider open sourcing it.

**Comment by brylie** [comment]
@abnerlee would it be OK if people donated towards this issue on Bountysource? If so, how much would be a reasonable goal to reach, so we could open source Typora?

[![Bountysource image](https://api.bountysource.com/badge/issue?issue_id=28946424)](https://www.bountysource.com/issues/28946424-open-source-typora)

**Comment by leewi9** [comment]
Since the 100+ issues can not be dealed in foreseeable time, I believe It's prime time to open source Typora, so that we can let more capable and suitable guys to solve them asap.

2016年10月27日 +0800 17:43 Brylie Christopher Oxley <notifications@github.com>，写道：

**Comment by AlexPasternak** [comment]
I don't know if a good convincing argument is to argue that the app's creator is not as capable or suitable.

**Comment by brylie** [comment]
@AlexPasternak right. It could also be a 'lost in translation' thing, since @leewi9 may not be a native English speaker.

**Comment by vassudanagunta** [comment]
The two meanings of "more", `[1]` comparative adverb as in "more capable" and `[2]` greater numerical amount ("more guys") are distinct words in Mandarin.  You can use it in sense `2` to modify "guys" yet have it adjacent to "capable" and it would still modify "guys".

**Comment by rognoni** [comment]
> “Decide you must, how to serve them best. If you leave now, help them you could; but you would destroy all for which they have fought, and suffered.”

**Comment by vassudanagunta** [comment]
@rognoni, Yoda turned out to be wrong many times. He was wrong in what you quoted, and he was wrong before that, when he said, “He is too old. Yes, too old to begin the training.”

**Comment by Lokesh-Krishna** [comment]
I too would gladly contribute to see this beauty go open source.
The BountySource idea sounds good.

**Comment by rdnz** [comment]
+1

**Comment by rguimaraens** [comment]
+1

**Comment by fulus06** [comment]
+1

**Comment by nonbeing** [comment]
+1

**Comment by yhaskell** [comment]
+1

**Comment by disanvparean** [comment]
+1

**Comment by balupton** [comment]
I love typora, but will always be on a lookout for an open-source equivalent for it.

**Comment by leewi9** [comment]
Also a million people ask President Obama to pardon Edward Snowden. Hmm... interesting, let's wait and see..

2017年1月16日 +0800 02:06 Benjamin Lupton <notifications@github.com>，写道：

**Comment by balupton** [comment]
Seems the typora editor is built ontop of codemirror - https://github.com/typora/typora-issues/issues/315

**Comment by kazup01** [comment]
+1

**Comment by apexJCL** [comment]
Just adding my 2 cents.

Not sure if this has been suggested previously, but you could take the pgModeler route. Offer a pre-compiled version for a modest amount of money (you know, to support your development and build chain). 

If someone wants it for *free*, they must clone and compile the source (thus themselves setting up the environment and whatsoever).

Alas, donation it's always something you can count on with, I love writing in Markdown, and Typora it's amazing, so giving you a few bucks wouldn't hurt.

**Comment by fiskr** [comment]
@apexJCL, if they want to eventually make Typora a product you have to buy, at least this way there would be an option for the more technically minded to make contributions and have their own Typora clone to tinker on... 

However, I think just like Nylas - they are going to get us dependent on a good tool and then rip away the free version and make us pay. I have already left Typora, for several reasons (such as not committing to Open Source, and there was some issue where the mapping between the richtext and markdown didn't work, and created an accessibility issue).

**Comment by dessalines** [comment]
I'd support this project on bountysource, if it went open-source.

**Comment by dessalines** [comment]
@fiskr whats a good open source markdown alternative? I'm also afraid that typora will suddenly start charging.

**Comment by AlexPasternak** [comment]
> I'm also afraid that typora will suddenly start charging.

I don't understand why the thought of paying for software you find useful is something to be afraid of. As we've seen from many free projects and apps that got shut down, I'm typically afraid of the opposite: that without an income stream, the thing I like will no longer be updated or supported. OSS is fine, but if someone can make a living charging something reasonable for an app I like, even better.

**Comment by xdvarpunen** [comment]
Honestly this is app I would pay for gladly 5-10$. It is useful!

**Comment by leewi9** [comment]
From my observation, this author does not make this app for money, it’s like a kind of experiment .

**Comment by nheeren** [comment]
I am really afraid this project is falling asleep. This one of the best pieces of software I have on my computer and I would certainly pay for it. Maybe also reboot the project with a kickstarter campaign for open sourcing it?

**Comment by dessalines** [comment]
I've been trying to find good open-source alternatives but none exist unfortunately.

**Comment by vassudanagunta** [comment]
@nheeren Huh? You say it's "one of the best pieces of software" yet you worry it's falling asleep? That's like worrying that the runner at the front of the race isn't running fast enough despite the fact that he's **still running** (Typora gets updated pretty frequently), **still ahead**, and **nobody is catching up**. 

Sure, open source would be nice, but that's not our call. @abnerlee is the person doing all the work. We can only beg him to make it open source. We are not entitled to it. And it's rather rude for *anyone* but him to "reboot the project". (And I'm still confused... one of the best pieces of software you use desperately needs to reboot?)

IMHO, Typora is good as-is. That is why so many of us use it (and call it one of the best pieces of software we use). It would be awesome if some of the open issues were addressed sooner than later. But no other editor is even close. I can't complain.

**Comment by vassudanagunta** [comment]
## BTW, do I win anything for submitting Issue #1000?

**Comment by leewi9** [comment]
Try Yu Writer 

发自 iPhone 版 Yahoo 邮箱


星期六, 十月 28, 2017, 04:31 于 Dessalines <notifications@github.com>写道：


I've been trying to find good open-source alternatives but none exist unfortunately.

**Comment by leewi9** [comment]
People are shifting for alternatives and you are still here promoting, funny!!


发自 iPhone 版 Yahoo 邮箱


星期六, 十月 28, 2017, 07:28 于 Vas Sudanagunta <notifications@github.com>写道：


@nheeren Huh? You say it's "one of the best pieces of software" yet you worry it's falling asleep? That's like worrying that the runner at the front of the race isn't running fast enough despite the fact that he's still running (Typora gets updated pretty frequently), still ahead, and nobody is catching up.

Sure, open source would be nice, but that's not our call. @abnerlee is the person doing all the work. We can only beg him to make it open source. We are not entitled to it. And it's rather rude for anyone but him to "reboot the project". (And I'm still confused... one of the best pieces of software you use desperately needs to reboot?)

IMHO, Typora is good as-is. That is why so many of us use it (and call it one of the best pieces of software we use). It would be awesome if some of the open issues were addressed sooner than later. But no other editor is even close. I can't complain.

**Comment by leewi9** [comment]
Look, this childish is crying for his lollipop So funny

发自 iPhone 版 Yahoo 邮箱


星期六, 十月 28, 2017, 07:37 于 Vas Sudanagunta <notifications@github.com>写道：


BTW, do I win anything for submitting Issue #1000?

**Comment by nheeren** [comment]
Sorry for my confusing post earlier. Due to the large number of open issues, I (apparently falsely) assumed development had stopped. Very happy to see the project is alive. My thought was that a kickstarter campaign could help the developer to make more time for creating the stable release.

**Comment by vassudanagunta** [comment]
I think people should simply ask him :)  We have no idea what his life is, or what he wants to do. 

It is also totally fair to ask him what his commitment to Typora is.

**Comment by vassudanagunta** [comment]
@dessalines Seriously? Down-voting me for saying that rather than unilaterally starting kickstarters or declaring the project needing a reboot, people should _ask the author_, the person doing the work, the one who created the thing you say you cannot find a good alternative for?

Can you tell me where I am wrong in my two comments you down-voted?

You and @leewi9 simultaneously admit Typora is amazing and the best, yet he complains about "so many bugs" and arrogantly says "It's prime time to open source Typora, so that we can let more capable and suitable guys to solve them asap", and you both down-vote me for simply asking people to be more respectful and appreciative, and less entitled?

I know should just ignore all this, but I am just saddened by the lack of respect and gratitude.

**Comment by leewi9** [comment]
Why are you always talking too much? I assume you don’t do coding, so better get the fuck out of our community 


发自 iPhone 版 Yahoo 邮箱


星期日, 十一月 5, 2017, 13:06 于 Vas Sudanagunta <notifications@github.com>写道：


@dessalines Seriously? Down-voting me for saying that rather than unilaterally starting kickstarters or declaring the project needing a reboot, people should ask the author, the person doing the work, the one who created the thing you say you cannot find a good alternative for?

Can you tell me where I am wrong in my two comments you down-voted?

You and @leewi9 simultaneously admit Typora is amazing and the best, yet he complains about "so many bugs" and arrogantly says "It's prime time to open source Typora, so that we can let more capable and suitable guys to solve them asap", and you both down-vote me for simply asking people to be more respectful and appreciative, and less entitled?

I know should just ignore all this, but I am just saddened by the lack of respect and gratitude.

**Comment by leewi9** [comment]
Why are you always talking too much? I assume you don’t code, better get the uck


发自 iPhone 版 Yahoo 邮箱 <https://overview.mail.yahoo.com/?.src=iOS>

星期日, 十一月 5, 2017, 13:06 于 Vas Sudanagunta <notifications@github.com>写道：

@dessalines <https://github.com/dessalines> Seriously? Down-voting me for saying that rather than unilaterally starting kickstarters or declaring the project needing a reboot, people should ask the author, the person doing the work, the one who created the thing you say you cannot find a good alternative for?

Can you tell me where I am wrong in my two comments you down-voted?

You and @leewi9 <https://github.com/leewi9> simultaneously admit Typora is amazing and the best, yet he complains about "so many bugs" and arrogantly says "It's prime time to open source Typora, so that we can let more capable and suitable guys to solve them asap", and you both down-vote me for simply asking people to be more respectful and appreciative, and less entitled?

I know should just ignore all this, but I am just saddened by the lack of respect and gratitude.

**Comment by dessalines** [comment]
There are too many bugs with this, I've since switched to [Retext](https://github.com/retext-project/retext), which is a great open-source markdown editor, and unlike this has a lot of active contributers.

**Comment by fiskr** [comment]
> Why are you always talking too much? I assume you don’t do coding, so better get the fuck out of our community 

I don't know who taught you to behave that way, but it's a shame. 


It is clear that the creator of Typora is greedy and won't open-source the tool. 

I too have stopped using it because of how it handles newlines. I won't be coming back unless it is made open source and I can address this problem.

**Comment by AlexPasternak** [comment]
This thread is disappointing in many ways. @leewi9, you usually contribute well to this board, but are being very rude here, and I'm not sure why. Just because people have a different opinion doesn't mean they need to be attacked and asked to leave.

@fiskr, I strongly disagree that working on a commercial license makes the author "greedy". Everyone loves free stuff, but not every app can be donation-ware. Besides, we've been using Typora all this time so far without paying. I know people have strong philosophical beliefs, almost quasi-religious ones, about open source, but I prefer whatever creates the best tools and let authors be happy with their creation and make a living.

**Comment by vassudanagunta** [comment]
@abnerlee, maybe you should close this issue and mark as won't fix. You have stated many times that you do not intend to open source Typora, that it has a commercial license, and that you want to make a living from your work on it (another thread where @leewi9 was being a bully), and that you intend to charge for it when it leaves beta. 

This issue has 56 thumbs up and 33 hearts. Keeping it open confuses and misleads people, giving them the false expectation that you are considering open sourcing it.

I also recommend that you clarify things in this repo's README. Pull request submitted.

**Comment by pgolebiowski** [comment]
> This issue has 56 thumbs up and 33 hearts. Keeping it open confuses and misleads people, giving them the false expectation that you are considering open sourcing it.

+1

> Pull request submitted.

Great that you pushed a pull request with 3 sentences that express @abnerlee's will. No matter whether it is aligned with his actual will or not, I find it ridiculous xD

**Comment by nostdm** [comment]
I'm a developer and would love to help improve the product. +1

**Comment by praveenscience** [comment]
👍

**Comment by javahemans** [comment]
👌👌👌

**Comment by vassudanagunta** [comment]
FYI, there is now another WYSIWYG Markdown editor, [Mark Text](https://marktext.github.io/website/), and [it is open source](https://github.com/marktext/marktext).  Only four months old, and not near Typora's feature set, yet.

**Comment by pgolebiowski** [comment]
Wow, the source code mode looks sooooo much like the one in Typora. Good find, @vassudanagunta.

You receive +20 to being cool.

**Comment by AlexPasternak** [comment]
> Mark Text will be open source indefinitely

Just to note, indefinitely is not the same as forever. But sure, competition is always good.

**Comment by vassudanagunta** [comment]
I just asked the dev. He said “forever”. He’ll probable change the wording. 

I hope the people who were on Abner’s case for not making Typora open source now go make contributions to Mark Text. Put up or... 😉

**Comment by poVoq** [comment]
This software is also a reasonably close open-source alternative:
https://github.com/nhnent/tui.editor

**Comment by felipehw** [comment]
This is a good libre software alternative to Typora: <https://github.com/marktext/marktext>.
Let me know if you knows a better.

**Comment by leewi9** [comment]
Sorry but this doesn’t have sidebar and file manager.

**Comment by felipehw** [comment]
There are sidebar. Look in Menu -> "View" -> "Toggle Side Bar"

**Comment by leewi9** [comment]
what about sidebar TOC and folder manager?
