### ISSUE TITLE
Please add code block folding function, thanks.

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#161]
folding, like in IDE, please add if you can make it.

**Comment by abnerlee** [comment]
Folding according to headings, right?

**Comment by leewi9** [comment]
like this, seems not that simple as according to headings

<img width="1251" alt="2016-05-17 12 23 05" src="https://cloud.githubusercontent.com/assets/10832544/15311118/22926256-1c2a-11e6-99db-0291542e568e.png">

**Comment by abnerlee** [comment]
Folding code blocks seems low priority since it is not a common requirements. Besides, the code block would still show when share or export.

Avoid pasting too long code in code blocks could solve this for all readers. 
When you have to paste the whole code, use external file or gist link would help. 
While in most case, using only significant snippets is the right answer for this kind of scenario.

**Comment by vassudanagunta** [comment]
I totally agree. Typora is not an IDE!  It's for writing prose that may include code (such as in a tutorial), in which case if you need folding to make your article readable you are doing it wrong! :)

**Comment by leewi9** [comment]
It's already closed.


2016年5月18日 +0800 05:01 Vas Sudanagunta<notifications@github.com>，写道：

**Comment by vassudanagunta** [comment]
@leewi9 I know. GitHub is a community where users often express approval or disapproval of choices. As a developer myself, I highly value feedback from my users, both before and after I make decisions. I've been a Typora users since v0.1. In fact, it was I who suggested creating this GitHub Issues repository. No need to be snippy. :)

**Comment by leewi9** [comment]
@vassudanagunta I assume you being too sensitive. I apology for anything that uncomfort you.

**Comment by leewi9** [comment]
![2016-05-18 13 56 47](https://cloud.githubusercontent.com/assets/10832544/15348844/6337ac40-1d00-11e6-822b-bd03269cbf3c.png)

just received an email sent from a guy less than 15 years old.

**Comment by eevilspock** [comment]
Whatever dude. You must be lonely. Feel sorry for you.  I don’t care what
you reply, this is the last you will hear from me. You are a child.
Hopefully one day you grow up.


On May 18, 2016 at 1:57:43 AM, leewi9 (notifications@github.com) wrote:

[image: 2016-05-18 13 56 47]
<https://cloud.githubusercontent.com/assets/10832544/15348844/6337ac40-1d00-11e6-822b-bd03269cbf3c.png>

just received an email sent from a guy less than 15 years old.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/typora/typora-issues/issues/161#issuecomment-219932348>

**Comment by leewi9** [comment]
![2016-05-18 14 10 34](https://cloud.githubusercontent.com/assets/10832544/15349176/72315ee6-1d03-11e6-917e-143e1314a89d.png)

already created an personal attack ticket to Github official support, this posted here as reference.

**Comment by AlexPasternak** [comment]
FWIW, Atlasssian's Confluence, which is my favorite wiki ever, does allow code folding blocks, even though it's not an IDE. E.g., you could read about possibilities of a large API, but only expand samples for those functions in which you're interested.

That said, I agree that Typora would not be greatly enhanced by having this functionality, as it's an editor. For personal documentation, it could be marginally useful, but as a "nice to have".

On a side note, not to get dragged into this, but I do agree that personal emails are not meant to be posted, even when they're from rude unappreciative people.

**Comment by leewi9** [comment]
It's not email from Hillary, I can not see why I can't post public

Also it's not personal, who the hell want to have this kind of personal things with that crazy ?


2016年5月18日 +0800 22:39 AlexPasternak<notifications@github.com>，写道：
