### ISSUE TITLE
 remember last export path

### ISSUE THREAD

**Issue by xgdgsc** [typora/typora-issues#1614]
Now every time I export to pdf it would go to my linux home foler root path, rather than the last used export path, which is inconvenient. A one click export to last path button would be more desirable.

**Comment by NeroVanbiervliet** [comment]
I use typora on linux (ubuntu) as well as on windows. The behaviour of pdf export on these systems is different:
* Windows: will open the directory where the .md file is located
* Ubuntu: will open my home directory

**Comment by ArtDan** [comment]
Personally I would love when export would offer me the directory of the *.md file, because in 90% of all cases I'd like to save an exported PDF next to its *.md file. And it can be very time consuming to navigate back to the *.md all the time.

Maybe it would be feasible that
* Every Typora window stores a last-export-path
* And last-export-path is initialized with the directory of the opened *.md file

**Comment by abnerlee** [comment]
supported such option
