### ISSUE TITLE
is there a way to use highlight.js to render code in preview?

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#163]
https://highlightjs.org

Please guide me if it can.

**Comment by abnerlee** [comment]
Unfortunately, we use [CodeMirror](https://codemirror.net/) for editing code blocks which contains syntax highlight functions, and I don't think it support highlight.js.

So, you are not satisfied current syntax highlight performance, or there's some unsupported language you want to use?

**Comment by leewi9** [comment]
thanks, what i want to do is to customise code syntax color when preview, for example, i like change comment color to green, so i edit the `github.css` file under `theme` folder.

```
.cm-comment { color: green !important; }
```

but i also want to customise other syntax colours, and I'm  not familiar with CodeMirror, i don't know if there's a relationship between them. or maybe i have to add more lines to the css file.

regards,

**Comment by leewi9** [comment]
```
.CodeMirror-code {
    font-family: 'Courier New' !important;
}
```

I used to `Courier New` when preview code, I can change by css file.

Everytime i update Typora, i have to restore this css file to get my config back.

**Comment by abnerlee** [comment]
> thanks, what i want to do is to customise code syntax color when preview

There's a sample CodeMirror style, <https://gist.github.com/abnerlee/b522c4caf3a74c499fca04a378ea28b7>
syntax highlights are classes starts with `cm-`, like `cm-number` for integers. The class naming rule is is provided by CodeMirror.
`.cm-s-typora-default` specifically applies to "Source Mode" Markdown syntax, `.cm-s-inner` specifically applies to Code Fences.

> Everytime i update Typora, i have to restore this css file to get my config back

Yes,
1.  Currently all theme css are undocumented.
2.  There's no easy way to do small modifications to existing CSS like changing font. User need to copy and modify an existing theme file.

That's because basic CSS are changing during early development of Typora, but now basic CSS is relatively stable, so I'm starting to write documents for this part, and provide features like #91, hopefully an improved theme function can be introduced in next or next next version up.

**Comment by leewi9** [comment]
Thanks I get it, no wonder they are start with `cm`


2016年5月19日 +0800 18:25 AbnerLee<notifications@github.com>，写道：
