### ISSUE TITLE
location for conf.user.json on mac

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [typora/typora-issues#1641]
I'd like to update the autosave frequency per [docs](https://support.typora.io/Auto-Save/), however it's not clear where I should place the *conf.user.json* file. Currently on macOS High Sierra.

**Comment by abnerlee** [comment]
On macOS, we do not provide `conf.user.json`

`autosave`  is a part of OS X, so we do not have configuration about it.

**Comment by clokman** [comment]
Having a conf.user.json file on Mac would be beneficial to control the auto-save behavior. Currently, on MacOS, the auto-save feature triggers on focus change. I have been searching for a way to make Typora save every 500 milliseconds so that the Markdown-based website I am building updates automatically on my second monitor without requiring me to switch windows or press ⌘S manually. 

I would very much like to see this feature as either a conf.user.json file for MacOS or as a preferences menu option.
