### ISSUE TITLE
Justify

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#166]
There seems to be no way to justify the text using css without breaking a lot of things. But spare some justice to justification! For example, could this be done via javascript?

Also, just to satisfy my curiosity, why is `white-space: pre-wrap` needed (the thing preventing justification)?

**Comment by abnerlee** [comment]
Duplicate as #42

> Also, just to satisfy my curiosity, why is white-space: pre-wrap needed (the thing preventing justification)?

Without `white-space: pre-wrap`, tab in HTML is ignored and two or more whitespace will only display as one. To show whitespace in HTML, normally they are escaped as `&nbps;`, but `&nbps` is different unicode to whitespace, so `&nbps` and whitespace could get missed up.

> There seems to be no way to justify the text using css without breaking a lot of things. But spare some justice to justification! 

Actually, in Chrome `white-space: pre-wrap;` and `text-align: justify;` can be supported with the same time, and it should be so since there are no conflicts between these two rules. But Typora for Mac is based on Webkit and share almost same things with Safari, and unfortunately, `text-align: justify;` not work for `white-space: pre-wrap;` in Safari.

So, it is actually Apple's bug, and the best solution is to fix this bug for Safari by Apple.

> For example, could this be done via javascript?

One solution I come up with is to show "tab" and "whitespace" with specifal `<span>` element, but those element is either `inline-block` or `white-space: pre-wrap` or else the tab and whitespace still cannot be rendered correctly. 

The problem is 
1. It seems complicated for implementation.
2. `text-align: justify;` may still not work well on Safari since there are inline elements with `inline-block` and `white-space: pre-wrap` mixed with other elements.
3. The width of whitespace and tab is actually flexible, according to your text, especially when the style is `text-align: justify;`, but the `span` we created for "whitespace" and "tab" is hard to have a flexible width.

Maybe there are other solutions on js side, but "tab" is always ignore without `white-space: pre-wrap` or `white-space: pre`, unless we make a "tab" by HTML elements or set margin/padding/width to simulate a "tab", while in that case, how to correctly calculate the proper width for the "Tab" to make text "justify" under "justify" alignment?

**Comment by yatharthb97** [comment]
Is there a solution for justified text in Typora yet? It is really a deal breaker, especially for academic writers, where such requirements are enforced.
