### ISSUE TITLE
Change awkward characters / keys in shortcuts or allow to customize

### ISSUE THREAD

**Issue by luisspuerto** [typora/typora-issues#1673]
This issue is related to #1548

----

Inline code shortcut isn't working here... even using the [grave accent](https://en.wikipedia.org/wiki/Grave_accent) `` ` `` . 

![](http://g.recordit.co/fdXdMCtqwB.gif) 

The problem using such a symbol is that at least in my keyboard it expect an additional character to work. Either a vocal to be the accent of a space to be a single symbol. The true is that they aren't symbols on their own but complements. Perhaps in some keyboards they are, but not for example in one with Spanish layout. 

![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/spanish_notebook.png)

The same happens with the strike shortcut `^~`. In my keyboard to put `^` I need to press ``shift + ` `` keys and to get the [tilde](https://en.wikipedia.org/wiki/Tilde) alone I have to press `alt + Ñ`. Pretty awkward combination. 

I recommend that you change those shortcuts to more conventional characters or at least you gives the option to customize. 

For example inline code could be `shift + cmd + k` and strike `cmd + ctrl + s`. But please don't use special characters because oftentimes they are in awkward places in different layouts. 

PS/ I live in Finland, my wife has a computer with a Finnish/Swedish layout, and sometimes things could go really really awkward 😠. Tilde key is pretty impossible. 

![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/swedish_notebook.png)

**Comment by GandalfSaxe** [comment]
It's not something Typora can fix IMO. So many choices of symbols and syntax in computer software is dictated by the fact that the computer industry was predominantly shaped by people using American English keyboard layouts. The backpack / grave accent character (`) is a widely used convention for formatting text as code/verbatim/monospace everywhere by now. I'd be insanity if Typora would go with it's own symbol for this.

I do have a series of suggestions for you, because I'm Danish and have gone through some keyboard pains as well:

1. Switch to using the US International keyboard layout. It maps fairly well unto these scandinavian keyboards, and there will be a time of adjustment, but trust me it's worth it if you're anything but a casual computer user. Everything, including `[] {} /|\\~` and yes the ` itself is so much more accessible.

2. You can quickly switch between keyboard layouts using Ctrl+Space on Mac (Win+Space in Windows).

3. On Mac, you can customize your own keyboard shortcuts in System Preferences -> Keyboard -> Shortcuts, either as applying globally to all apps, or specifically to e.g. Typora. This is one of the big benefits macOS have over Windows IMO.

Finally I don't know why the problem you showcase in the GIF in your first post happens. I'm guessing it's because you input the ` symbol with a chord, not directly with a single press of a key? Some people made some very bad choices on non-English keyboards back in the day on symbols such as ~ and `, thinking it was only for letters and not as actual symbols in programming/typesetting purposes. It's regrettable, but the best thing I ever did with my keyboard was to accept the English layout as a superior default and then work to get what I need from there. Luckily in Danish I'm quite lucky that æ ø å are all very accessible with the default shortcuts Opt+', Opt+O, Opt+A. You could also be lucky that special Finnish characters are also simply mapped to similar strokes.

One Thing Typora could do is to provide Windows users a way to change the shortcuts easily if they insist on using non-English keyboards, and some things are not working so well, as you've found. On Mac, we fortunately have a native solution in the System Preferences as mentioned.

**Comment by luisspuerto** [comment]
@thanks fo the tip about to customize the shortcut on mac. Anyhow I find the two default shortcuts i mentioned unfortunate.

**Comment by GandalfSaxe** [comment]
I can see what you mean, because users on English / sane keyboard layouts can simply select any text and press back tick, which wraps back tick around the selection, so there is no need for any Ctrl+Shift+` anyway. So a default shortcut for Format->Code that are more friendly to weird keyboards would make sense, yes.

Same story with Format->Strike because you can simply make the selection and press ~ twice on English-type keyboards.

So yeah I'd be in favor of default keymap change on those two things. However it's always difficult to pick one that's good. Ctrl+Shift+K is shortcut for "Delete line" in many modern editors, including VSCode and Sublime, so that could result in some annoying muscle memory conflicts. Don't have any other suggestion though, but I guess you could find something that works.

**Comment by abnerlee** [comment]
https://support.typora.io/Custom-Key-Binding/

**Comment by GandalfSaxe** [comment]
@abnerlee Does `conf.user.json` work on macOS as well? Would be easier to modify and backup / restore in case of OS reinstall.
