### ISSUE TITLE
Support importing embedded media with pandoc

### ISSUE THREAD

**Issue by leepfrog-ger** [typora/typora-issues#1725]
I noticed that when importing Word documents (docx) with embedded documents that the embedded images seem to be recognized but not imported (I've tried with 0.9.56 beta on Windows).

In the .md file they will show up as something like `![](media/image5.png){width="6.298611111111111in" height="0.6319444444444444in"}` but they are not written to the location of the markdown file.

Looking at the [pandoc documentation](http://pandoc.org/MANUAL.html#reader-options) this seems to be  possible to realize with the `--extract-media=` option. 

If that would be built in that would be a huge help because currently we need to manually add the images back after importing.

**Comment by jayjlawrence** [comment]
+1 
merge with #1451 ?

**Comment by jayjlawrence** [comment]
@abnerlee +bounty https://www.bountysource.com/issues/62571002-support-importing-embedded-media-with-pandoc

**Comment by abnerlee** [comment]
#249

**Comment by abnerlee** [comment]
`--extract-media` is not needed for docx export

>  If the source format is a binary container (docx, epub, or odt), the media is extracted from the container and the original filenames are used. Otherwise the media is read from the file system or downloaded, and new filenames are constructed based on SHA1 hashes of the contents.

Its means Pandoc will fetch the image automatically. If not work, please upgrade Typora to latest version first.

**Comment by jayjlawrence** [comment]
Thank you for this info.
* I am running Typora Version 0.9.9.19.4 (1355).
* I have Pandoc 2.5 via Homebrew (same for 2.4)
* Using Word 15.13.3 I created a document called TestTypora.docx that includes 2 pasted png images
* My sidebar is showing "FILES" to a directory called "typora-issues"
* Using the menu File/Import ... I imported the Word document

gives ...

* The resulting markdown shows "media/..." for the image paths
* no folder called "media" was created in "typora-issues" 
* I have no 'defaults' set for Pandoc to the best of my knowledge

and ...

* I searched for image1.png and it wasn't created anywhere else on the filesystem
* The word document is not a bundle but a compressed archive.
* Uncompressing the document shows a 'word/media/image1.png' file

also ...

* I would expect media files to be copied to "typora-issues/assets" regardless of where they are found because I have "copy  image to ./assets" selected for Images Insert. (I view this as an equivalent case)
* I would also expect that the markdown file would be written to "TestTypora.md" in the "typora-issues" directory
* If the markdown filename cannot be determined then current functionality is good.

Let me know if you need logs or anything else.

[TestTypora.docx](https://github.com/typora/typora-issues/files/2719510/TestTypora.docx)
[The year in review.md](https://github.com/typora/typora-issues/files/2719511/The.year.in.review.txt)

**Comment by jayjlawrence** [comment]
FYI ... see https://github.com/jgm/pandoc/issues/4127 where jgm, author of Pandoc, explains:

> It's a basic principle that we don't write files unless we're explicitly told to.

**Comment by leepfrog-ger** [comment]
> `--extract-media` is not needed for docx export

I think there may be a misunderstanding here. The issue is regarding imports (docx -> typora), not exports.
