### ISSUE TITLE
Document Typora's mission and design philosophy

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#183]
Looking at RFE issues that have been submitted, it's clear that many issue submitters do not know that Typora is supposed to be "a truly minimal markdown editor" as declared on [its homepage](http://www.typora.io).

If Typora's mission and design philosophy are documented (perhaps in a doc in the typora-issues repo), it would help people understand what kind of requests make sense. And when an idea is rejected, an issue comment could link to the mission/design philosophy doc.

**Comment by leewi9** [comment]
Some good people doing the real work while some dudes just keeping talking
about philosophy.  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Jun 10 2016, at 11:03 am, Vas Sudanagunta &lt;notifications@github.com&gt;
wrote:  

> Looking at RFE issues that have been submitted, it's clear that many issue
submitters do not know that Typora is supposed to be "a truly minimal markdown
editor" as declared on [its homepage](http://www.typora.io).

>

> If Typora's mission and design philosophy are documented (perhaps in a doc
in the typora-issues repo), it would help people understand what kind of
requests make sense. And when an idea is rejected, an issue comment could link
to the mission/design philosophy doc.

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly, [view it on GitHub](https://github.com/typora
/typora-issues/issues/183), or [mute the thread](https://github.com/notificati
ons/unsubscribe/AKVKoOE0gCsImX0j_FpWUm2vJuFpVTCxks5qKNPugaJpZM4Iylci).![](http
s://github.com/notifications/beacon/AKVKoFYTFNW0hGTzn2spdDe6fK23knILks5qKNPuga
JpZM4Iylci.gif)

**Comment by smallx** [comment]
+1

**Comment by abnerlee** [comment]
Typora is originally created as an experiment about "what a markdown editor should look like", since I just cannot find a proper one. Then opened up to users include myself, providing a simple yet powerful way to read and write markdown.

The minimal UI is introduced to make users focus on writing without being distracted by annoying buttons, icons, toolbars, especially for 13in screen users like me. In other words, the "minimal" is a key feature of typora to improve users productivity. 

Meanwhile, some functions will be integrated to "simplify" user's workflow in some cases, while avoiding complicate other users' workflow by keeping typora "minimal".

So, yes, typora's main design philosophy is "minimal" (KISS), but mission is to solve real problems and improve writing/reading experience of markdown, and KISS rule is just the key to achieve it.
 
-----

The Github issue page is originally opened because I wanted to open pre-order of typora, so paid users should know which features typora will implement after beta, which won't, which maybe (actually most features is "maybe") in 1.0. 

Then I withdrew the plan of pre-ordering, since many users have been cheated by the "pre-order" event of some Markdown editor once. 

But anyway, they are first my users, then contributors,  therefore, I don't want to setup any rules on their requirements and I want know their complaints and ideas.

Besides, not all issues will be implement in Typora 1.x. Since:
1. it is impossible to satisfy all users.
2. many requirements are not real requirements, and many users actually do not know what they want. 
3. technical compromise
4. implement time is limited and developers are just lazy.

But I have bigger plans in future if I can make some money from Typora 1.x.

----

Also , please be polite when commenting other users' comments

**Comment by vassudanagunta** [comment]
Thanks for the clarification, @abnerlee.
