### ISSUE TITLE
Privacy policy of Typora software too unspecific

### ISSUE THREAD

**Issue by GiantCrocodile** [typora/typora-issues#1842]
In the privacy policy of the software you state this:
```
We will only collect: when you use Typora, how long you stay on it, your operation system, system language, and other very basic information anonymously via google analytics.
```

- What is `other very basic information`?
- How precisely do you collect the operating system? Does it contain specific installed update versions or only `Windows 10`? 
- Where is the data physically stored?
- With who do I have a contract? I don't find any name and company address.
- Is Google Analytics always used or only if `Send Anonymous Usage Info` is enabled? This isn't clear to me.

Please improve the privacy policy regarding this.

**Comment by abnerlee** [comment]
> Is Google Analytics always used or only if Send Anonymous Usage Info is enabled? This isn't clear to me.
[This](https://support.typora.io/Privacy-Policy/) says "Anonymous usage data will only be send when the option “Send Anonymous Usage Info” is enabled in preferences panel. If you disable the option, no data will be collected to us. (The option can be opt-out, but may need a restart of Typora for the option to apply)."

> What is other very basic information?
> How precisely do you collect the operating system? Does it contain specific installed update versions or only Windows 10?
> Where is the data physically stored?
> With who do I have a contract? I don't find any name and company address.

Please refer our link towards google analytics https://policies.google.com/privacy?hl=en

But we will update the privacy policy since we may abandon google analytics.
