### ISSUE TITLE
Sometimes can not delete chars and lost the last inputed content ( already save the file)

### ISSUE THREAD

**Issue by wuyad** [typora/typora-issues#1855]
Mac os 10.14 with chinese input method.
seems conflict with chinese input method.

**Comment by abnerlee** [comment]
What's your Typora version and which IME did you use? Are there any ways to reproduce it?

**Comment by behind47** [comment]
I'v met the similar problem occasionally. Related info as follows:
  1. Mac os 10.10.4 with Chinese input method.
  2. Typora version  0.9.9.19.
  3. Mac system IME with Chinese input source.

I'm sorry I cannot provides stable ways to reproduce it, but theses conditions may do help:
  1. Chinese content.
  2. A large Amount of unsaved words which makes Typora slow, but not necessary.

When I use Chinese input method, I firstly enter English chars in IME, then IME shows Chinese chars for I to choose. 
This problem occurs when I enter English chars, then I choose Chinese chars and press enter, but failed to enter Chinese chars, English chars are entered and I can't delete them with backspace. And since that, only English chars can be entered, I am only able to delete them by select them and enter new chars.
I'll supplement if I find more ways to reproduce it.

**Comment by behind47** [comment]
I suffered the problem 2~3 times since last comment and I found that switching to source-code-mode  and editing can bypass the problem quickly, switching to normal-mode then is also okay.

**Comment by whitebob** [comment]
I have encountered the same problem. And I find more details about this problem:

Under such condition the last line will become a <div></div> block with style="orphans: 4".

The last line will not have cid and thus could not be seen under command+/ source mode, although the last line number will be there but shown as blank.

Under this condition, the delete key and enter key will not work, and if you input more than one character in Chinese, there will be no output or just a blank.  

At the same time if you look up in the js console, you will see some warning:
TypeError: null is not an object (evaluating 'F.cid')
prepNode — main.js (line 5043)
l — main.js (line 33035)
dispatch — main.js (line 30334:193)
handle — main.js (line 30300:102)
r — main.js (line 23620)
<img width="610" alt="error" src="https://user-images.githubusercontent.com/15847413/49518424-98cd8e80-f8d9-11e8-823f-6e2af8aa5dbf.png">

**Comment by whitebob** [comment]
This error is not easy to repeat, however, I feel it might have some relationship with the touching pad. And when this problem happens, most of time the cursor will jump to the beginning of the first line. I think it might be some special escape encoding caused by certain characters in Chinese or from touching pad events .  AndI don't think it is a conflict with Chinese IME. I use the system SCIM and also the Squirrel/Rime IME, and the problems are exactly the same.  
 
I really love Typora and hope it become better and better! 
PS: my Mac OSX 10.11.6 
input method: Squirrel 0.9.26.1

**Comment by behind47** [comment]
I found a way to repeat this error easily on Mac OSX 10.10.4 with system Chines IME and typora version 0.9.9.19.4(1355) beta:
1. new an empty typora file.
2. enter several characters, then delete them without pressing space or enter/return.
3. then you can see the cursor jumping to a line even before the first line, now Chinese IME is invalid.

**Comment by abnerlee** [comment]
still exist in latest macOS version of Typora? relates #3387
