### ISSUE TITLE
I would love to pay for Typora

### ISSUE THREAD

**Issue by kontrafiktion** [typora/typora-issues#1903]
I have read https://github.com/typora/typora-issues/issues/890.
I use Typora all the time and really feel like cheating, because I didn't pay for such a polished product.

**Comment by GiantCrocodile** [comment]
You would like to pay without any real info about price, payment model, payment methods, in detail infos about the company, warranties and all? That's totally weird. I agree that I like this software but for commercializing it, we lack still some things/information.

**Comment by abnerlee** [comment]
Thanks for loving Typora. Really appreciate it :)

We would open the payment on v1.0. For now, we didn't even set up the payment method ~ We are still busy on developing towards a 1.0 version which met our expectation.

**Comment by gnzlbg** [comment]
> You would like to pay without any real info about price, payment model, payment methods, in detail infos about the company, warranties and all? That's totally weird.

No it isn't. @abnerlee I use this software every day and I'd like to support you in your endeavor of working on it. Do you have a patreon or something that I could use to support you while the software is still in beta?

If typora was on sale for 100$ I probably wouldn't buy it. OTOH if I could support typora's ongoing development for 1$/month or so it is very likely that I would for as long as you continue to improve it.

Even if typora was open source, I would still support somebody that improves it for me. The only difference that it being open source would made for me is that instead of just filling issues for nitpicks, I might fill in PRs every now and then, but that's about it.

**Comment by abnerlee** [comment]
I actually didn't get the payout accounts for Typora ready ~

So for you, you may 

- Support via paypal (<hi@typora.io>).
- Consider a purchase of https://appmakes.io/paletro if you're on macOS.

**Comment by kontrafiktion** [comment]
I have just paid half the amount, I would pay for the software without even thinking about the price. If would be more expensive, I would still consider purchasing it. 
I think my payment is for the value I already received
