### ISSUE TITLE
SideBar-Openfolder cause screen freeze

### ISSUE THREAD

**Issue by reTsubasa** [typora/typora-issues#1976]
OS：Ubuntu 18.04.1 4.15.0-39-generic #42-Ubuntu SMP
Typora version:0.9.60

screen freeze at "Toggle siderbar" - "Open Folder" ,then gnome freeze

**Comment by abnerlee** [comment]
same with https://github.com/typora/typora-issues/issues/1516?

**Comment by reTsubasa** [comment]
run typora from terminal,when the freeze happen,terminal show the info "Gtk-Message": _time_ GtkDialog mapped without a transient parent. This is discouraged.
i found even can not use the mouse,the keyboard is still work,this freeze can easy exit by press ”ESC“.
i had install the typora via `apt-get`，

**Comment by hongwen000** [comment]
Also having this problem. I have both KDE and Gnome3 installed, and I tried the binary one and the `pacman -S archlinuxcn/typora` one, but always meet this bug.
The situation is similar to that described by @reTsubasa. However I don't have gkt warnings in the terminal.(Maybe because I'm using KDE now?)
- OS: Archlinux (`Linux four 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux`)
- Typora version: 0.9.60(beta)
- Gtk3 version: 3.24.1+8+g220f77d8c1-1

**Comment by ljylin** [comment]
I Also having this problem. KDE4 installed,The situation is similar to that described by @reTsubasa. I don't have warnings in the terminal.

- OS: CentOS Linux release 7.5.1804 (Core)
- Kernel version: 3.10.0-862.el7.x86_64
- Typora version: 0.9.60(beta)
- KDE: 4.14.8

**Comment by abnerlee** [comment]
I'm not able to reproduce this. Please reopen this issue if it still happens in 0.9.62
