### ISSUE TITLE
Who is behind typora?

### ISSUE THREAD

**Issue by biquini** [typora/typora-issues#2007]
I think there could be some more clarity on the person/company that develops Typora. All I have found is a blog post by @abnerlee from 2015 on why Typora was developed, as well as a twitter profile ( https://twitter.com/LeeAbner ) which frankly raises more questions than it answers.

I can understand if for professional (or political?) reasons, the developer prefers to remain anonymous but some more clarity would certainly be nice. Or at least an explanation why the developer wants to remain anonymous. How do we know that we can trust Typora to not install malware?

Also, it is great that you have a privacy policy but it seems quite worthless without a name and address for the person that publishes it. Who would be responsible if you would breach your privacy policy?

**Comment by abnerlee** [comment]
No professional/political reasons maybe, I just think who I am is my privacy, I respect my users' privacy, so I don't collect user's identify, but I want my privacy should get protected too.

Since Typora on macOS are code signed by my Apple Developer ID, you may be able to track me via Apple Inc with legal reasons. After v1.0, Typora will be a paid app, so you may ask police to track me via payment companies and my back account. 

But it should be acceptable that my privacy also gets protected if I didn't do anything illegal.

Since Typora is a small side protect in early stage, so that is the current solution. Typora on Windows would get coded signed too in future, which would requires a company or real name.

**Comment by biquini** [comment]
I don't want to be a party pooper but a lot of bad things can be done without doing anything illegal unfortunately. Neither do I think having the code signed by an Apple developer ID means much (if you released it through the Apple App Store there would at least be some review of the software). You also seem to say above that even the Apple developer ID is not in a real name or company contrary to the windows version which "requires a company or real name".

Had it been an open source project things would obviously be very different: it would allow users to review the code. You are asking users to have blind faith and install software on their computers that is published by someone who wishes to remain anonymous. I know it's a free beta but I still think that is asking for a lot.

Even if you have the best of intentions with Typora, in general it is a really bad idea as a user to install software where there is no accountability or possibility to review the source code. By doing so, sooner or later they will install software from someone who wishes to remain anonymous because they have less admirable intentions.

**Comment by doncabreraphone** [comment]
This thread shouldn't be closed. We need to know more about who's behind this to be able to trust.

**Comment by FranklinYu** [comment]
Maybe publishing in App Store would alleviate the concern? #361 

 1. Apple reviews the app before publishing it. 
 2. Force the application to use Sandbox, which prevents a lot of bad behaviors (like scanning your disk).

When I have to use macOS application from companies (which is unfortunately inevitable), I would prefer an application from App Store over a simply code-signed one.

**Comment by hasii2011** [comment]
So who is behind this app?
