### ISSUE TITLE
Custom keybinding not work

### ISSUE THREAD

**Issue by Sytronik** [typora/typora-issues#2013]
OS: Windows 10 version 1803
Typora Version: 0.9.60
Language: Korean

I set the custom keybinding as follows:

``` 
 // Custom key binding, which will override the default ones.
  "keyBinding": {
    // for example: 
    // "Always on Top": "Ctrl+Shift+P"
    "Table": "Ctrl+Alt+T",
    "Math Block": "Ctrl+Alt+B",
    "Inline Math": "Ctrl+Alt+E",
    "Quote": "Ctrl+Alt+Q",
    "Code Fences": "Ctrl+`",
    "Refresh All Math Expressions": "Ctrl+R",
    "Clear Format": "Ctrl+Shift+F",
    "Toggle Sidebar": "Ctrl+\\"
  },
```
But they don't work except "Toggle Sidebar."
(I didn't edit any other lines in conf.user.json file.)

The thing is, the menu item in Typora shows my custom keybinding exactly.
I tested on two Windows PCs with the same configuration, and the same situation occured.

**Comment by abnerlee** [comment]
> the menu item in Typora shows my custom keybinding exactly.

This means the shortcut are successfully set.  I could not give good advice since I cannot reproduce this. You may check:

- Those menu items are enabled or not
- Try different (left/right) ctrl or alt key combination.
- Check if Alt+Key will insert special character like `ō` or something in certain keyboard layout that is not American-English.

**Comment by Eskander88** [comment]
But, if keybindigs haven't defined problems?
