### ISSUE TITLE
Bulk Increase/Decrease heading level

### ISSUE THREAD

**Issue by dericke** [typora/typora-issues#2037]
The **Increase/Decrease Heading Level** commands are great tools. However, if I highlight a large block of text containing more than one heading, I would expect that these commands would promote or demote all the headings within the highlighted text. Instead it appears that these commands currently will only work on the first heading within the highlighted text, and then only by hotkey—the menu items are disabled when text is highlighted.

If these commands were made to work on multiple headings at once, it would be very helpful for times when the context of an article changes. For example, copying a standalone article from a page and converting it into a section of another article.

Thanks!

**Comment by abnerlee** [comment]
An article is usually:

One Header, followed by many paragraphs.

So when will a use select a ranges of paragraphs and convert them all into same level headers?

**Comment by dericke** [comment]
I wouldn't expect the function to convert paragraphs to headings, only to increase/decrease the level of headings which are already marked as such.

Did I understand your question correctly?

**Comment by willismorse** [comment]
I have what I believe is the same need.

I write large documents that contain a large number of nested headers at many different levels. I often find the need to insert a higher level section after the fact, and need to shift the existing material down one level to allow me to insert a higher level.  

Being able to select large amounts of text in the main editor and apply "Increase Header" or "Decrease Header" would handle this use case. This would not affect the structure of any lines/paragraphs except headers. It is logically the same operation as "Increase Indent" and "Decrease Indent", applied to headers instead of lists.

Being able to do this from within the Outline view would be better. The challenge to performing this sort of operation  in the main edit view is that selecting multiple levels of text within a long document is challenging when you have to scroll around to find the bounds of the selection range.

Simply increasing and decreasing a single item in the Outline would be a nice enhancement. Being able to select multiple items within the Outline view and increase/decrease as a group would be even nicer.

## Example use case

Starting from this:
```
# Products
## Product 1
### Details about Product 1 
## Product 2
### Details about Product 2
```

I would like to transform to this in one operation:
```
## Products
### Product 1
#### Details about Product 1 
### Product 2
#### Details about Product 2
```

so that I can add a new top level section:
```
# Introduction
## Products
### Product 1
#### Details about Product 1 
### Product 2
#### Details about Product 2
```

**Comment by spirosag** [comment]
Is this feature implemented? I would love to have it.

**Comment by vassudanagunta** [comment]
@spirosag No, not implemented. 

@abnerlee close the issue, but clearly from his comment above he did not understand the request. I've stated it more clearly in a new issue, #2375, with a solution that doesn't require highlighting except when you need more control.

**Comment by chdonncha** [comment]
Has this been implemented since? Would be extremely beneficial when I have some overhauls.

**Comment by DC-Jade** [comment]
I guess you could use **find+replace** to implement it **in source code mode**. 
First, select **<source code mode> in <view> toolbar**; 
and then **find '#' and replace it with '##'**
