### ISSUE TITLE
Pandoc doesn't work on typora....

### ISSUE THREAD

**Issue by Adolf-L** [typora/typora-issues#2040]
>  **1、Install pandoc successful**

<img width="879" alt="tt1" src="https://user-images.githubusercontent.com/10137107/50383589-0824ea00-06f2-11e9-95ef-1bd9712c9db6.png">

>  **2、restart typora, but pandoc still doesn't work**

<img width="1066" alt="tt22" src="https://user-images.githubusercontent.com/10137107/50383588-065b2680-06f2-11e9-9393-eb808f9d75e2.png">

> **3、version info**
<img width="671" alt="ttt3" src="https://user-images.githubusercontent.com/10137107/50383616-c0eb2900-06f2-11e9-8ac5-eb67df46d9b4.png">

**Comment by merlinuwe** [comment]
I had the same issue with typora 0.9.62 under windows 10 64 bit. (I tried both available .msi files.)
When I use pandoc 32bit I get

```
C:\Users\XXXXX>pandoc -v
Cannot find file at 'c:\program files (x86)\pandoc\pandoc.exe' (c:\program files (x86)\pandoc\pandoc.exe). This usually indicates a missing or moved file.
```
I tried to export some files (docx, OpenOffice, rtf, ...) an always get this message:

![unbenannt](https://user-images.githubusercontent.com/4138869/51212114-d7faf080-1917-11e9-8c3f-3a9fecc68df5.jpg)

When I uninstall pandoc32 bit, reboot, install pandoc64 bit, I have the same issues than Adolf-L.

**Comment by merlinuwe** [comment]
I had the same issue with typora 0.9.62 under windows 10 64 bit. (I tried both available .msi files.)
When I used pandoc 32bit I got

```
C:\Users\XXXXX>pandoc -v
Cannot find file at 'c:\program files (x86)\pandoc\pandoc.exe' (c:\program files (x86)\pandoc\pandoc.exe). This usually indicates a missing or moved file.
```
I tried to export some files (docx, OpenOffice, rtf, ...) an always got this message:

![unbenannt](https://user-images.githubusercontent.com/4138869/51212114-d7faf080-1917-11e9-8c3f-3a9fecc68df5.jpg)

When I uninstalled pandoc32 bit, reboot, install pandoc64 bit, I had the same issues than Adolf-L.

The **solution**: 

The problem was: I a) had to install the 64 bit version of pandoc and I b) had to manually (!) set the PATH for both the user and the system at the first lines of the environment variables. 

(Perhaps helpful: Look, that there are no old or second installations of pandoc in C:\Users\USER\AppData\Local and reboot windows after the installation.)

-HTH

**Comment by fightingwing** [comment]
> > **1、Install pandoc successful**
> 
> <img alt="tt1" width="879" src="https://user-images.githubusercontent.com/10137107/50383589-0824ea00-06f2-11e9-95ef-1bd9712c9db6.png">
> 
> > **2、restart typora, but pandoc still doesn't work**
> 
> <img alt="tt22" width="1066" src="https://user-images.githubusercontent.com/10137107/50383588-065b2680-06f2-11e9-9393-eb808f9d75e2.png">
> 
> > **3、version info**
> 
> <img alt="ttt3" width="671" src="https://user-images.githubusercontent.com/10137107/50383616-c0eb2900-06f2-11e9-8ac5-eb67df46d9b4.png">

Hi I'm wondeirng if you have found out the solution to this problem. I'm troubled by this problem too as well for a long time. Typora version <0.9.9.32.1 (4191)>, OSX<10.15.4>, and pandoc installed successfully and I can even run it in the shell. Thanks in advance!

**Comment by abnerlee** [comment]
#1721

**Comment by abnerlee** [comment]
#1169
