### ISSUE TITLE
How to move Typora configuration directory ?

### ISSUE THREAD

**Issue by thechile** [typora/typora-issues#2088]
Hi

On Windows by default Typora configuration is located `C:\Users\scott.mcgillivray\AppData\Roaming\Typora` on my machine. I would like to change this to be in my OneDrive or Dropbox so the configuration and themes i install are portable/replicated to my other machines. 

Can i change the path ? 

Thanks.

**Comment by abnerlee** [comment]
It is not supported to move the folder

**Comment by syedsameerali** [comment]
It would be pretty easy to do by using symbolic links instead of changing the actual location. There is a pretty handy gui utility available on sourceforge called 'Symlink Creator' ( authored by octanum)  which simplifies the task of creating symbolic links. 

https://sourceforge.net/projects/symlink-creator/

**Comment by abnerlee** [comment]
relates #2353
