### ISSUE TITLE
Can't select text at all

### ISSUE THREAD

**Issue by TheDeviantCrafter** [typora/typora-issues#2152]
I'm using Typora 0.9.64 (beta) on Windows 10. In every other text editor, I can select text by left clicking and dragging my mouse over that text. Selected text can be copied, pasted and overwritten by typing. This doesn't seem to work in Typora.

I've tried other methods to try to select text. In all cases, no text is selected. The only change is that the "I" shaped text cursor disappears, and I can no longer type until I click the window.

I've tried:

*  Control + A/D/L/E

* Pressing Control + Shift + Left/Right Arrow Key

* Pressing Shift + Left/Right Arrow Key

* Clicking "Select All" in the Edit dropdown menu

* Double clicking and tripple clicking text

**Comment by abnerlee** [comment]
In which case the text cannot be selected by mouse? Could you produce some steps/example to reproduce this, and what's the actual behavior after you mouse down and mouse move?

**Comment by TheDeviantCrafter** [comment]
I can't select text at all. In every case I've tried, the carat icon disappears and I have to click somewhere on the window to continue typing.

If this isn't a known problem, it's probably an issue with my installation. I'll try reinstalling some things and troubleshoot on my side.

**Comment by meet-v** [comment]
Hey! I am facing this issue too. It's very annoying.
Anything relating to text must support text selection keys. It's a very basic thing.

Just to elaborate on the issue, the text focus is lost as soon as we press SHIFT+UP/DOWN buttons. And the screen behaves like scroll lock is activated. It is not actually activated, but Typora behaves like that. With each up or down key, it scrolls up or down instead of continuing with the text selection.

Strangely, the SHIFT+LEFT/RIGHT works just fine. But that selects words. We need to select lines, which we cannot unless we use mouse.

This issue is not just with Typora. I have faced this in MarkText too. And the standard notepad (windows or linux) doesn't have this issue on the same computer with the same file. So it is something specific with Typora and MarkText.

Please fix this. It's very necessary and almost forcing us to stop using your software and move to alternatives. Even when the alternative is bad at several other things, we'd prefer that as text selection is a must for a text program.
