### ISSUE TITLE
Pasting a link inserts < and >

### ISSUE THREAD

**Issue by DustinWStout** [typora/typora-issues#2203]
I have only noticed this happening recently. Current version: Version 0.9.9.21.1

Steps to recreate: 

1. Copy a URL outside of Typora (example: `https://somedomain.com/post-name/`)
2. Paste that URL into Typora
3. Result = `<https://somedomain.com/post-name/>`

**Comment by DustinWStout** [comment]
Is anyone else seeing this?

**Comment by stennie** [comment]
I noticed the same problem in recent betas (currently on `0.9.9.23.4 (2293)` on macOS with the GitHub theme).

This is a definite annoyance for Markdown links: the angle brackets are hidden in Typora's WYSIWYG mode, but are included (and rendered) when pasting Markdown to some sites (for example, Stack Exchange comments).

I think this issue should be considered a bug since it isn't compatible with many flavours of Markdown and seems to be ignored in the rest: [Babelmark2 test](http://johnmacfarlane.net/babelmark2/?text=%5B%3Chttp%3A%2F%2Fsample.com%3E%5D(sample)). Alternatively there should be a preference to disable this behaviour.

**Comment by seamusdemora** [comment]
On my mac, I only see the added angle brackets when I c&p a URL from Chrome's "URL box". Firefox c&p does not cause this.

**Comment by abnerlee** [comment]
`<url>` is a part of Markdown syntax. https://daringfireball.net/projects/markdown/syntax#autolink
So it can be used as default behavior.

**Comment by abnerlee** [comment]
> This is a definite annoyance for Markdown links: the angle brackets are hidden in Typora's WYSIWYG mode, but are included (and rendered) when pasting Markdown to some sites (for example, Stack Exchange comments).

**Comment by abnerlee** [comment]
merge into #2415
