### ISSUE TITLE
Typora Windows 7: BOLD still does not work with NEWSPRINT-Theme

### ISSUE THREAD

**Issue by Angaria** [typora/typora-issues#2265]
Before I start: thank you for your great work! Typora has become my favorite writing tool!

This relates to #2046, which is already closed.
I can confirm that BOLD (**bold**) does work with the NEWSPRINT-Theme
in Windows 8.1 as well as in Windows 10.
But it still **does not work** with Windows 7 using this theme.
I have seen the new section in newsprint.css which goes like:

/* https://github.com/typora/typora-issues/issues/2046 */
.os-windows-7 strong,
.os-windows-7 strong  {
	font-weight: 760;
}

But it doesn't work for me.
I experimented with several values for the font-weight - but sadly to no avail.
When I export the document to HTML, the browser renders it just fine.
Any ideas?

**Comment by Angaria** [comment]
Formatting something italic does not work too, as well as combinations of italic and bold don't.
Striking something does work, on the other hand.

**Comment by abnerlee** [comment]
The font may not support bold or italic, please try with other themes. #2268

**Comment by ivofii** [comment]
I had a similar issue on my second Windows 7 computer. Italics also wouldn't display -- only in Newsprint theme. By comparing the two computers I discovered what turned out (for reasons I only partially understand) to be the crucial difference: PT Serif (all four styles) was installed on the second computer, not the first. (Newsprint.css refers first to this 'PT Serif", then to its woff equivalent, e.g. 'pt-serif-v9-latin-regular.woff'.)

So, in Control Panel > Fonts, I deleted PT Serif from the second computer. (When I first tried to do this, it complained the fonts were in use; after I quit Typora, I could delete the fonts. This confirmed that Typora was using those fonts.) Then, upon re-opening Typora, the Newsprint font suddenly appeared fine in all its styles (including italic, bold, bold italic). (Presumably it was now using the woff fonts.)

Why the deleted PT Serif fonts had not worked correctly in Typora when they appeared correctly in Control Panel > Fonts, I don't quite understand. Maybe the styles are named slightly differently? Anyway, I was relieved to find a workaround.

**Comment by Angaria** [comment]
**ACCEPTED SOLUTION** from **ivofii**
That was exactly what I needed! Deleted PT Serif from installed fonts and voila! :-)
And that after I have suffered for almost half a year.
I am truly grateful, ivofii.
Thank you very much, mate!
:+1: :1st_place_medal:

**Comment by nunhes** [comment]
Sorry!
Delete PT Serif don't work for me. And I can't see the bold words or paragraphs.
