### ISSUE TITLE
in DveTools there are some error messages

### ISSUE THREAD

**Issue by xfanplus** [typora/typora-issues#23]
Typora windows version 0.7.5

in DveTools there are some error messages:

1. file:///C:/Program%20Files%20(x86)/Typora/resources/app/app/window/frame.js Failed to load resource    Y.cors.a.crossDomain.send	@	app/window/frame.js:4
2. window.html:1 Uncaught SyntaxError: Unexpected end of input
3. missing C:\Program Files (x86)\Typora\resources\app\lib\html2canvas.js

I'm worrying about the correctness and stability of Typora damaged by the errors.

Coud you fix those errors?thanks!

the screenshot is like this:

![screenshot](http://ww1.sinaimg.cn/large/0060lm7Tgw1ezk67j2sxaj311i0k241h.jpg)

**Comment by abnerlee** [comment]
Errors of type `fails to load resource` can be ignored by users, it won't affect Typora's running. 
It is caused by Typora failed to load localized text resources, and currently no localization is available in Typora.   

But it seems I cannot change their level from errors to warnings (<http://stackoverflow.com/questions/7035466/check-if-file-exists-but-prevent-404-error-in-console-from-showing-up>).
