### ISSUE TITLE
The checkbox is very fuzzy in the printed pdf

### ISSUE THREAD

**Issue by jaychsu** [typora/typora-issues#2303]
OS: maxOS Mojave (10.14.3)
Detailed steps to reproduce: File > Export > PDF > Save (by using default preferences)

![image](https://user-images.githubusercontent.com/6890034/54675556-c44b5080-4b39-11e9-8f2c-4ca2856cf396.png)

**Comment by jaychsu** [comment]
My current workaround: export as HTML and print as PDF in Chrome. Then everything looks good...except a bit inconvenient.

**Comment by abnerlee** [comment]
Which Typora Theme? How about built-in themes?

**Comment by jaychsu** [comment]
@abnerlee it's build-in theme `github`

![image](https://user-images.githubusercontent.com/6890034/56139464-840daf80-5fcb-11e9-82b1-1a9b802a2d46.png)

**Comment by abnerlee** [comment]
I can confirm this, but we could only improve a little bit since Safari itself renders checkbox in a fuzzy way, you could try zoom or print https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_checkbox in Safari, needs Apple to improve this. or use themes that does not use the default checkbox style
