### ISSUE TITLE
Fended codeblocks doens't show the full code if the code is too long

### ISSUE THREAD

**Issue by luispuerto** [typora/typora-issues#2312]
As you can see in the gif below if the code is too long isn't show entirely in now. It was before. 
![2019-03-21 11 16 49](https://user-images.githubusercontent.com/22882880/54745935-2c964280-4bcb-11e9-9a60-212b98cc0525.gif)

**Comment by luispuerto** [comment]
Updating: the code is shown if you use your trackpad or mouse to move the `overflow` content, but if you type anything the content return fully to the left. 

Perhaps this is more an enhancement than a bug?

**Comment by vassudanagunta** [comment]
@luispuerto codeblocks are rendered in HTML as `pre` elements. Text within <pre>  do not wrap by default.  For example, the following Markdown:

    ```shell
    loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooog text
    ```

renders as follows here on GitHub:

```shell
loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooog text
```

In my browser, at least, it renders without wrapping, with horizontal scroll.

You can [change default `pre` behavior with CSS](https://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag). 

@abnerlee The above example *does* line wrap in Typora for me. Is that because I'm still on 0.9.9.22? (I don't upgrade right away because all my open Typora windows forget which desktop they are on when Typora restarts)

**Comment by luispuerto** [comment]
@vassudanagunta I think the issue isn't exactly that. They render fine, without wrapping and with horizontal scroll. 

Problem here is you can reach a point where if you are typing in the codeblock you don't see what are you typing because each time you type something the it scrolls to the left (to the beginning of the line). 

I guess it's because the viewer refreshes the view and reset the position to the left again.

**Comment by luispuerto** [comment]
If you want to reproduce just c&p your codeblock in typora and try to write to the end of the line. 

Something like this: 

![2019-03-21 16 18 10](https://user-images.githubusercontent.com/22882880/54762763-01284d80-4bf5-11e9-9268-48bf5cd24167.gif)

**Comment by vassudanagunta** [comment]
@luispuerto Understood. 

I can't replicate what you are experiencing because on my Typora it is wrapping (and it shouldn't!)

![Screen Shot 2019-03-21 at 12 26 26 PM](https://user-images.githubusercontent.com/2830093/54768054-c8787c00-4bd4-11e9-8fde-33cce473f014.png)

**Comment by abnerlee** [comment]
should be fixed in new release, please reopen if it still happen

**Comment by luispuerto** [comment]
confirm that it's fixed

PS/ Again if you close the author **cannot** reopen 😃
