### ISSUE TITLE
Could there be a Typora plugin on VSCode and Atom ?

### ISSUE THREAD

**Issue by Arilox** [typora/typora-issues#2323]
Hello everyone, I'm bored with bad documentation and bad code structuring / code UI.

And I enjoy markdown for that, it helps a lot structuring documentation, especially for coding.
I also love typora, a lot, for one especially reason, his UI. Editing markdown files like it was Word ones is clearly what people need.
So here's my question, could there be a plugin that could kind of integrate typora into those IDEs ?

I'm sure it could make markdown way more used and code way more documented by everyone.

**Comment by abnerlee** [comment]
VSCode does not support texts mixed with rich contents.

**Comment by JarnoRFB** [comment]
@edokode If you are looking for visual markdown editor that integrates with VSCode you can try out unotes https://marketplace.visualstudio.com/items?itemName=ryanmcalister.Unotes. It is open source and based on Toast UI. That was the only I found after some search.

**Comment by TomasHubelbauer** [comment]
FYI there is also https://marketplace.visualstudio.com/items?itemName=zaaack.markdown-editor and I believe what @abnerlee said no longer applies to VS Code API today as there is not a WebView API which can express rich text (but AFAIK the editing experience needs to be built on top of it manually, it doesn't come from VS Code because the WebView API is like an alternative opt-in editing experience provided by the extension and not VS Code core). I believe the extension I linked is using this relatively new VS Code API to achieve MarkDown WYSIWYG.
