### ISSUE TITLE
list indent and outdent behave inconsistently

### ISSUE THREAD

**Issue by vassudanagunta** [typora/typora-issues#2374]
List outdent `⌘[` works recursively, while list indent `⌘]` does not.

### Reproduce

1. Paste the list below in Typora
2. Place the cursor on "1", then use the list outdent command.
    "1" and its three children will be outdented one level each. (i.e. the "1" branch will be outdented recursively).
3. Leaving the cursor on "1", use the list indent command.
    Only "1" will be indented, none of its children.

```markdown
- a
- b
  - 1
    - x
    - y
    - z
  - 2
  - 3
- c
```

### Workaround 

One can select "1" and all its children to indent all of them together. 

So the issues isn't that users can't do what they need. It is that Typora behaves inconsistently and is not user-friendly in this area.

### Recommendation

**Quick fix**: when the cursor is on only one item, make `outdent` and `indent` behave the same: non-recursively.

**Better fix**: have separate commands for recursive and non-recursive promotion/demotion.

**Best fix**: have separate commands for recursive and non-recursive promotion/demotion, and have this same command work universally on any nested structure: nested lists, heading hierarchies, nested block quotes. See #2376.

**Comment by abnerlee** [comment]
We don't use "indent" to represent list indent, but using HTML `<ol><li>` to represent list items. For you example, if we outdent non-recursively, it become

```gfm
- a
- b
- 1
    - x
    - y
    - z
  - 2
  - 3
- c
```

which renders same as 

```gfm
- a
- b
- 1
  - x
  - y
  - z
  - 2
  - 3
- c
```

But later one is more "formatted", and in user's eye, from the rendered result, the list is still outdent recursively.

If user input a loose list like

```gfm
- b
  - 1

      - x
      - y
      - z

 - b
```

Then , when outdent `1` non-recursively, it become

```gfm
- b
- 1

      - x
      - y
      - z

 - b
```

And suddenly `- x` `- y` `- z` become code fences.

**Comment by skyblue002** [comment]
If an instance-specific `id` property is added to child lists and list items, they could be recursively indented/outdented using those tags as a key.

For example, if you have:
```
<ul id="abc">
   <li id="abc-1">first level</li>
      <li id="abc-1-1">second level</li>
      <li id="abc-1-2">second level</li>
   <li id="abc-2">first level</li>
```
By using the `id` property of the `ul` and `li`, the relationship between the items can be tracked. If the second level is outdented, the app could look for everything that begins: `abc-1` and outdent them.

The initial `abc` name of the outer `ul` could be generated somehow to make it unique, so that list indenting and outdenting doesn't conflict in a document.

Just an idea. I'm not sure if it's possible, but I've seen the code using the `DevTools` feature and if other tags can be added to elements, it's not such a stretch to think that these could be added, too. -- If it's possible, given the constraints of `html` and the underlying software/libraries used to create Typora.

**Comment by vassudanagunta** [comment]
@skyblue002 I think that's too complex. @abnerlee is correct above, so the current behavior makes most sense. My original thought didn't consider how outdenting non-recursively doesn't work. 

In other words, I think the inconsistency is warranted.  It is a natural consequence of the asymmetry of indenting and outdenting list items.

**Comment by skyblue002** [comment]
I’ve written programs, myself and it doesn’t seem too complex to me. But this isn’t my project. It’s up to the developers to choose what to do. I was just sharing an idea out of good will.

**Comment by vassudanagunta** [comment]
@skyblue002 I'm not talking about coding complexity. I'm talking about behavioral and semantic complexity. You're imputing knowledge of the writer's intent by "the relationship between the items can be tracked", knowledge you don't have.
