### ISSUE TITLE
MacOs app quits unexpectedly

### ISSUE THREAD

**Issue by mahdix** [typora/typora-issues#2446]
This happened twice in a space of a few minutes. I was checking a MD file when suddenly app quits.

This is the report that OS X wants to send to Apple:

```
rashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [42275]

Application Specific Information:
Crashing on exception: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

```
Model: MacBookPro11,5, BootROM 189.0.0.0.0, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: kHW_AMDRadeonR9M370XItem, AMD Radeon R9 M370X, spdisplays_pcie_device, 2 GB
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
Bluetooth: Version 6.0.11f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
```

**Comment by abnerlee** [comment]
What's your Typora version and locale, and could you share the crash log?

**Comment by mahdix** [comment]
Sorry, I did not save the crash log. I just downloaded the latest version from the website and this happened a few minutes after.

**Comment by beunguk** [comment]
Hi, I also having a similar problem using Typora on Mac. I've got this problem for some period. I expected to be resolved when each new version is released, but it didn't.

Problem occurs when I do followings.
1. Open Typora and change some contents of one file.
2. Save the file, then file bowser on the left pane shows two files with the same name. (Somewhat strange...)
3. Change to edit another file, or just click several other files to view the contents. (Just hanging around with the app.)
4. Suddenly Typora stopped and crashed.

I think the main cause of this problem is that Typora shows two file of the same name when I save the file. In my opinion, overriding the contents of the file which named in other languages cause this problem (I am using Korean. e.g "파일이름.md"). Maybe filename encoding is different between at the time of reading and saving?

I attach a crash log file. I hope this helps.
[typora-err.txt](https://github.com/typora/typora-issues/files/3145153/typora-err.txt)

Thank you in advance.

**Comment by abnerlee** [comment]
should be fixed in latest version
