### ISSUE TITLE
Wrapping selected text with characters other than braces

### ISSUE THREAD

**Issue by snungd** [typora/typora-issues#246]
Currently, when one selects text and presses [, ( or {, Typora will conveniently add matching braces at the beginning and the end of the selected text. I would also propose to extend this functionality to several markdown special characters: 

_ ~ * ` $

This will allow faster markdown editing without need to learn keybindings.

**Comment by AlexPasternak** [comment]
Agree 100%. I believe I already suggested the ` character earlier, that one would be very welcome.

**Comment by vassudanagunta** [comment]
To be consistent then doing the same with * should result in italicizing a word. I'm not sure that is a good idea, because normal expectation of typing a character without any meta keys (CMD, ALT or CTRL) is that it replaces the selected text.

It would be better if we simply had a simply keyboard shortcut. Unfortunately we can't use CMD-` for that because that normally belongs to switching windows within a app on OS X.

**Comment by snungd** [comment]
I agree @vassudanagunta that this should be consistent, that's why I proposed all the magic characters to have this behavior: _ ~ * ` $ . 

With regards to key combos, I would agree if Typora were ordinary editor. But being able to edit files without remembering yet another set of key bindings makes Typora outstanding among editors and I would really love it to stay that way :)

**Comment by vassudanagunta** [comment]
Thank you, @abnerlee, for making this a user setting in the new version!

**Comment by snungd** [comment]
Works like a charm! Thank you.
