### ISSUE TITLE
Navigation between footnotes and contents

### ISSUE THREAD

**Issue by AlienKevin** [typora/typora-issues#2479]
# Problem
Footnotes are separate from the main contents and there are no ways to navigate from either the content to the footnotes or the footnotes to the contents. Footnotes are not simply a place to store links, they serve as an *overview of the sources* used in the content that is very important for academic research papers using various style guides like MLA, APA, and Chicago. Footnotes can be *another way to navigate* within the document besides the current outline and provide a way to verify the reliability of the main content.
# Solution
* Add a go-to-content button besides the list of footnotes 
* Add a button to navigate to footnotes from the contents.

**Comment by neubland** [comment]
I too use Typora for academic work, but it is important to know the difference between footnotes and endnotes. What you are describing are either (1) endnotes, which are collected in the end, rather than on the bottom of every page, or (2) the list of literature, which is not actually numbered, but sorted alphabetically. Sometimes endnotes are used to reference literature, but not always and not exclusively. Wikipedia does this (footnotes and endnotes are interchangeable as it's a web site). Sometimes, footnotes and entnotes are used side-by-side in the same document.

The problem with footnotes and endnotes in Markdown (and therefore Typora) is that 1) it is not in the CommonMark reference but 2) it is supported by Pandoc, but there is no distinction. From what I saw, there are discussions about this though.

What could solve this? As most documents use either Footnotes or Endnotes, there could be a switch for which style of notes one wants to use. It depends on the Pandoc implementation though.

What I experiment with is adding a heading at the end, titled "Notes", where I collect the notes. Sadly, notes are not clickable, which makes finding the right passage harder.

**Comment by abnerlee** [comment]
You could write right footnotes under your references, no need to put all footnotes in the end of the documents.

Currently footnote is footnote, not academic reference, the later part can refer to #912

**Comment by abnerlee** [comment]
you can now jump between footnotes and contents
