### ISSUE TITLE
missing word in footnote export [bug]

### ISSUE THREAD

**Issue by xrwang** [typora/typora-issues#2488]
Hi! First, thanks for Typora, it's been amazing and has replaced any other word processing program I use, even for long chapters.

However, there's a strange bug with the footnote feature. When I use a named footnote, after exporting to OpenOffice, the named footnote word disappears.
ie.
`hi this is [^footnote]` becomes `hi this is` in Open Office. See screenshot below:
Typora:
<img width="365" alt="Screen Shot 2019-05-09 at 4 03 59 PM" src="https://user-images.githubusercontent.com/4019929/57492194-c8ac0400-7274-11e9-87f5-d2932161abf1.png">
<img width="325" alt="Screen Shot 2019-05-09 at 4 04 03 PM" src="https://user-images.githubusercontent.com/4019929/57492199-d06ba880-7274-11e9-9c37-f6085b51106f.png">

Open Office (the named footnote, the word `video` disappears):
<img width="615" alt="Screen Shot 2019-05-09 at 4 04 26 PM" src="https://user-images.githubusercontent.com/4019929/57492226-eaa58680-7274-11e9-9cb3-0b23ad9f38b1.png">

Thanks!!

**Comment by neubland** [comment]
As far as I understand, this is intentional. The name of the footnote has the function of an internal reference, so you don't have to manually number them. Furthermore in word processing footnotes are always numbered (mostly numerically, sometimes alphabetically), other behaviour would be strange.

I too think there is a problem though, as in this case WISIWYG is broken. A solution would be on-the-fly numbering. Problem is, this could make manually entering footnotes difficult.

**Comment by abnerlee** [comment]
This is current spec. 

duplicate with #1163
