### ISSUE TITLE
Error with typora 0.9.71 on Debian Stretch

### ISSUE THREAD

**Issue by meaz** [typora/typora-issues#2581]
I've just updated Typora on my Debian Stretch. But now, typora doesn't open. I get this message when trying to launch it fro command liene:
`[8898:0620/213856.172363:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/typora/chrome-sandbox is owned by root and has mode 4755.
`
I had indeed to chmod 4755 to get it work. But why now? It worked in the previous version without that...

**Comment by SHNacho** [comment]
Same error

**Comment by abnerlee** [comment]
https://github.com/electron/electron/issues/17972

**Comment by fredmurdoc** [comment]
Same error with the same OS

**Comment by MarcinKlejna** [comment]
Same error with the Debian Sid

**Comment by charisz** [comment]
Same error with Debian Buster

**Comment by Faulst** [comment]
As @abnerlee pointed out in [his answer](https://github.com/typora/typora-issues/issues/2581#issuecomment-504487657), this issue as already been answered in an other project.

In my case (Debian Buster), /usr/share/typora/chrome-sandbox was already owned by root but I had to do a `chmod 4755 /usr/share/typora/chrome-sandbox` in order to set the SUID. No problem after that.

**Comment by charisz** [comment]
@Faulst This solved the issue in my case as well. I don't fully understand, because I did `chmod 4755` before and didn't solve it, but now It works. Thanks.

**Comment by wencan** [comment]
I use debian 10.0
My solution：sudo chmod 4755 /usr/share/typora/chrome-sandbox

**Comment by touwoyimuli** [comment]
Same error with the same OS：
**OS:** 　Deepin 15.11 stretch
**Kernel:**　 x86_64 Linux 4.19.0-5-amd64

`./Typora 
[11547:0817/165238.810335:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /media/yuanyi/新加卷/SoftIns/Typora-linux-x64/chrome-sandbox is owned by root and has mode 4755.
追踪与中断点陷阱
`

**Comment by abnerlee** [comment]
I added "4755" in packaging script, did anyone still saw this in 0.9.75+ ?

**Comment by Faulst** [comment]
@abnerlee Works for me (debian 10, typora 0.9.76)
