### ISSUE TITLE
Inconsistent indentation

### ISSUE THREAD

**Issue by leowill01** [typora/typora-issues#2724]
There are a bunch of wild inconsistencies and bug in the way Typora handles indentations. Here are two I've documented so far.

### 1) Inverted indentation levels between normal view and source view

In source view, the indentations are correct: 

<img width="670" alt="Screen Shot 2019-08-10 at 2 13 18 PM" src="https://user-images.githubusercontent.com/43548130/62825945-8ea31480-bb79-11e9-8e0b-41893706fac4.png">

But the same lines in regular view are inverted:

<img width="400" alt="Screen Shot 2019-08-10 at 2 13 10 PM" src="https://user-images.githubusercontent.com/43548130/62825954-99f64000-bb79-11e9-816b-f702af2faf9b.png">

Why is this happening?

### 2) A list looks normal in regular view, but for some reason in source view, +1 level indents are styled as a code block, even though there is no code block:

<img width="773" alt="Screen Shot 2019-08-10 at 2 15 16 PM" src="https://user-images.githubusercontent.com/43548130/62825969-c27e3a00-bb79-11e9-9d29-c6656c86d153.png">

<img width="740" alt="Screen Shot 2019-08-10 at 2 15 09 PM" src="https://user-images.githubusercontent.com/43548130/62825970-c5792a80-bb79-11e9-895b-dc713cae7348.png">

In source view, the text turns into "code block" style text. This also happens if you indent a line with 4 spaces -- but then how are you supposed to indent a line and not make a code block if your indent is 4 spaces?

**Comment by abnerlee** [comment]
@coffee-and-genomics I cannot reproduce the first one, possible to send us the sample *.md file? (<hi@typora.io>)

The second one is #1638

**Comment by coffee-and-genomics** [comment]
Hi @abnerlee, I can't seem to reproduce the first issue straight up. It seems to only occur after a while of use and lots of changing indentation levels in lists.

However, I can reproduce another inconsistency between edit view and source view. I have made an example `*.md` file with some lists:

<img width="844" alt="edit-view" src="https://user-images.githubusercontent.com/43548130/63653840-cbedd180-c737-11e9-9581-191b63c084da.png">

This looks normal, but when I switch to the source view, the different indentation levels disappear:

<img width="823" alt="source-view" src="https://user-images.githubusercontent.com/43548130/63653843-d4460c80-c737-11e9-972a-e53f79599f38.png">

However, the indentations still seem to be there because they show up when I open the file in TextEdit:

<img width="576" alt="textedit-view" src="https://user-images.githubusercontent.com/43548130/63653845-d90ac080-c737-11e9-8faf-e572be0f40ae.png">

Here is the .md file for reference (had to change to `.txt` to upload to GitHub):
[example-error.txt](https://github.com/typora/typora-issues/files/3538444/example-error.txt)

Are there a bug fixes coming for how Typora handles indentations?

**Comment by abnerlee** [comment]
@coffee-and-genomics I cannot reproduce the one with "example-error.txt" either, what's your Typora version, and is there any steps to reproduce it?
