### ISSUE TITLE
Live Rendering triggers File Change 

### ISSUE THREAD

**Issue by TechPlasma** [typora/typora-issues#2834]
When you have the Live Rendering Option enabled and move your cursor through a heading it will trigger a change to your file despite not having changed the file. 
https://puu.sh/Ei36w/f54c4d23d8.mp4

**Comment by MetalGearBronya** [comment]
In addtion to this, using an IME, typing one char and use baskspace to delete it, Typora will display the file as changed by a dot beside the title, despite nothing has been entered. Suppose the reason is typora didn't recongnize the removal of the stub space placed before entering the actual chinese character. 

Changing the basis of diff comparision to by raw text would solve both problems.

**Comment by abnerlee** [comment]
I can confirm this, but there's an existing issue #2354 about this
