### ISSUE TITLE
One cell table

### ISSUE THREAD

**Issue by floriandierickx** [typora/typora-issues#2861]
It would be practical if there is the possibility to create a 1x1 table with one cell

**Comment by xDeuiii** [comment]
you can, type HTML table directly (as if you're typing a normal text in the editor, not in a code fence) instead of using built in "Insert Table".
![html table](https://user-images.githubusercontent.com/55028626/65673591-2098ab00-e05c-11e9-853a-9facd2429000.png)
![html table 1](https://user-images.githubusercontent.com/55028626/65673596-22626e80-e05c-11e9-9ffd-8517ec75bab6.png)

**Comment by abnerlee** [comment]
Markdown is plain text, one cell table "might" become
```
|cell|
```
If we support it, this cause unexpected behavior when user just want to input two "|", instead of making a table.

**Comment by floriandierickx** [comment]
Hey both, thank you for your reply.

Concise background: I wanted to have a feature to render a 'note'like box in both pdf and docx. I first used `tcolorbox` by including `header-includes: - \usepackage{tcolorbox}` and surrounding notes with `\begin{tcolorbox}` and `\end{tcolorbox}`, but this did obviously only render in pdf and not in docx. 

Therefore, a one-cell table seems like a nice workaround. In the meantime I found a way to render this in both final pdf and docx is using :

```markdown
| Note |
| ---- |
```
