### ISSUE TITLE
Outline not updated sometime

### ISSUE THREAD

**Issue by Yuhang-Follheart** [typora/typora-issues#3047]
When I change a title and make the cursor stay on the line of the title，The [toc] doesn't change immediately and the exported PDF will not change either, even though I've saved it with Ctrl + S。
![image](https://user-images.githubusercontent.com/44488283/69542037-8b675380-0fc5-11ea-9cef-e400b301a118.png)
In pdf, the problem looks like:
![image](https://user-images.githubusercontent.com/44488283/69542173-d6816680-0fc5-11ea-8f31-a22c5a1884d9.png)
Sometimes I just want to change the title and export it quickly，Instead of using unnecessary cursor movement to trigger [toc] Modification. 
Thank you very much if you can fix this bug

**Comment by kuvam** [comment]
Another instance of the outline not updating, on 0.9.95:

1. Change a paragraph to a heading.
   Result: The outline updates to reflect the new heading.
2. Undo.
   Result: The styling is correctly beheaded (sorry), but the outline does not update and still includes the ephemeral heading.

Possibly unrelated to @Yuhang-Follheart's issue since this looks like a bug in the undo functionality specifically but filing it here as the issue title seems appropriate.

**Comment by abnerlee** [comment]
When it is "## xxxx", it means the header is still under input, you can blur it somewhere else to get outline update.

when export, in my test, it will use the most recent headers.
