### ISSUE TITLE
[feature request] export DOCX/PDF with auto-numbered heading/toc/outliner

### ISSUE THREAD

**Issue by retsyo** [typora/typora-issues#3097]
I have read https://github.com/typora/typora-issues/issues/2986 where DutchPete points the solution to render auto-numbered heading/toc/outliner in typora. However when such a md document is exported( I prefer to DOCX or PDF)

| item                   | typora | html          | pdf  | docx   |
| ---------------------- | ------ | ------------- | ---- | ------ |
| auto-numbered heading  | yes    | yes           | yes  | no     |
| auto-numbered toc      | yes    | yes           | yes  | no[^not real] |
| auto-numbered outliner | yes    | no such thing | no   | no     |

[^not real]: in fact, if we click the item of toc in MSWord, no jump happens

**Comment by abnerlee** [comment]
For docx, now you can create a style reference (https://support.typora.io/Export/#style-reference) and add styles to number the headings https://support.microsoft.com/en-us/office/number-your-headings-ce24e028-4cb4-4d4a-bf25-fb2c61fc6585

For pdf export, I think the number will be displayed. Or you can use https://support.typora.io/Export/#pdf-latex--pandoc and some latex template to build one.

We could close temporary this since there are now workarounds, and no other users requests this.
