### ISSUE TITLE
Disable spell checking in labels

### ISSUE THREAD

**Issue by 01010101lzy** [typora/typora-issues#3134]
In Typora, when spell checking is enabled, labels like those in `[link_name][link_label]` and `[^footnote_label]` are also checked. But it is common in labels to use abbreviations to shorten words, as well as using non-standard letter cases, so they are easily spotted out by spell checkers. Is there a way to disable spell checking only in these labels?

Example:

![图片](https://user-images.githubusercontent.com/10259119/71713531-13ead680-2e45-11ea-9f7c-9b3e49955e7e.png)

**Comment by abnerlee** [comment]
We will disable spellcheck for the reference of links and footnote, since if it is same with the definition, it is correct, not matter misspelled or not.

The spellcheck for the definition of link and footnote will be kept since they will occur only once, and user can use words instead of abbreviations.
