### ISSUE TITLE
Cannot save file because has been changed by another app

### ISSUE THREAD

**Issue by yif-li** [typora/typora-issues#3137]
When saving the md file, Typora keeps showing this window:

<img width="521" alt="Image Copied on 2020-01-04 at 17 39 06 PM" src="https://user-images.githubusercontent.com/32441766/71772906-5da4f100-2f19-11ea-8c09-8a3cbb8154ff.png">

Could you tell me what's happened?

**Comment by abnerlee** [comment]
What's your Typora version, is there any 3rd app which may modify the file, such as another editor, or sync app like dropbox, etc

**Comment by yif-li** [comment]
> What's your Typora version

Version 0.9.9.31.3 (3987)

>  is there any 3rd app which may modify the file

I doubt there is another markdown editor because I've tried to quit all other apps in both my mac and my iPhone (which may alter it by cloud).

But I do use sync app, OneDrive, in my mac. 

I tried to reinstall typora but this bug remains.

---

btw, hoping that dev team can consider extending typora as bear-like note-taking app, with all current features, cross-platform support, and mobile counterpart. I believe we would like to pay for it!

**Comment by abnerlee** [comment]
see https://talk.macpowerusers.com/t/confusing-auto-save-behavior-in-pages-with-onedrive/10373

If you use TextEditor.app or Pages.app to edit file that in the same folder (sync by OneDrive), will they also show this popup?

**Comment by leafyoung88** [comment]
same popup dialog, very annoying.

**Comment by abnerlee** [comment]
Please confirm if it happens for TextEditor.app or Pages.app to edit file that in the same folder (sync by OneDrive or Dropbox)

https://forums.realmacsoftware.com/t/this-documents-file-has-been-changed-by-another-application-since-you-saved-it/21285
https://www.dropboxforum.com/t5/Dropbox-files-folders/quot-The-file-has-been-changed-by-another-application-quot/td-p/274210
https://discussions.apple.com/thread/6150018

**Comment by dwbruhn** [comment]
I've also been struggling with this behavior with OneDrive + Catalina (10.15.7) + Typora (0.9.9.35.2 (4715)).

Other editors like BBEdit and TextEdit cooperate just fine with OneDrive. I noticed that BBEdit doesn't automatically update the file on disk with unsaved changes, though TextEdit does. However, neither one has conflicts with OneDrive.

**Comment by fastfading** [comment]
the same error ,   vscode work fine. 
typora conflict with onedrive

**Comment by abnerlee** [comment]
duplicated with #2735

**Comment by bumpux** [comment]
> duplicated with #2735

Commented on #2735 - there's a problem saving from Typora to folders in some cloud services

**Comment by kangbosun67167** [comment]
The same error with typora 0.11.16 and onedrive (MacOS 12.0.1).

**Comment by jsgounot** [comment]
This issue is still here. It would be interesting as a temporary fix to allow an automatic save anyway for current file.

**Comment by mzilinski** [comment]
Same here. Please bugfix this.

**Comment by subrat-kar** [comment]
Same problem with owncloud / nextcloud. Where is the external application which is modifying the file ?

I use a licensed version of typora as an external editor for Joplin - this behaviour could be because Joplin is 'touching' (synchronising) the file while Typora has not yet done so. That is sufficient ground for a error message like this to be displayed.

**Comment by abnerlee** [comment]
would be fix in #5209
