### ISSUE TITLE
Feature Request: Option to set Source Code Mode as the default mode.

### ISSUE THREAD

**Issue by fresheneesz** [typora/typora-issues#3170]
I pretty much always want to use Source Code mode rather than the normal view mode. Please make an option for that : )

**Comment by abnerlee** [comment]
We does not have such plan

**Comment by fresheneesz** [comment]
@abnerlee What? Could you please explain further? Why not create this option?

**Comment by abnerlee** [comment]
It's not Typora designed to be. Source code mode is designed as a temp workaround in Typora, we will not put much effort on improving the source code mode, so we will not make it default.

**Comment by fresheneesz** [comment]
Is there some discussion I could read about why source code mode is a temporary workaround? Source code mode is much simpler to reason about, and I would certainly imagine much easier to code up the UI for. 

> we will not put much effort on improving the source code mode, so we will not make it default.

I'm not asking to make it "the default". I'm asking for an option that allows people to set it as the mode the application will open in for all documents.

**Comment by ETOgaosion** [comment]
Study Apple to teach people how to use markdown?

CS students like facing codes rather than WYSIWYG, for us source code is most explicit showing way.

Your source code mode is good, don't have to improve it, we just need you add a button, a query logic to make it display default, that's simple isn't it? I can do it in 10 minutes.
