### ISSUE TITLE
Typora using 97% of my macbook CPU

### ISSUE THREAD

**Issue by LeAcid** [typora/typora-issues#3218]
Typora Version:  0.9.9.31.6 (4047)
MacOS Version: Catalina 10.15

When performing operations near images or links the application will hang and then my CPU will climb until the whole computer starts to freezup. This then results in a loss of work done because even if I select save it fails to do so.

**Comment by aaarbk** [comment]
Same here
![image](https://user-images.githubusercontent.com/3729533/73605629-a64fd880-45b1-11ea-9801-4bc4c7e70f4d.png)

**Comment by rickmills** [comment]
Can confirm its an issue here as well. This might explain why after spending ages writing the app locks up when you hit save and loses whatever you've done since the last auto-save. Having to switch away until this gets resolved.

![Screenshot 2020-02-02 at 15 38 12](https://user-images.githubusercontent.com/103707/73610694-3a319c80-45d2-11ea-9f57-846d2171e287.png)

Running macOS Catalina 10.15.2, Macbook Pro 2016.

**Comment by musicbyjing** [comment]
Same here, Typora freezes often when adding or clicking on images.

**Comment by wkumari** [comment]
Yup - this is a major issue (for me at least). Typora is dying multiple times a day.
I'm running: Version 0.9.9.31.6 (4047) on Catalina (10.15.3 (19D76)) - I'm happy to collect logs, additional debugging, whatever else might be needed to fix this issue. Typora is one of my favorite app, and this failure is making me sad :-(

**Comment by abnerlee** [comment]
should be fixed in latest release
