### ISSUE TITLE
Typora input/text area

### ISSUE THREAD

**Issue by arcandio** [typora/typora-issues#3245]
I know that Typora itself is not and is not going to be open source, that's clear from the dozens of other issues already closed. I did however see that in 2015 @abnerlee mentioned an open source extract of the Typora editor for the purposes of markdown input/text area usage, in his [blog](https://abnerlee.github.io/typora/2015/03/11/why-typora/#adapt-markdown-everywhere).

1. Does the current stance on Typora's closed source apply to this too? I.e. is a Typora library text editor off the table now?
2. Would anyone be able to share some insights for how Typora works under the hood? I'm trying to develop an app, and I'm trying to understand how to build a live markdown view.

**Comment by arcandio** [comment]
Related to #3079, #16 and possibly others.

**Comment by abnerlee** [comment]
I was planning to provide a typora style input/textarea, but since code of Typora gets bigger and we are still handling many new requirements. I don't have the time to make a "lite" and "clean" version for textarea usage, I'm still focus on the desktop development.

But many products, like "Slack", is already developing and applied a similar approach in their "textarea", and there are open source solutions like https://canner.github.io/canner-slate-editor/?selectedKind=canner-slate-editor&selectedStory=Simple%20demo&full=0&addons=1&stories=1&panelRight=0

---

> Would anyone be able to share some insights for how Typora works under the hood? I'm trying to develop an app, and I'm trying to understand how to build a live markdown view.

Typora is similar with code editor, while the later only change style/color of special syntax, while typora also changes its visibility. The flow is mainly: input -> parse -> render. 

Hope this can help you

**Comment by arcandio** [comment]
Thanks very much @abnerlee! I really appreciate the direction. That's a good trick with keeping the Markdown intact and just hiding it, but I'll also look into these other options as well.
