### ISSUE TITLE
mermaid diagrams - words get cut off

### ISSUE THREAD

**Issue by C3LY** [typora/typora-issues#3291]
using MacOS
![image](https://user-images.githubusercontent.com/43711652/75165105-c63e6c00-5719-11ea-9da5-7678b1e2fa9a.png)

**Comment by abnerlee** [comment]
Typora version?

**Comment by jklm264** [comment]
I am currently having the same problem on Mac only; version 0.9.34.2. Was a fix ever implemented? This issue affects all types of graphs LR, TD, etc.

**Comment by TUNGHUAYU** [comment]
Recently, I would like to export Markdown to HTML by Typora, which includes mermaid syntax.
It can display a pretty flowchart on Typora GUI. ( see Figure 1 )
However, there is something wrong with exporting to HTML. ( see Figure 2 )

Please let me know if there is any way to solve it.

Thank you very much

---

Table 1.environment of my PC
| No. | attribution | content |
| --- | --- | --- |
| 1 | Operation System | Ubuntu 20.04.2 LTS |
| 2 | Typora | version 0.10.11 (beta) |


![Screenshot from 2021-06-29 19-42-26](https://user-images.githubusercontent.com/59678141/123791539-264ab100-d912-11eb-844f-5550d4decc7e.png)
Figure 1. The flowchart on Typora by mermaid syntax.

![Screenshot from 2021-06-29 19-44-24](https://user-images.githubusercontent.com/59678141/123792518-47f86800-d913-11eb-97f9-69f849afd1a9.png)
Figure 2. The flowchart on HTML is exported by Typora with mermaid syntax. (the world was cut off for some reason)

**Comment by abnerlee** [comment]
#4499

**Comment by JasperCiti** [comment]
This bug is also annoying me very much. However, I think I found a work-around. If you choose a theme with a very large font size or override the custom font size to very large text, then the mermaid diagrams seems to provide enough space or the text even if the font size does not affect the mermaid diagrams.

Another work-around is to keep switching between themes until the text "fits" in the diagrams. However with this approach you need a bit of luck because you have to switch it in the correct order for this work. Don't know why it is like that.

Another work-around is to close Typora and reopen it again. Sometimes it renders correctly the second time but not always.

**Comment by tatitati** [comment]
I have the same problem. I have the last version: Version 1.1.5 (6235). MAC Monterey

**Comment by wiesener** [comment]
Same bug here.

**Comment by PenceGL** [comment]
I just encountered this on MacOS 12.3.1, Typora version 1.2.4, and found this issue after searching. Why is this marked as closed? Changing themes did not fix or affect it in any way. Here's the example code from the main website:

<img width="888" alt="Screen Shot 2022-06-03 at 11 21 06 AM" src="https://user-images.githubusercontent.com/8877847/171905819-406cf5a9-61d0-4bf4-9628-60510c36dd12.png">

**Comment by WuTianming** [comment]
as a workaround, check if you have a custom window zoom ratio set. if so, try turning the zoom ratio back to 100%.

**Comment by MarqueIV** [comment]
> as a workaround, check if you have a custom window zoom ratio set. if so, try turning the zoom ratio back to 100%.

That fixed it for me!  THANK GOD!!!!!!!!!  Been pissing me off forever!!

Keyboard Shortcut: <kbd>Command</kbd>-<kbd>Shift</kbd>-<kbd>0</kbd> _(Zooms to 'Actual Size')_
