### ISSUE TITLE
Links to file system folders should not open in the browser

### ISSUE THREAD

**Issue by jackwlee01** [typora/typora-issues#335]
If I make a link to a folder on my file system, it should open that folder in Finder instead of opening my browser.

**Comment by jparris** [comment]
+1 Also it would be really useful to open other local md files in another typora window.

**Comment by pjeby** [comment]
Here's a quick hack that worked for me with Typora 0.9.20 on Windows.  You will need to find the `Typora/resources/app/app/window/frame.js` file and change its permissions so that it's editable.  Then search for:
```js
a="http://"+a}
```
and replace it with:
```js
reqnode("electron").remote.shell.openItem(a); return}
```
Haven't tried this on OS X yet, but the same principle should apply since `shell.openItem()` is a cross-platform Electron API.

**Comment by abnerlee** [comment]
#309
