### ISSUE TITLE
Auto Save on macOS

### ISSUE THREAD

**Issue by seamusdemora** [typora/typora-issues#3360]
Re `Preferences, General, Save & Recover` in macOS:

I feel slaving this option to the selection in macOS' `System Preference, General, Ask to keep changes when closing documents` is **wrong**. I would prefer that my Typora Preferences be **independent** of settings in macOS. [REFERENCE](https://support.typora.io/Auto-Save/)

Why? Because I use Typora to create & edit all of my GitHub content. Sometimes I make "trial changes", not necessarily intending to keep them. Sometimes my workflow is interrupted, and some dodgy experimental crap gets saved in my repo. Not good. Typora's mission is **different** than all other editors on my system, and I need to be allowed to make a *conscious* decision wrt saving a file to the repo. 

Please don't put this option in the Preferences, and then disable it based on a generic system setting.

**Comment by abnerlee** [comment]
>  Sometimes I make "trial changes", not necessarily intending to keep them.
This is #710 and #2354

Typora on macOS is a macOS app, of course we would respect your system preferences.

**Comment by seamusdemora** [comment]
That's a wee bit disingenuous IMHO... I'm happy to have a "default" option, but I want to be able to make exceptions on a *case-by-case* basis. 

And the work-around to this could be to offer an option in `Preferences`, `General`, `Save & Recover` that allowed Typora users to choose whether or not to follow the "Default" options in macOS. Everybody's happy. 

Just because Apple does something does not mean that all users like it, and you certainly don't *have to* do what Apple does.

**Comment by neldeles** [comment]
+1 for this. Mark Text has this feature, and I think how they implemented it is pretty well done. They even offer the option to configure how long the delay is before auto-save kicks in.

**Comment by leowill01** [comment]
I unfortunately had to leave Typora because of this because I frequently switch between multiple editors for the same files at the same time. For instance, I will have a large todo list open that i will edit both on my mac and my iPhone/ipad and i will also have an R Markdown doc open in both typora and RStudio. the only way this system works is if each app saves the doc either after a set period of time (eg 1s) or when the focus leaves the app, otherwise different edits may run into file conflicts. I've had to move to Zettlr (which has autosave options) on my mac for technical docs and Bear's new Panda beta on all my devices (which isn't perfect but it does have some type of iCloud-based autosave even if the file doesn't appear to be saved, but it is far from perfect) for my todo list docs. the main reason i need this is because of how often i switch between devices and docs. having to remember to manually save everything multiple times per minute wore me out long ago.

**Comment by seamusdemora** [comment]
I had forgotten about this; forgotten that my request was disregarded. Now I'm disappointed again.

**Comment by vassudanagunta** [comment]
@leowill01 and @seamusdemora looks like its back on the table: #5209.

**Comment by seamusdemora** [comment]
> @leowill01 and @seamusdemora looks like its back on the table: #5209.

Smartest thing you could do! FWIW, think on this for a moment: The intersection (in a Venn diagram sense) of people who use `git` - particularly GitHub & GitLab  AND people who use markdown. 

"Huh!... I don't remember that commit! How tf did that happen?" 

How do I deal with it? I have to keep an extra folder for the documents I am working on. AutoSave without choice is just awful. And if Apple is your excuse... well, let's not go there. You really DO NOT have to copy Apple - in fact, that will lose customers. I wish now I'd not forgotten this thread before I bought my license. I'm not bitter - I love Typora - but we all have to make choices that best suit us.

**Comment by kbd** [comment]
As @leowill01 [commented](https://github.com/typora/typora-issues/issues/3360#issuecomment-1116868946):

> I've had to move to Zettlr (which has autosave options) on my mac for technical docs

I actually just switched *from* Zettlr and became a paid Typora user, but was surprised to notice the following behavior:

Test was: Typora open on Mac, Textastic open on iPad, the file open is synced in an icloud directory. It's *also* committed to git via `watchexec` which is relevant for this test mainly because I can see when it's synced *instantly* to git when the file is saved. So, I know exactly when the file is being saved vs when it's not.

Behavior observed:
- Typora autosaves instantly when losing focus / switching apps (~5s until appearance in Textastic on other device via icloud)
- Typora autosaves as expected on sleep (shutting the lid, hitting power button) (~6-7s until appearance in Textastic)
- Typora **will not autosave** (longer than 1m at least) so long as focus stays in Typora and Mac is awake. Even "overlay" apps like Alfred or Spotlight or Hammerspoon's chooser don't cause loss-of-focus save.
- Typora **will not autosave** even if you switch to another document within Typora! 

I much prefer a behavior like Zettlr's where it'll autosave after ~5s of inactivity. It should also definitely have the option to autosave when switching focus of documents. Imagine working on documentation for a while, even among multiple documents, without leaving Typora. It could be a while before data is written to disk. This is unsettling behavior from an app I trust critical data to, and I'm going to wind up adjusting my behavior to obsessively close Typora windows whenever they're open so I trust things are saved.

**Comment by seamusdemora** [comment]
@kbd 
> I much prefer a behavior like Zettlr's where it'll autosave after ~5s of inactivity. It should also definitely have the option to autosave when switching focus of documents. Imagine working on documentation for a while, even among multiple documents, without leaving Typora. It could be a while before data is written to disk. This is unsettling behavior from an app I trust critical data to, and I'm going to wind up adjusting my behavior to obsessively close Typora windows whenever they're open so I trust things are saved.

I guess this comes down to *use cases* and *workflow*. For me, I have to leave Typora for (sometimes) extended periods of time to *research something* - i.e. to verify something I've written, to look up a URL reference, or just to pause & reflect before saving/committing. I need to be able to **control the save**... I do not want some monkey-shit *"Apple feature"* making that decision for me...   just sayin'  :)
