### ISSUE TITLE
macOS: text selection

### ISSUE THREAD

**Issue by mpneuried** [typora/typora-issues#337]
It's quite difficult to select a text because of the automatic scrolling.
If i try to select a text at the bottom of the current screen the page scrolls/jumps to that position.
Especially if i want to mark a single word with a double-click another word could be selected, because the selection will be made during the auto scroll.

**Comment by abnerlee** [comment]
It's a bug if typora scroll like this.

Have you confirm that you are at the latest version and **not** enabled the "typewriter mode"?

If it still happens, could you give me detailed steps to reproduce this (or a screencast if you find it hard to describe)? because it works fine on my Macbook. Thanks~~

**Comment by mpneuried** [comment]
i had the typewriter mode active ...
After deactivating it, they strange behavior is gone.
**Thanks!**
