### ISSUE TITLE
latest mermaid 8.4.8 support gnatt chart with multiple dependencies

### ISSUE THREAD

**Issue by iamhuzhe-microleads** [typora/typora-issues#3403]
task1 :after t3 b3, 10d

(t3, b3 seperated with space, multiple dependencies)

**Comment by froberts0n** [comment]
Also, I had errors in my `classDiagram` because the version included in Typora doesn't support underscores in class names. I think this could be fixed by updating the library since it works fine in VisualStudioCode and on the [live Mermaid](https://mermaid-js.github.io/mermaid-live-editor/) web page. Might solve this issue altogether,

**Comment by abnerlee** [comment]
#1661
