### ISSUE TITLE
Dynamic TOC in Sidebar - Typora and Strapdown not working together

### ISSUE THREAD

**Issue by flangel** [typora/typora-issues#348]
Hi, 

the typora outline panel feature is awesome and it would be great to have the same functionality in the exported html. 

In the meantime, i am trying to use Strapdown  http://ndossougbe.github.io/strapdown/ to achieve the same, but Typora/Strapdown combination doesnt work. 

1. I create basic MD document for testing (strapdownTest.md), adding the necessary html.
2. I exported to HTML including style

The TOC generated doesn't support layers. It stops working after hierachy Heading 1

I am attaching .md and .html as zip.
Anyone, any idea why ? I wasn't able to identify the culprit!

[strapTypora.zip](https://github.com/typora/typora-issues/files/519689/strapTypora.zip)

**Comment by flangel** [comment]
@abnerlee Ndossougbe rightly pointed out that his tool works on MD, not on the html Typora generates. So rather than being a bug, this should be an enhancement request to "add ability to create TOC in sidebar when exporting to HTML". Would you agree?

**Comment by abnerlee** [comment]
I would say this it not in high priority, since Typora should only export the writing content, like most markdown parsers, and for control UIs like sidebar, we do not plan to include it in exported HTML.

I think it is better to leave this to static site generator to for such structured webpage.

Also, 3rd part libraries like https://gsnedders.html5.org/outliner/ or tools like https://chrome.google.com/webstore/detail/html5-outliner/afoibpobokebhgfnknfndkgemglggomo can do the trick.

**Comment by flangel** [comment]
abnerlee, 

thanks for the link, I spent some hours researching for a good solution with a good look and feel that is similiar to Typora's outline. Unfortunately, to no avail. Everything i found were crud hacks. I tried
 
1.  Static page generator's such as Jekyll
2. Built in Javascript (no way to insert JS in MD language at the moment)

However, I found https://www.staticgen.com/ and perhaps that provides me with a good tool to achieve what I  want. I keep you update. Thanks
