### ISSUE TITLE
Reloading Themes when they are edited

### ISSUE THREAD

**Issue by NeoGalaxy** [typora/typora-issues#3497]
Hello, I am trying themes and editing them to try getting what I want. Although, when I edit a Theme, I have to exit and re-open Typora in order to get my themes reloaded. 

Is there a way to reload the themes without restarting Typora ? If not, could you add a way to reload themes ? (If possible it would be great to reload them automatically, otherwise could you add an option "Reload themes" in the "theme" menu ?)

**Comment by abnerlee** [comment]
I think you just need to 
1. switch to other theme
2. new window (maybe not required)
3. switch theme back

**Comment by AugustM** [comment]
Switching to another theme and back again does not work.
Opening a new window with a new file using the same theme shows the changes to the theme for the new file, but not in the original file.
You don't have to restart Typora, but you do have to close and reopen the file to see changes to the CSS theme in that file's display.

What I have found useful to see the effect of changes that I am making in <theme>.user.css files is to keep the CSS editor open along with the folder where my Typora test.md file is. 
With the Typora file open, I make changes to the <theme>.user.css file and save the file. 
Then in the Typora File menu, I open a new window and drag the test.md file from its folder onto the new, empty Typora window that has just been opened using the updated theme CSS.
The test.md file will be displayed using the new CSS while the previous Typora window shows the "before" version. 
I then close either of the Typora windows, edit the CSS, save the *.css file, open a new Typora window from the existing window, and drag the test.md file onto the new window again.

It's not great, it could be smoother, but it saves having to close and reopen Typora and it has the benefit of being able to see before and after versions of how the file displays.

**Comment by anmeissner** [comment]
I would like to have an option that activates a theme reload on theme file change. So when I edit a theme file and save it, then Typora will recognise this and automatically reload the theme. That would be such a relief when youre creating a new theme.

**Comment by steveruizok** [comment]
It would be great to be able to Cmd + R or something to reload the current window with new themes.

**Comment by frankulyn** [comment]
How is this closed as completed?

**Comment by mikelei8291** [comment]
Switching themes back and forth is a way to reload the theme, but you will need to open the dev tools and enable "Disable cache" at the top of the Network panel, see #5415.

However, with a bit of reverse engineering, I did found a way to make this easier. It seems you can just execute the following code in the Console tab of the dev tools while enabling "Disable cache" to reload the current theme:

```js
File.setTheme(File.option.curTheme);
```

To make it even easier, you can bind the action to a specific key combination with the standard `document.addEventListener` API:

```js
document.addEventListener("keydown", (e) => {
    if (e.ctrlKey && e.key === "r") {
        File.setTheme(File.option.curTheme);
    }
});
```

Then you can just press <kbd>Ctrl</kbd>+<kbd>r</kbd> to reload the theme, as one would normally do to reload a web page. Note that you will have to keep the dev tools open for any of this to work, otherwise the CSS file will be read from cache, as the "Disable cache" option only works when the dev tools is open.

I do hope that @abnerlee could just add this as a menu option. Then theme developers could re-bind this to any key binding they prefer by simply editing the configuration file. It's quite painful to develop a theme for Typora without this feature now due to the fact that the `typora-theme-toolkit` is [deprecated 4 years ago](https://github.com/typora/typora-theme-toolkit/commit/548bdf6c7d9c204dd2a80e410201b44fd55852c6) and the recommended way is to test and develop in Typora directly.
