### ISSUE TITLE
Include Imgur script for image uploading

### ISSUE THREAD

**Issue by arjvik** [typora/typora-issues#3498]
Instead of relying on PicGo, why not include a script which uses Imgur to host images? This script can be implemented in pure bash with no dependencies other than curl and jq.

I have made such a script:
https://github.com/arjvik/dots/blob/master/i3/bin/image-uploader

This could likely even be built into Typora directly.

**Comment by abnerlee** [comment]
We allow users to use their own scripts, and after support imgur, we may need to support much more services as well..

**Comment by CryptoSharon** [comment]
@arjvik While it's not supported by default, I added it very simply with your code. I saved it as a .sh file, then I added it to the "Custom Command" section as `bash C:\Users\Sharon\typora\uploader\uploader.sh`. And it works. Easy setup. (I do have Linux commands enabled on Windows, with bash, and I had to install `jq` with Chocolatey before I was able to run it)

**Comment by GamerGirlandCo** [comment]
@CryptoSharon could you please elaborate on what exactly you did to get it to work??

**Comment by CryptoSharon** [comment]
@GamerGirlandCo Sorry, I read your question today. I wasn't notified of your reply. I just installed Typora on a new system so I'm setting things up again.

This time, the Linux installation is different (it was a console thing before and now it's WSL). I tried what I suggested before and got the error you got. I debugged it and got a few more errors, so I solved them all and wrote a new bash file that actually works. It replaces Windows paths with Linux paths. Additionally, the command that is inserted into Typora had to change as well to comply with WSL path differences. I'll show you.

This is the custom command:
`bash /mnt/c/Users/sn/AppData/Roaming/Typora/uploader/uploader.sh`

This is the code I used:

```sh
#!/bin/bash

while [[ $# -gt 0 ]]; do
	rawfilepath="$1"
	slashedfilepath="${rawfilepath//\\/\/}"
	filepath="${slashedfilepath/C:/\/mnt\/c}"
	echo "$filepath"
	filename="${filepath##*/}"
	type="image/${filepath##*.}"

	curl -ss -X POST https://imgur.com/upload -H "Referer: https://imgur.com/upload" \
			 -F "Filedata=@\"$filepath\";filename=$filename;type=$type" \
		| jq -r '.data.hashes | map("https://imgur.com/"+.+".png") | .[]'

	[[ $filepath == $HOME/.config/Typora/typora-user-images* ]] && rm $filepath
	shift
done
```

Beware that I replaced C: with /mnt/c. If the drive where you have Typora is different (E:, D:, etc.), it won't work. You have to be aware of the letter. This is all because I'm a bash newbie. If you or someone else is better, please adapt it \*.*

**Comment by arjvik** [comment]
@GamerGirlandCo are you on WSL? Or just plain Linux?
