### ISSUE TITLE
Include Typora-generated TOC and anchors upon "Copy As HTML Code"

### ISSUE THREAD

**Issue by mleiphamellis** [typora/typora-issues#350]
The Table of Contents that Typora previews upon use of the [toc] element is fully usable within the document, and I would like to request that a simplified version be included in the HTML code when copied.

My employer works with a hosted CMS platform that doesn't support Markdown, so I use intermediate software to render the HTML, pasting the output into the HTML editor of the platform. Typora has been an excellent writing tool and I love the Copy As HTML Code shortcut, however it omits the generated TOC and anchors in the headings. A single command to copy everything in the preview to the clipboard would be a beautiful enhancement and save me several steps!

My current workaround:
- Export the document to HTML (choosing "HTML (Without Styles)" also does not include the TOC)
- Discard all but the body of the exported document
- Add a bit of structure to the TOC (without the CSS, the layout of that area is non-existent but the links and anchors are all intact)
- Paste into the HTML editor as described above. 

Even this tedious workaround is a better solution for me than manually creating anchors and links from the WYSIWYG editor of the platform, but I hope to find that others would benefit from the improvement I have suggested!

**Comment by FindHao** [comment]
Same problem too.
The 'copy as html code' can't generate the table of contents.

**Comment by timpulver** [comment]
I would also very much like to statically generate the TOC, so that my markdown file contains actual links:

```
**TOC:**  
- [Chapter 1](#Chapter 1)
    - [Chapter 1.1](#Chapter 1.1)
        - [Chapter 1.1.1](#Chapter 1.1.1)
- [Chapter 2](#Chapter 2)
```

The ideal workflow for me would be to navigate to a certain position in my document, press a shortcut, e.g. `cmd + shift + t`, Typora will parse my document and insert the static TOC.
If I wanted to update it I could then just select the generated TOC and press the shortcut again.

I basically want the functionality of [github-markdown-toc](https://github.com/ekalinin/github-markdown-toc)

**Comment by abnerlee** [comment]
merge this into https://github.com/typora/typora-issues/issues/535

**Comment by SebyKiu** [comment]
Is there a workaround for copying markdown toc ? still just pastes [toc]
