### ISSUE TITLE
Feature Request - Saving untitled draft without asking when closing the app

### ISSUE THREAD

**Issue by AcrylicShrimp** [typora/typora-issues#3565]
Hi all,

I want typora to manage untitled drafts automatically. In Visual Studio Code or Notepad++, they save drafts without asking when closing. They re-open them whenever app restarts.

I know that typora has a feature `Recover Unsaved Drafts`, but it's not much useful. Can we have this feature?

**Comment by abnerlee** [comment]
Currently Typora is file-base not project-based, we don't follow IDEs.

Maybe #935 is a better solution to handle untitled drafts

**Comment by AcrylicShrimp** [comment]
Thanks for your feedback, @abnerlee. But I don't understand about relations between 'Typora is not project-based', and supporting automatic management of unsaved drafts. I believe they are irrelevant at all. For an example, Notepad++ has this feature and it doesn't follow IDE while it's file-based. Can you explain it more? Maybe you just misunderstood my request.

**Comment by abnerlee** [comment]
Typora is a wordpad or MS Paint but writes & read in markdown format, currently logic is to close all windows when quit.

Typora lacks feature like multi-tab, etc to recover closed windows. I think it is very uncommon to pop up many windows when an app launched on Windows.

Also, it feels a bit dangerous since Typora is in beta, better to still let users to save on close for a while.
