### ISSUE TITLE
Search(Ctrl + F) Not Working

### ISSUE THREAD

**Issue by akhil189** [typora/typora-issues#3618]
Search(Ctrl + F) is not working as expected. When searched for a word, the words are getting highlighted(in orange and black) in the document but pressing enter button or up/down buttons doesn't take the screen or scroll to the place where this word is located in the document.
**My doc size: 105KB
words: 4867
Typora version: 0.9.89
OS: Windows 10 x64**

**Comment by luckytoilet** [comment]
I am experiencing this too. I don't know how to reliably reproduce the bug, but it seems to occur after having a document open for a long time. Closing and re-opening Typora fixes it. I have not had this problem on earlier versions of Typora, it only started to occur with 0.9.89.

**Comment by abnerlee** [comment]
Are the matched text, which you'll scroll to, a part of content in code blocks?

**Comment by luckytoilet** [comment]
No, there are no code blocks in the document.

**Comment by luckytoilet** [comment]
If it helps, here's a screencast of the bug: https://www.youtube.com/watch?v=0PUtyYXbIBM

**Comment by khaggerty-adev** [comment]
I am also having this issue (and feel like I have had it for quite some time on Windows).

- Typora = v0.9.89(beta)
- OS = Windows 10 Pro v10.0.18363 Build 18363
- Device = Dell Latitude E5540
- How To Reproduce = Open "Find" either through keyboard shortcut (Ctrl-F) or menu and attempt to search for text string within document.
- Behavior = Matching strings are highlighted, but jumping to a matching string "below the fold" does not automatically scroll the Typora window to bring it into view. This also applies if the first matching string is outside the current viewport.
- Expected Behavior = Matching search results should scroll into view.

This issue does not occur on my version of macOS on a different device. — macOS Catalina v10.15.5 on a MacBook Air (Retina, 13-inch, 2020) using Typora v0.9.9.33.2 (4442).

**Comment by Wizna** [comment]
I updated to the newest Typora 0.9.90 (beta), but the problem persist.
Os: windows 10 pro version 1903 build 18362.900

**Comment by bencamber** [comment]
Still having this garbage problem. Anyone figure out a fix?

**Comment by informatiquefen** [comment]
Me too, exact same problem. I did a search and found this thread and was hoping to see a solution. I use a lot of this CTRL-F function, but don't want to switch in Source Code mode.

**Comment by kkuhle** [comment]
+1 on 0.9.98 (beta)

Switching to "Source Code Mode" -> `CTRL`+`F` works, but is a pain.

**Comment by abnerlee** [comment]
To be clear about this issue: the search will highlight matched ones in document, but won't scroll, right?

**Comment by luckytoilet** [comment]
Yup, that is correct.

**Comment by abnerlee** [comment]
should be fixed

**Comment by kkuhle** [comment]
Seems to be good after updating today.  Thanks, @abnerlee!!!

**Comment by kkuhle** [comment]
This issue seems to be back in 0.10.11.  I think it's been back for a few versions (assuming it was fixed).  I'm trying to test the version it was fixed.  What version was the fix originally implemented?

**Comment by abnerlee** [comment]
@kkuhle which OS / theme? Possible to provide a screencast?
