### ISSUE TITLE
[Question] How do you actually get these symbols in Typora code mode?

### ISSUE THREAD

**Issue by SimZhou** [typora/typora-issues#3653]
This might be only a trivial question to ask but I am still curious to know. 

When typing 4 spaces + 1 return in Typora, it is shown as the following in code mode: 

![image](https://user-images.githubusercontent.com/11748629/86221311-55232f80-bbb7-11ea-9f77-4b59538a5a82.png)

I am just wondering if these symbols are actual type-able characters, or they are just symbols marked by Typora indicating a new paragraph here?

**Comment by abnerlee** [comment]
In markdown, the whitespace should be ignored in some cases, like line start, etc.

So, when you input whitespace in source code mode, there are whitespace in source code mode, but when you input whitespace in hybrid mode, nothing will happen (but in source code mode there are whitespaces). But since you input whitespace in a WYSIWYG-like mode, users may report bugs if nothing happens. So an "\u200b" will be inserted to preserve those whitespace.
