### ISSUE TITLE
Image in html twice the size as normal

### ISSUE THREAD

**Issue by flangel** [typora/typora-issues#366]
Version 0.9.9.8.2 (0.9.9.8.2)

When I export a document to HTML with styles, images are twice the size as in Typora editor. When I open the image in separate tab in browser, it shows in normal size. Does the CSS cause the change in size? 

Attaching zip file with md file, image and html. See results screenshot here

<img width="1347" alt="result" src="https://cloud.githubusercontent.com/assets/2772980/19549728/27feb522-96a6-11e6-9398-d6886bb02679.png">
[imagetest.zip](https://github.com/typora/typora-issues/files/541012/imagetest.zip)

**Comment by Blaxus** [comment]
This also happens when exporting in PDF, so I think it's [pandoc](http://pandoc.org), which is used for exporting PDF's and possibly HTML when available. This must be some kind of configuration. When you inspect the image, it shows that `.md-image:only-child` has `width:100%`, and if you disable that it fixes the image resize. For me the image is also not aligned.

I don't know how to fix this. It works in Typora but not in exported files. So my guess is that they have to modify the export configuration somehow to avoid that problem. I've got no experience with pandoc, so it's up to them to either fix it, or if it's something we have to configure on our end then a small guide would be nice.

![](http://puu.sh/rUg64/0475ba1144.jpg)
![](http://puu.sh/rUg7a/db937aa907.jpg)

**Comment by abnerlee** [comment]
Should be fixed in new version
