### ISSUE TITLE
 deprecated method warning

### ISSUE THREAD

**Issue by HarveyHub** [typora/typora-issues#3817]
When I open a .md file with typora in windows10 powershell terminus, some warning appeared:
- [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

- Electron: Loading non-context-aware native module in renderer: typora\0.9.95\resources\app\node_modules\spellchecker\build\Release\spellchecker.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

system: windows10
version: 0.9.95

**Comment by this-josh** [comment]
I to am experiencing this issue on Typora version 0.9.98, the only difference being this has been added to the end of the message.

(node:24620) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead

**Comment by syco** [comment]
Same problem in linux now.
Almost a year later, better bump this to the top...

**Comment by abnerlee** [comment]
would not show the warning now
