### ISSUE TITLE
the cursor disappear at the end of some formated lines

### ISSUE THREAD

**Issue by Hedilict** [typora/typora-issues#386]

**Comment by Hedilict** [comment]
For example,when I finish one line:
## This is a line
When I click at the end of it,the cursor disappear;but I can still type some letter.

**Comment by Consumered** [comment]
I'm seeing this occur erratically, again, only with the end of lines. I will update with additional details if I can repro reliably.

I suspect this may be related to the cursor at the end of the line being rendered differently from in the middle/start. Navigating left from a Heading end-of-line often shows a remnant of the cursor, similar to ghosting effects (and going back and forth can induce two cursors) which does not occur anywhere else in the document nor with Paragraph lines.

Just a shot in the dark in case this helps identify the issue: it looks like it could be a dirty state if the end-of-line cursor is being drawn/cleared separately for Headings, since this issue seems to crop up in a fashion as if the line state gets stuck as `hidden` or `visible` (after which the line fails to show the cursor at the end of the line until the line is cleared).

Windows 10
v0.9.23 (beta) x64

**Comment by klydd** [comment]
I am having the same issue on Typora version 0.9.25 on Windows 7.

Made a gif to illustrate the problem:

![](https://i.imgur.com/Ouvc3bY.gif)

**Comment by abnerlee** [comment]
Should be fixed already
