### ISSUE TITLE
timescale on gannt charts not very flexible

### ISSUE THREAD

**Issue by duncanmapes** [typora/typora-issues#398]
I am trying to put together a chart that spans 8-10 months but i cannot change the scale from weeks to months or quarters..  is there a way to do this?

**Comment by abnerlee** [comment]
Hi, for mermaid chart feature, you should report to https://github.com/knsv/mermaid

After the support this feature, we will follow

**Comment by aral** [comment]
Hi @abnerlee, can we please reopen this? Currently the default initialisation for Mermaid results in an x-axis for Gannt charts that is fixed to weeks and also starts the weeks at zero (W0, W1, etc.)

<img width="441" alt="screen shot 2017-12-21 at 15 11 30" src="https://user-images.githubusercontent.com/41798/34259119-454a90cc-e661-11e7-96dd-f62b7c333edf.png">

I was able to get it to display the actual dates on the x-axis (which is what I’d like for my charts) using the development console and running:

```javascript
mermaidAPI.initialize({
               startOnLoad:true,
                gantt: {
                    axisFormatter: [
                        // Monday a week
                        ["%-m/%-d", function (d) {
                            return d.getDay() == 1;
                        }]
                    ]
                }
            });
```

(Code courtesy: https://github.com/knsv/mermaid/issues/171#issuecomment-110877592)

That results in:

<img width="479" alt="screen shot 2017-12-21 at 15 11 13" src="https://user-images.githubusercontent.com/41798/34259142-5fc300f6-e661-11e7-9dd4-4abfe7afb71a.png">

But, of course, that is only a temporary workaround.

Ideally, of course, Mermaid should have the x-axis setting as a parameter you can set in the Markdown itself. However, in the absence of this, may I please ask that the functionality I used above be made the default functionality (especially since the current default, with weeks starting at zero, is not a format that’s used anywhere as weeks start at one by convention).

Thanks!

**Comment by abnerlee** [comment]
it is already supported by mermaid/typora, e.g:
```mermaid
gantt
  dateFormat YYYY-MM-DD
  title Adding GANTT diagram functionality to mermaid
  section A section
  Completed task :done, des1, 2014-01-06,2014-01-08
  Active task :active, des2, 2014-01-09, 3d
  Future task : des3, after des2, 5d
  Future task2 : des4, after des3, 5d
```
