### ISSUE TITLE
Sort by modification date broken on startup

### ISSUE THREAD

**Issue by nanoant** [typora/typora-issues#4064]
It looks like one of the recent versions (running `0.9.9.36.2 (4901)`) has broken sorting by modification date on startup and files are sorted by random fashion, I need to click sort by date twice to restore the list to the correct order
<img width="235" alt="image" src="https://user-images.githubusercontent.com/103067/102546381-d87a0400-40b7-11eb-9eac-7d690f57efc1.png">

**Comment by abnerlee** [comment]
> It looks like one of the recent versions has broken sorting by modification date on startup and files are sorted by random fashion, 

Could you shared detailed steps? It seems working if I open folder in Typora. What is your "on launch" option?

**Comment by nanoant** [comment]
Yes my on launch option is to open folder in `~/Documents/Notes`
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103067/102884488-f3e76500-4451-11eb-9777-ee18870cdfb3.png">

My sort order is descending modification date, however when I open Typora the files are sorted in random order:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/103067/102884675-53de0b80-4452-11eb-96e6-c2da330da627.png">

It looks like the issue is *macOS* specific as on my business Windows laptop it works fine.

**Comment by abnerlee** [comment]
fixed in new release

**Comment by merondun** [comment]
Hi, I am seeing a similar issue (although this may be an enhancement suggestion) in windows now with version 1.6.7 (windows 10.0.19045). With `On Launch` set to my .md folder: 

![image](https://github.com/typora/typora-issues/assets/72861773/23a041df-4eef-4247-86c8-8adceb03e89a)

The folder opens, but it always resets the sorting to 'Natural', which ends up being a pain when I tend to open several times a day (3 extra clicks: triple dot > Sort Modification Date twice).

![image](https://github.com/typora/typora-issues/assets/72861773/4acd4eb3-2d28-4be3-b47f-fd7ed74412ad)

Previously I modified my `.json` to remember these preferences...but my hard drive crashed and I unfortunately didn't back that file up. It might be an easy fix for typora to remember the sorting option, otherwise if you wouldn't mind sharing the `.json` line to remember sorting by modification date (descending), or pointing me to the issue that references this I will bookmark it. I searched online and the git but couldn't find an issue talking about this exactly..but of course I likely missed it. 

Thanks!
