### ISSUE TITLE
Space not preserved for code fences in some export formats (PDF)

### ISSUE THREAD

**Issue by dimosr** [typora/typora-issues#4091]
First of all thanks for building Typora!

When exporting  a markdown document from Typora to PDF, all the space inside code fences seems to be removed. This makes the experience very bad for the reader, since they cannot just copy+paste the code into their editor. In the general case, the pasted code is unreadable, but in some cases (see Python) it might even be invalid code.

Is there some way/workaround to prevent this from happening (e.g. using CSS) or is this a bug?
Thanks.

Typora version: 0.9.9.33.2

P.S.: Space seems to be preserved in some formats (e.g. HTML).

**Comment by abnerlee** [comment]
Which theme did you use, and possible to provide a sample md file?

**Comment by dimosr** [comment]
I noticed it with Whitey, but I managed to reproduce it with the Github theme too.

I've attached a sample .md file. When I export a PDF file from it using either of these two themes and try to copy/paste the code snippet, space is not preserved.

[example.zip](https://github.com/typora/typora-issues/files/5830922/example.zip)

**Comment by abnerlee** [comment]
I think is it not related to code.

You can write a markdown file containing whitespace at the start of some lines,
Then export to HTML
Open in Edge or Chrome and print it to PDF.

The whitespace are also un-selectable in output PDF.

The issue is either the spec of the printer (Chrome) or of the PDF reader. for all webpage (I guess). So I don't think we can fix this in Typora side.

Related discussion: https://community.adobe.com/t5/framemaker/copied-text-from-pdf-is-pasted-without-spaces/td-p/5723306?page=1

**Comment by dimosr** [comment]
indeed, seems like it depends on the reader. I tried with some other readers and seems like they preserve _some_ spaces when copying code snippets.
