### ISSUE TITLE
Recover drafts when macOS restarts

### ISSUE THREAD

**Issue by zaeemnalla** [typora/typora-issues#4165]
I had a few new tabs open in Typora with notes jotted down in each but didn't save them as files - I noticed that based on my settings, whenever I quit the app (`cmd+Q`) and reopen it, it picks up from where I left off by opening all of my drafts. 

I needed to restart my laptop but didn't quit Typora before doing so. Once Typora had reopened after the restart, all of my drafts were gone. They're not in` ~/Library/Autosave Information` either. Any idea where I can find them?

**Comment by abnerlee** [comment]
saving to ~/Library/Autosave Information and restore on reopen is the system logic.

> Once Typora had reopened after the restart, all of my drafts were gone. 

You mean previous file is not reopened, and it shows "untitled"?

**Comment by YYan2017** [comment]
I met the same problem, I think it obviously means the drafts just "gone", you can't find the files anymore, even in the ~/Library/Autosave Information. Please give us a solution to getting back our files ( for example, how we can find them back by time machine? ) Otherwise it will continually bring endless losses to your users, which is totally unbearable.

> saving to ~/Library/Autosave Information and restore on reopen is the system logic.
> 
> > Once Typora had reopened after the restart, all of my drafts were gone.
> 
> You mean previous file is not reopened, and it shows "untitled"?
