### ISSUE TITLE
Feature Request: Adding watermark to inserted images

### ISSUE THREAD

**Issue by changlan** [typora/typora-issues#4196]
Hi, I think it'd be great to have an option to add watermarks to inserted images. If enabled, Typora can automatically add the user-configured watermark when it copies / uploads the images. The user could also specify which corner to add the watermark. Thoughts?

**Comment by AlexPasternak** [comment]
I think this would be completely outside of the core scope of the application, and best left to an image editor. Do you have another text editor in mind that does this, because I've never seen this built in, personally.

If you'd like to automate this, you likely need to enlist a workflow tool like Hazel to automatically add the watermark. This to me goes in line with "insert today's weather into document" type of requests.

**Comment by abnerlee** [comment]
You can use custom command to do this.

https://support.typora.io/Upload-Image/#custom

https://stackoverflow.com/questions/5533458/how-to-add-watermarks-to-images-via-command-line-hopefully-using-irfanview
