### ISSUE TITLE
No justification because pre-wrap

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#42]
In `base.css` there's this:

    35    white-space: pre-wrap;
    36    text-align: justify;

`justify`isn't available inside `pre-wrap`. Seems to me that it isn't even in the standard: https://www.google.fi/search?q=pre-wrap+justify

Everything seems ok after commenting the first line out and — most importantly — the text is justified.

**Comment by abnerlee** [comment]
:+1:

**Comment by abnerlee** [comment]
`white-space: pre-wrap;` has been removed from v0.9.8.5 as a hot fix.

But 
```
white-space: pre-wrap;
text-align: justify;
```
should be supported as there are no conflicts between those two rules, and in chrome 47 they are supported. 

However, since safari/webkit does not support this, I removed `white-space: pre-wrap;` to make `text-align: justify;` possible

**Comment by abnerlee** [comment]
I will still restore `white-space: pre-wrap;` in `base.css` from next version up. 

Because without pre for whitespace, `\t` won't be rendered in HTML. For users who want `text-align: justify;`, he need to add `white-space: normal` in css, and the known bug that will case is that TAB key cannot be inserted correctly.

Windows version won't be affected

**Comment by SMontiel** [comment]
With the theme Whitey, that theme justify text.

**Comment by yatharthb97** [comment]
> With the theme Whitey, that theme justify text.

I am trying to do the same and it does not work on me. I am using Version 1.7.3 (7006) on Mac M1 (macOS Monterey v12.5). Could anyone help me?
