### ISSUE TITLE
Increase font size for LaTeX render preview

### ISSUE THREAD

**Issue by aron-hoogeveen** [typora/typora-issues#4248]
Feature enhancement.
The preview for the LaTeX rendering is on the small side. I have to really come close to my monitor to see the preview while typing LaTeX, but the inline rendered LaTeX is readable. See following screenshot:
![Knipsel](https://user-images.githubusercontent.com/28545476/111321853-9e91ad00-8668-11eb-8b9c-ac5ff2ff0289.PNG)
It would be nice if we can set the font size for the preview render, or if the default font size for the preview render is increased.

**Comment by abnerlee** [comment]
You could use `.MathJax_SVG svg {zoom: 2}` in custom CSS to zoom math svgs. 

The font size for preview is same with font size of rendered math, whose font size is same with other normal texts. So we do not have plans to increase preview font size, since the the size will not be matched with your normal texts. Therefore, you can also increase text font size or zoom the editing view.
