### ISSUE TITLE
New Update break everything cant open the Typora

### ISSUE THREAD

**Issue by skillhacker-code** [typora/typora-issues#4388]
After the update that changed the Typora Logo( 0.10.3) , the app is no longer opening .

I had to uninstalled the new version and installed version 0.9.98 beta and now it is working .

This is very unfortunate , because I loved the Typora app and it is not opening in the new version .

Please fix this issue .

**Comment by abnerlee** [comment]
send us the log (https://support.typora.io/Get-Logs/) please?

**Comment by liyewen521** [comment]
Hello, I can not open Typora, too. Due to there are not sensitive data in my log data, so I put it here. And my OS is Windows 10 Education 10.0.19042(the latest), and my Typora is the latest version(I download it from https://typora.io/#windows)

Hope you can find the solution, The Log is here:
`
INFO 2021/5/13 下午2:47:56  ------------------start------------------
INFO 2021/5/13 下午2:47:56  typora version: 0.10.9
INFO 2021/5/13 下午2:47:56  [Raven] instanceKey = 1ad2603c-a79a-4293-b2d5-12bd2f16f2c4
INFO 2021/5/13 下午2:47:56  [Raven] userId = 5fff5147-99b0-485b-a550-7daf5f03053f
INFO 2021/5/13 下午2:47:56  launch from abnormal quit
INFO 2021/5/13 下午2:47:56  recoverWindow {"id":1,"useCRLF":true,"hasUnsaved":true,"scrollPos":0,"syncDate":1620837483201,"mountFolder":null}
INFO 2021/5/13 下午2:47:56  [1] recover from content 0 
INFO 2021/5/13 下午2:47:56  skip due to empty untitled file
INFO 2021/5/13 下午2:48:07  got argv [D:\Applications\Typora\Typora.exe --allow-file-access-from-files] from secondary instance
INFO 2021/5/13 下午2:48:07  secondary instance would exit
INFO 2021/5/13 下午2:52:34  ------------------start------------------
INFO 2021/5/13 下午2:52:34  typora version: 0.10.9
INFO 2021/5/13 下午2:52:34  [Raven] instanceKey = d19c3602-41e3-4976-b618-f398cd655d09
INFO 2021/5/13 下午2:52:34  [Raven] userId = 5fff5147-99b0-485b-a550-7daf5f03053f
INFO 2021/5/13 下午2:52:34  launch from abnormal quit
INFO 2021/5/13 下午2:52:34  recoverWindow {"id":1,"useCRLF":true,"hasUnsaved":true,"scrollPos":0,"syncDate":1620837483201,"mountFolder":null}
INFO 2021/5/13 下午2:52:34  [1] recover from content 0 
INFO 2021/5/13 下午2:52:34  skip due to empty untitled file
INFO 2021/5/13 下午2:57:42  got argv [D:\Applications\Typora\Typora.exe --allow-file-access-from-files] from secondary instance
INFO 2021/5/13 下午2:57:42  secondary instance would exit
INFO 2021/5/13 下午3:06:16  ------------------start------------------
INFO 2021/5/13 下午3:06:16  typora version: 0.10.9
INFO 2021/5/13 下午3:06:16  [Raven] instanceKey = fa61f0fb-a4ef-4ba7-a9b9-82fbd6175d57
INFO 2021/5/13 下午3:06:16  [Raven] userId = 5fff5147-99b0-485b-a550-7daf5f03053f
INFO 2021/5/13 下午3:06:16  launch from abnormal quit
INFO 2021/5/13 下午3:06:16  recoverWindow {"id":1,"useCRLF":true,"hasUnsaved":true,"scrollPos":0,"syncDate":1620837483201,"mountFolder":null}
INFO 2021/5/13 下午3:06:16  [1] recover from content 0 
INFO 2021/5/13 下午3:06:16  skip due to empty untitled file
INFO 2021/5/13 下午3:09:00  ------------------start------------------
INFO 2021/5/13 下午3:09:00  typora version: 0.10.9
INFO 2021/5/13 下午3:09:00  [Raven] instanceKey = 901f9bbf-7fce-4944-bdf8-0372a2bd0594
INFO 2021/5/13 下午3:09:00  launch from abnormal quit
INFO 2021/5/13 下午3:09:00  recoverWindow {"id":1,"useCRLF":true,"hasUnsaved":true,"scrollPos":0,"syncDate":1620837483201,"mountFolder":null}
INFO 2021/5/13 下午3:09:00  [Raven] userId = 5fff5147-99b0-485b-a550-7daf5f03053f
INFO 2021/5/13 下午3:09:00  [1] recover from content 0 
INFO 2021/5/13 下午3:09:00  skip due to empty untitled file
INFO 2021/5/13 下午3:15:09  got argv [D:\Applications\Typora\Typora.exe --allow-file-access-from-files] from secondary instance
INFO 2021/5/13 下午3:15:09  secondary instance would exit
`

**Comment by abnerlee** [comment]
hot fix is to remove C:\Users\{username}\AppData\Roaming\Typora\backups

But we will fix this.

**Comment by liyewen521** [comment]
Okay, Typora open successfully when I remove C:\Users{username}\AppData\Roaming\Typora\backups.

Thanks, hope you can fix this bug in next release.

**Comment by abnerlee** [comment]
should be fixed
