### ISSUE TITLE
Jump using title tag and roll problem.

### ISSUE THREAD

**Issue by HYBB-rash** [typora/typora-issues#4429]
When I use jump function by title tag, I must **double tick** to jump. I don't know what happen in typora.
![jump_gif](https://user-images.githubusercontent.com/55585958/119430714-d5103600-bd43-11eb-90ad-3c538f94eef1.gif)
At the same time, roll will have the same problem. Typora will shake if I try to roll. I feel bad when I am focus on typing.
I find version 0.9.98 is good, but the 0.10.11 will have this problem.

**Comment by HYBB-rash** [comment]
When I try to roll my file, Typora will shake like this gif.
![typora_bug5](https://user-images.githubusercontent.com/55585958/119447539-a2296a80-bd62-11eb-87c7-ddbb532c37fe.gif)
This problem is not good for me when I am typing. Where is Typora log file? I could provide more message if I can find the log file, please help me resolve this shake problem ...

**Comment by Shen897** [comment]
Here info on how to get the logs https://support.typora.io/Get-Logs/    

On Windows there is a `typora.log` under `C:\Users\{username}\AppData\Roaming\Typora`.
You could also click “Open Theme Folder” in preference panel, and find typora.log on its parent folder.

**Comment by HYBB-rash** [comment]
> Here info on how to get the logs https://support.typora.io/Get-Logs/
> 
> On Windows there is a `typora.log` under `C:\Users\{username}\AppData\Roaming\Typora`.
> You could also click “Open Theme Folder” in preference panel, and find typora.log on its parent folder.

Thanks! I had fund the log file.
Maybe this error message is valued.
```
ERROR 2021/5/25 上午10:14:15  unhandledRejection TypeError: Cannot read property 'close' of null
    at C:\Program Files\Typora\resources\app\atom.asar\updater.js:286:27
INFO 2021/5/25 上午10:14:15  [blur] 2
INFO 2021/5/25 上午10:14:17  [focus] 2
INFO 2021/5/25 上午10:14:17  C:\Users\hyong\AppData\Local\Temp\typora-update-x64-0.10.11.exe
INFO 2021/5/25 上午10:14:17  ----------------before-quit-----------------
INFO 2021/5/25 上午10:14:17  ----------------before-quit-----------------
INFO 2021/5/25 上午10:14:17  ------------------will-quit------------------
INFO 2021/5/25 上午10:14:44  luanchFromDiffVersion, pre version is 0.9.98
INFO 2021/5/25 上午10:14:44  overwriteThemeFolder
INFO 2021/5/25 上午10:14:44  ------------------start------------------
INFO 2021/5/25 上午10:14:44  typora version: 0.10.11
INFO 2021/5/25 上午10:14:45  [Raven] instanceKey = 8ac91cc0-4464-4805-a518-78de0f1ef68d
INFO 2021/5/25 上午10:14:45  [Raven] userId = 6ff4909c-53b1-4267-9a82-c51bc1ad13e2
INFO 2021/5/25 上午10:14:45  addRecentDocument
INFO 2021/5/25 上午10:14:45  added recovery 1 D:\Users\hyong\Documents\MyNote\English\paper\cet-6\cet6-2020-9-1.md undefined (0)
INFO 2021/5/25 上午10:14:45  [focus] 1
INFO 2021/5/25 上午10:14:46  synced recovery
INFO 2021/5/25 上午10:14:47  handle document.loadInitData
INFO 2021/5/25 上午10:14:47  added recovery 1 D:\Users\hyong\Documents\MyNote\English\paper\cet-6\cet6-2020-9-1.md undefined (0)
INFO 2021/5/25 上午10:14:47  synced recovery
INFO 2021/5/25 上午10:14:58  [blur] 1
INFO 2021/5/25 上午10:14:58  [win] blur
INFO 2021/5/25 上午10:14:59  [focus] 1
INFO 2021/5/25 上午10:15:01  [blur] 1
INFO 2021/5/25 上午10:15:01  [win] blur
INFO 2021/5/25 上午10:15:02  [focus] 1
INFO 2021/5/25 上午10:15:43  [blur] 1
INFO 2021/5/25 上午10:15:43  [win] blur
INFO 2021/5/25 上午10:15:44  [focus] 1
INFO 2021/5/25 上午10:15:46  [blur] 1
INFO 2021/5/25 上午10:15:46  [win] blur
```

**Comment by abnerlee** [comment]
1. This is happens in default theme?
2. Could you attach or send a sample md file to <hi@typora.io> and provide steps to reproduce this issue?

**Comment by HYBB-rash** [comment]
> 1. This is happens in default theme?
> 2. Could you attach or send a sample md file to [hi@typora.io](mailto:hi@typora.io) and provide steps to reproduce this issue?

@abnerlee Thanks to reply! 

In the gif what I show is not in default theme. The theme name is Gitbook Teal.  But when I switch to  the default theme, there is the same problem in the default theme.

Just wait a moment, I will sent more detail by email.

**Comment by HYBB-rash** [comment]
> 1. This is happens in default theme?
> 2. Could you attach or send a sample md file to [hi@typora.io](mailto:hi@typora.io) and provide steps to reproduce this issue?

@abnerlee Sorry, finally I find that the problem is only happen in the [Gitbook theme](https://github.com/16soundsofsilence/typora-gitbook-theme).

It just a theme problem?

I have sent the email.

**Comment by 16soundsofsilence** [comment]
Hello @abnerlee and @HYBB-rash, I think I have isolated what causes this problem. It seems to appear when you add a transition to the class `outline-label` like I have done it in my theme.

The stuttering can be reproduced by creating a theme which just contains this bit of css:

```css
.outline-label {
  color: black;
  transition-duration: 1s;
  transition-property: color;
}

.outline-label.outline-active {
  color: blue;
}
```

The issue occurs only if the outline in the sidebar is opened. For me it sometimes takes a little bit of scrolling (and it only becomes obvious within a document with quite a few headers) until it starts to stutter.

I will update the theme soon by removing the transition.

However, i don't know whether this is an expected behavior as it didn't seem to be an issue in version 0.9.98.

It isn't a major issue though, as the transition duration in my theme was only 0.3s long.

**Comment by 16soundsofsilence** [comment]
@abnerlee I would just like to point out that also other parts stop behaving as expected when they have an transition property applied since version 0.10.11, in case you are not aware of it.
For example the context menu doesn't appear (and only flashes shortly) on unfocused sidebar items, as mentioned [here](https://github.com/16soundsofsilence/typora-gitbook-theme/issues/24). Though again, the fix is pretty easy - it's just a matter of removing this transition.
