### ISSUE TITLE
Failed to replace map bed uploading

### ISSUE THREAD

**Issue by misteruly** [typora/typora-issues#4494]
Failed to replace map bed uploading

The picture is the original map bed link, now changed map bed, then upload all local images failed.
How to solve it？

**Comment by abnerlee** [comment]
I guess the tool you use to upload images does not support uploading an "online" images, that's why it fails.

you can try workaround:
change option to move images to folder when insert images -> export md file to html -> copy & paste into new typora document -> change image options -> upload all images
