### ISSUE TITLE
After every update there will be a folder called "(Defalut)" created in the star menu.

### ISSUE THREAD

**Issue by htw128** [typora/typora-issues#4735]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
After I upgrade the typora either with a package manager, like scoop, or with the build-in tool, there is always a "(Default)" folder created in the path `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` .

**To Reproduce**

Update typora 

**Expected behavior**

I believe this folder should be called "Typora". Even better, there shouldn't have a folder with just on app in it.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit 21H1 19043.1288

**Typora Version**
0.11.13(beta)

**Comment by gorskii** [comment]
relates to https://github.com/typora/typora-issues/issues/3730

Probably triggered by install or upgrade using package manager, since all package managers use installers listed on https://typora.io/windows/dev_release.html, as there is no other source of versioned installers. These installers are not identical to those published on the [main page](https://typora.io/#windows). Related issues here https://github.com/typora/typora-issues/issues/4736 and in https://github.com/microsoft/winget-pkgs/issues/30727

**Comment by abnerlee** [comment]
We now keeps the setup.exe from v1.0, this should be fixed
