### ISSUE TITLE
[Feature] Zoom with mouse wheel

### ISSUE THREAD

**Issue by tobiasrenkin** [typora/typora-issues#4862]
This has been raised before (and closed w/o explanation). The vast majority of applications use ctrl + wheel and ctrl + "+" / "-" to zoom. Please consider adding this option. Ctrl + shift + "+" or "-" is extremely unintuitive to me, and I am sure to others.

**Comment by ibonito1** [comment]
I support this strongly! I'd even pay another 5 bucks just to get this feature!

**Comment by abnerlee** [comment]
relates #3975

**Comment by poisonborz** [comment]
Please add this... **Typora is almost the only major text editor that does not support this.**

@abnerlee previously said "easy to trigger by mistake, so we do not have plans for this"

Word, Google Docs, Sublime, IntelliJ, VSCode all have this... along with every app that has desktop zooming like Google Maps, without users mistakenly triggering it.

This is something users would expect to work out of the box.

**Comment by ibonito1** [comment]
I absolutely agree with @poisonborz !

> @abnerlee previously said "easy to trigger by mistake, so we do not have plans for this"
And even if this was true (it totally might be for some people), then please give us the option to choose! If you feel so strongly about it, activate it by default, but please give us the option.

**Comment by Cuissedemouche** [comment]
Hey, I would also love this feature, I really like Typora, but zooming with the mouse wheel is an essential for me and don't understand why it's missing. As @ibonito1 said, it could be an option to enable.

**Comment by celmi** [comment]
I too came here to report this and was surprised to find this relatively old thread on this. Yes, Typora's behaviour in this respect is really counter intuitive, even more so, as the plus/minus key on the numpad are not accepted as input. On my swiss german keyboard I would need to press shift to reach the plus sign on the normal keyboard (key for 1), so ctrl-shift-+ would work for me only if I can use the plus sign on the numpad.
So, for me the priorities would be:
1. allow plus sign to be pressed on numpad (for typora-specific keyboard shortcut ctrl-shift-+)
2. additionally, allow users to use ctrl-mousescrolling to zoom in or out
3. change that unusual keyboard shortcut to "general standard" ctrl-+

Thank you for the otherwise fantastic software.

**Comment by cxplay** [comment]
Cool, today is 2023/11/20😅.
We already need this feature.

**Comment by abnerlee** [comment]
supported in 1.8.6 as an opt-in option

See https://support.typora.io/What's-New-1.8#zoom-with-mouse-wheel
