### ISSUE TITLE
LaTeX possible?

### ISSUE THREAD

**Issue by Fastidious** [typora/typora-issues#5]
Is it possible to include the ability to utilize LaTeX within Typora? How is Math being handled?

**Comment by abnerlee** [comment]
Currently, typora can handler block level math/TeX code (wrapped by $$) and inline level math/TeX code (wrapped by $ or $$, and you should use v0.9.6.1 and enable it in preference panel). You can see one demo [here](https://twitter.com/Typora/status/637495313259892740/photo/1)

And it is powered by [MathJax](http://docs.mathjax.org/en/latest/tex.html). 

Therefore, **yes**, the LaTeX expression is supported by MathJax, but still limited, since the render engine -- MathJax "implements **only the math-mode macros** of TeX and LaTeX, not the text-mode macros". But I think in most case it should be enough, because, to some degree, "text-mode macros" can be replaced by Markdown itself.

**Comment by Fastidious** [comment]
@abnerlee excellent! Thank you much.

**Comment by mklilley** [comment]
Hi.

Just found Typora today and am absolutely loving it!

Just wondered whether you had a view on Katex as a possible alternative/ option when compared to MathJax. 

Seems like Katex is a lot faster https://www.intmath.com/cg5/katex-mathjax-comparison.php although I do think it has a more limited set of symbols.
