### ISSUE TITLE
Text corrupted when Typora reads a file with accented characters [Windows]

### ISSUE THREAD

**Issue by starise** [typora/typora-issues#501]
On the latest Typora v0.9.23 (beta) @ Windows 10.

I'm having some kind of strange character encoding issue with accents in my language (italian). I couldn't understand what happend, but now I figured out what it is after dozens of tests.

The bug doesn't happens all the time, looks like is present only on certain conditions, Typora corrupts the text as you can see in the picture above:

![Example of corruption](http://i.imgur.com/MzBdila.png)

But, opening the same file in another text editor (Atom) it looks fine. So the mistake happens when Typora tries to read the file. Trying to save the file in Typora, causes a definitive corruption.

The weirdest thing is that: putting just one of the two same exactly "incriminated" paragraphs (copy-paste), and trying to open it in Typora, you got the file correctly displayed. So, I suppose it could be related to the "quantity" of accented characters or something like that.

I hope this is sufficient to find what the problem is. Thanks for your time.

Text that causes the issue: http://pastebin.com/eKSeJZvk

**Comment by gpascii** [comment]
Same here, file is saved correctly but sometimes is displayed with the wrong encoding.

In my machine the bug is reproducible with this steps:
- open Typora and type some text with accents like "asd òèàìù asd òèàù dsa òèàùì"
- save the file and close
- reopen the file
- "asd 簷癡�𦟌珍� asd 簷癡�𦟌� dsa 簷癡�𦟌嘔�" !!!!

Typora 0.9.23(beta) - elementary OS Loki (4.4.0-59-generic)

**Comment by abnerlee** [comment]
fixed in new release
