### ISSUE TITLE
[Feature] iOS, iPadOS and Android App

### ISSUE THREAD

**Issue by OrangeEd1t** [typora/typora-issues#5154]
Does typora have a plan to develop a mobile version? It is already version 1.0+, I hope to support the mobile terminal as soon as possible, I am very much looking forward to it!

**Comment by abnerlee** [comment]
dup with #4942

**Comment by nextlogic-ono** [comment]
The problem is, that there isn't a mobile app that works well like Typora. I've tried a dozen on both iOS and Android and either they aren't good enough or they have Markdown compatibility issues. (Like tables and horizontal bars not working or links getting stripped etc)

Anything planned? I would easily pay the same price on both platforms.
