### ISSUE TITLE
Math block was tore after typora file exported into pdf

### ISSUE THREAD

**Issue by ChanTau** [typora/typora-issues#5156]
![image](https://user-images.githubusercontent.com/52941654/161383014-8106b231-0854-4925-be43-fe7f8a7c6839.png)
![image](https://user-images.githubusercontent.com/52941654/161383021-476c030a-7026-421e-ad06-8f0d2becbb38.png)
How can I tackle this problem? Thanks!

**Comment by abnerlee** [comment]
Could you provide a sample md file?

And what is your OS?

**Comment by ChanTau** [comment]
Sorry, I already deleted the file, but the contents were just typed in an normal way. My OS is Win10.

**Comment by Llemaban** [comment]
The following zip contains a sample md and the exported PDF, one with the default GitHub theme and the other with my own Academic theme. In both cases the math block at the end of the page is tore.
[typora-issue_issues_5156.zip](https://github.com/typora/typora-issues/files/8547404/typora-issue_issues_5156.zip)
This also happens if a text block is in between the math blocks.
[typora-issue_issues_5156-2.zip](https://github.com/typora/typora-issues/files/8547424/typora-issue_issues_5156-2.zip)
Exported with Typora 1.2.4 on Win10.

I'm not sure if this is related with #5173 and #3418 as i haven't seen this issue before the update from 1.1.5 to 1.2.4 and i used a lot of maths in other exported md's before.

**Comment by Llemaban** [comment]
**Working Solution**
Add the following to the sytel sheet:
```css
.md-math-container {
	page-break-inside: avoid;
}
```
The math blocks will not be tore anymore after the export to PDF.
[Current_Integrator_Test_WithText_CssModified.pdf](https://github.com/typora/typora-issues/files/8550149/Current_Integrator_Test_WithText_CssModified.pdf)
Exported with Typora 1.2.4 on Win10 with the described modification of my own Academic style sheet.
(Refer to the previous uploaded zip [typora-issue_issues_5156-2.zip](https://github.com/typora/typora-issues/files/8547424/typora-issue_issues_5156-2.zip))

**Comment by abnerlee** [comment]
fixed in 1.4.4
