### ISSUE TITLE
Generated Markdown could be hard-wrapped for easier reviewing in code review tools

### ISSUE THREAD

**Issue by mikehearn** [typora/typora-issues#522]
Currently Typora generates markdown that never hard wraps. This makes it annoying to review files generated with the tool in a code review environment. It'd be nice if the generated text could be hard-wrapped at 80 cols by default.

**Comment by kellpossible** [comment]
agreed, this is a bit of a blocker for me using this

**Comment by vassudanagunta** [comment]
If the purpose is to facilitate "review files generated with the tool in a code review environment", then Typora *should NOT* automatically hard wrap. The author should do that manually. If Typora automatically reflows and rewraps text after the writer has inserted even a single word, the diffs will most often no longer line up, defeating the stated purpose.

The only thing needed is for Typora to implement #364, which it already has.  Please reject and close this request.

**Comment by kellpossible** [comment]
Is there a problem with providing an option to allow Typora to do this, it could even just be something that happens on saving the document? I don't think anyone is suggesting this behavior should be enabled by default. The teams that I have worked with that would benefit from this feature review our changes to documentation and user manuals alongside the related changes to code code in the same environment. Having this feature makes Typora an easier sales pitch because it integrates better with  existing tools. Having it reflow and not have the diff lines up is a smaller problem than having extremely long lines, many tools do not support soft wrapping in diffs (the entire Atlassian stack), and many companies are tied to these tools. Many people also just prefer having documents which are formatted this way, myself included.

**Comment by kellpossible** [comment]
But I can also see your point, ideally the review tools should support soft breaks, and the reviews would be more accurate.

**Comment by kellpossible** [comment]
It solves the problem because at least it's readable on the review/diff screen without the horizontal scroll bars.  It puts Typora on par with the multitude of other text editors we could use for this purpose of editing markdown.

Neither of their tools supports it yet, and given the backlog of over 1000 issues I doubt it's going to get fixed on their end soon 😢 

https://jira.atlassian.com/browse/SRCTREE-869

https://jira.atlassian.com/browse/BSERV-4134

Is there a way to disable the auto wrapping in Typora so that you can at the very least know when to manually hard wrap to keep the lines from getting too long?

**Comment by mikehearn** [comment]
We solved this for ourselves by switching to GitHub 😹

**Comment by kellpossible** [comment]
@mikehearn I wish that decision would be up to me! 😅

**Comment by whyrusleeping** [comment]
I would love an option in typora that auto wraps my paragraphs at a fixed width as i type them. As it stands, every paragraph i write in typora turns into one giant long line, and i have to manually go into source mode to break it into separate lines. As mentioned, this makes reviewing things pretty rough.

I wouldnt be too upset if there was just an easy way to tell typora to break up a paragraph into multiple lines. I'm currently just opening the files up in vim and using `gqq` to wrap everything.

**Comment by cwensel** [comment]
I concur. 

Optionally, on save, Typora should reflow the paragraph to a customizable width.

Not every developer on a project will use Typora, but the code standard for a project will limit line length which will apply to all developers.

**Comment by bartlettD** [comment]
Bumping an old issue, but I agree that an option to be able to automatically limit columns in the file so that they can be easily viewed in tools that don't reflow text.

For me, this isn't about code review tooling but just being able to read plain markdown without having to horizontal scroll.

**Comment by abnerlee** [comment]
merge into #1316
