### ISSUE TITLE
Generate HTML for code, TOC and diagrams when copy html code or export html (without styles)

### ISSUE THREAD

**Issue by owt5008137** [typora/typora-issues#535]
I want to keep table of content when export HTML(without styles), and I also want to use [highlight.js](https://highlightjs.org/) to highlight my codes. But [highlight.js](https://highlightjs.org/) use <strong><em>&lt;pre&gt;&lt;code class="LANG"&gt;codes..&lt;/code&gt;&lt;/pre&gt;</em></strong>to find all the codes need highlighted. Now the exported data is <strong><em>&lt;pre lang="LANG"&gt;codes..&lt;/code&gt;&lt;/pre&gt;</em></strong>and can not be used directly. 
Can we set the exported code content to adjust [highlight.js](https://highlightjs.org/) or [Syntax Highlighter
](https://github.com/syntaxhighlighter/syntaxhighlighter) or other libraries?

BTW: Can we keep TOC and diagrams when export  HTML without styles?

**Comment by jominions** [comment]
Also can we add support for LaTex? It seems that formulae are converted into SVG nodes.

**Comment by abnerlee** [comment]
We don't want to add one more option only to choose between `<pre><code></code></pre>` and `<pre>`. You can use js to switch between tow, since you will import highlight.js anyway.

TOC and diagrams also go against "without styles", since without style, toc are no difference than lists and diagrams will not be supported.

> Also can we add support for LaTex? It seems that formulae are converted into SVG nodes.

This option is already supported.
