### ISSUE TITLE
Export to PDF Failed - undefined?

### ISSUE THREAD

**Issue by uchiagehanabimaster** [typora/typora-issues#5390]
- [ DONE ] Searched existing issues to avoid creating duplicates.

- [ DONE ] Confirmed that it can be reproduced in built-in themes without customized css.

- [ DONE ] Searched http://support.typora.io/

----

**Describe the bug**
Failed to export to PDF, Typora says "Failed to export as PDF. undefined."

**To Reproduce**
1. Go to 'File'
2. Click on 'Export'
3. Scroll down to 'PDF'
4. See error (Obsidian has the same problem and **I'm sure that Print Spoller is running**)

**Expected behavior**
PDF export should succeed.

**Screenshots / Screencasts**
Now I want to show the log file from %APPDATA%/Typora
```
INFO 2022/8/26 08:47:00  [focus] 2
INFO 2022/8/26 08:47:05  load file [C:\Users\Suffron\AppData\Local\Temp\1661474825835-0.9204713473211961.html] for PDF export
INFO 2022/8/26 08:47:06  [blur] 2
INFO 2022/8/26 08:47:06  [win] blur
ERROR 2022/8/26 08:47:06  Error: ERR_FAILED (-2) loading 'file:///C:\Users\Suffron\AppData\Local\Temp\1661474825835-0.9204713473211961.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///C:\\Users\\Suffron\\AppData\\Local\\Temp\\1661474825835-0.9204713473211961.html'
}
INFO 2022/8/26 08:47:06  generate print window with id null
INFO 2022/8/26 08:47:07  [focus] 2
```

**Sample Markdown File**
EVERY file has this problem.

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]

**Typora Version**
Multiple Versions alle failed to export as PDF on my computer, and Obsidian failed too.

**Additional context**

**Comment by abnerlee** [comment]
Does this work in v1.4.1-dev?

**Comment by abnerlee** [comment]
fixed in 1.4.4

**Comment by lyboos** [comment]
[ DONE ] Searched existing issues to avoid creating duplicates.

[ DONE ] Confirmed that it can be reproduced in built-in themes without customized css.

[ DONE ] Searched http://support.typora.io/

Describe the bug
Failed to export to PDF, Typora says "Failed to export as PDF. undefined."

To Reproduce
Steps to reproduce the behavior:

Go to 'File'
Click on 'Export'
Scroll down to 'PDF'
See error (Obsidian has the same problem and I'm sure that Print Spoller is running)
Expected behavior
PDF export should succeed.

Screenshots / Screencasts
Now I want to show the log file from %APPDATA%/Typora

**Comment by lyboos** [comment]
[ DONE ] Searched existing issues to avoid creating duplicates.

[ DONE ] Confirmed that it can be reproduced in built-in themes without customized css.

[ DONE ] Searched http://support.typora.io/

Describe the bug
Failed to export to PDF, Typora says "Failed to export as PDF. undefined."

To Reproduce
Steps to reproduce the behavior:

Go to 'File'
Click on 'Export'
Scroll down to 'PDF'
See error (Obsidian has the same problem and I'm sure that Print Spoller is running)
Expected behavior
PDF export should succeed.

Screenshots / Screencasts
Now I want to show the log file from %APPDATA%/Typora
