### ISSUE TITLE
Always display at primary screen and maximize instead of the same size as it's closed at last time

### ISSUE THREAD

**Issue by CompetitiveLin** [typora/typora-issues#5430]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in built-in themes without customized css.

   If it only exists in 3rd party themes or css, you can still report it, but please attach the theme target or the css file. We may not "fix" it, if it is caused by 3rd party themes or css styles that we cannot support.

- [x] Searched http://support.typora.io/

----

**Describe the bug**
Similar with #2225 #2255, but what's different is my typora always display at primary screen.

**To Reproduce**
1. Open the app
2. Move and resize it casually
3. Close and reopen it

**Expected behavior**
Size and position should be the same as it's closed at last time.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Typora Version**
Latest

**Comment by CompetitiveLin** [comment]
Fine! Back to normal now for no reason!

**Comment by selina-lii** [comment]
Hi, 

I still have this issue on Windows with version 1.7.5.

I normally use two screens and when I turn off the monitor, Typora's window will show up where the other monitor used to be instead of on the primary screen. So essentially I can't view the file content when the other monitor is disconnected.
