### ISSUE TITLE
Typora auto update to 1.4 in windows 11, bug with does not support windows 7?

### ISSUE THREAD

**Issue by Diskrepanz** [typora/typora-issues#5490]
I just open it and it auto updated to ver1.4. And it cannot open with the error: This version does not support Windows7? My system is windows 11.

**Comment by abnerlee** [comment]
Try launch Typora without using Windows 7 Compatibility Mode

**Comment by tsbertalan** [comment]
I'm getting this error when I "Open in default app" from Obsidian. On a fresh install of typora-setup-x64-1.6.7.exe, Windows 10 Education 22H2. Since I'm opening from another app (by whatever xopen-like mechanism they use to open a file with the OS-default editor), I don't know how I'd go about changing the compatibility mode of that launch.

![image](https://github.com/typora/typora-issues/assets/306137/c5e297ef-08fc-4589-9f00-0bf46fb97198)

If I browse to the location of the same MD file and open it with Typora by double-click, it opens fine.

**Comment by tsbertalan** [comment]
Any idea how I can change the compatibility mode applied for such inter-app "open" actions? This is my main use of Typora.

**Comment by abnerlee** [comment]
Did you also use compatibility mode for Obsidian? Could you try disable compatibility mode for apps that will open "Typora" as well?
