### ISSUE TITLE
Save as .txt not .md? - macOS

### ISSUE THREAD

**Issue by samuelgibbs** [typora/typora-issues#5638]
Apologies if already covered somewhere, I couldn't find anything mentioning this.

It used to be possible to save in **.txt** as an alternative to **.md** using Typora on macOS, but for the last few iterations that ability appears to have been removed? Is there a way to still do it? And if not, could I please request it as a feature?

Saving in .txt makes it much easier to view files on mobile/cloud syncing drives etc. At the moment I have resorted to manually changing the extension after saving.

Many thanks.

**Comment by Joytide** [comment]
What's stopping from saving with: File > Save as > _myfile.txt_ ? ( instead of _myfile.md_)
Are you talking about a feature such as File > Export > TXT ? Because it wouldn't really save any substantial amount of time compared to the above option. (I do agree manually changing the extension afterwards isn't optimal)

**Comment by samuelgibbs** [comment]
Typora no longer shows the option to Save as > myfile.txt. The only option for file format is Markdown, which appends .md.

**Comment by abnerlee** [comment]
fixed in 1.6.5
