### ISSUE TITLE
File Navigator and open folder as workspace

### ISSUE THREAD

**Issue by mahdaen** [typora/typora-issues#57]
Add file navigation to the left panel. Maybe the left panel will contains **`Files | Outline`**. Opening file or folder will show the folder with the files on the left panel. Also add editor tabs, so opening file from the file navigator will open the file in new tab instead of new window.

Add formatting popup when selecting text on the editor to allow users format the selected text, like http://sofish.github.io/pen/

Thanks!

**Comment by jhildenbiddle** [comment]
I just sent an email about a similar feature request. Here's the relevant part of the email: 

> Add a means of navigating files from within the application. This feature will allow Typora to function as a better note taking environment rather than just a viewer/editor for individual markdown files. Evernote and OneNote provide this, but content is not stored using markdown so it is locked in a proprietary format. Applications like Ulysses, Write and Falcon provide note navigation and allow authoring in markdown, but they do not have the “live” markdown view offered by Typora. By offering some form of file browsing Typora could easily replace these applications for users that just want a capable note-taking environment that doesn’t lock them into a proprietary format. For folks like me who begrudgingly use Evernote because they haven’t found anything better, this would be a very welcome change.

**Comment by rjeady** [comment]
Totally agreed, a file tree panel would be a terrific improvement! This is the main feature needed to make Typora a superb note-taking application in my view.

**Comment by waahto** [comment]
Not only for note taking, but for larger writing projects also. Strongly in favour of this one. My suggestion at #45.

**Comment by prefersC** [comment]
Maybe I don't understand the use case, but I can't imagine Typora matching the functionality in Finder, let alone PathFinder, or any mind map. I can run either beside Typora flawlessly, and do this because Typora likes to run in an uncluttered, desktop window. 

Markdown = text, meaning not proprietary. I prefer tools sets supported by multiple single function apps. I avoid nasty behemoth applications that take files for ransom, and attempt everything, especially on a desktop. OSX = Unix, and Unix offers many small tools that work well together, or at least it does at the $ prompt. 

If Typora could accept a folder, or a drop stack of files, of parse OPML, it could offer something useful, and play well with everything else. If it tries to outdo PathFinder or even Finder, it will probably fail.

Drop stack apps do, or at least should, share file lists across desktops, and even devices, assuming all the files are accessible. Perhaps Typora could do something similar. Consider, Yoink for instance, although I don't think it sync's across devices. It's in the app store. I paid for a copy, and have zero relationship with them. I just use it alongside Typora, and find it works extremely well.

**Comment by mahdaen** [comment]
@prefersC Major text/code editors support file navigator (e.g: Brackets, Atom, Sublime Text, etc). It's help us quickly switch to another files (inside project folder) without switching to other apps. It's not Finder, it's just a file navigator to allow us to open folder and then files or subfolders list will available on the sidebar.

**Comment by prefersC** [comment]
I guess I don’t distinguish between another app, or another window. I can’t really tell myself. 


Finder works great for displaying a list of files, especially if you hide all the nonsense. Path Finder works even better, with cool folder slide-outs, and other stuff, and opens files with a single click. I suggest changing double click behavior inside system preferences for your titlebars to minimize, instead of maximize. Don’t let your apps get too greedy, and make it easier for yourself, so you can always use the right tool.


Most Finder replacements have multiple file search and replace functions, often with regex, track recently changed documents, and so on. I have no relationship with any of these products, but I just can’t imagine Typora coming up with something cooler, or more functional, than current offerings. There’s no point really. It’s been done, and it’s a competitive area. 


I understand what you’re saying, but I honestly never use those cheesy things in apps like Atom, Ulysses, and the like. Why would anybody? I can click on the window of another app just as easily as I can click on a window in the same app. Zero difference.


I think you probably have an awesome solution already. You just need to configure it.

**Comment by prefersC** [comment]
One further comment, pre-app store applications had to do everything, because nobody trusted anything, and apps were hard to find.


That changed.


Atom is old.

**Comment by mahdaen** [comment]
Well, I use markdown to write documentations of my projects. I use WebStorm to write code, and obviously it has a markdown plugin. I try Typora because it has a cool feature (Live Preview) which I hope it allows me to work with multiple files in a single window.

I (not sure with most developers) chose to use CMD+] to switch between tabs instead using click click, thats why I prefer Typora to support File Navigator and Tabs. I don't like when my 4K display is full with Typora and Finder window (omg!) because I use 4K display to allow me to put Terminal, WebStorm, Slack, AirMail, and Chrome together.

So, who will use Typora? Writers? Not sure since Pages and Google Docs is exist. Developers? Not sure if they're comfortable with multiple Typora windows, and force them to use CMD+O and click click to open another markdown files.

File navigator and tabs feature is only a small piece, and it wont makes the Typora become a 1GB app.

**Comment by prefersC** [comment]
Maybe so then. 

I am a writer that works on massive a texts, and an old developer that still codes. I have a wall of screens but I never have more that a couple Typora windows open at any one time. I use a memory map. Everything is super easy to find. Source, text, images, whatever I click pops me in an editor. I close the windows when I'm done, or kind of done. I rarely look at 'files'. Only notated topics. 

I let makefiles, or near enough, feed pandoc, gcc, whatever. 

Different workflow I guess.

**Comment by prefersC** [comment]
Meant, I use a mind map. Not a memory map. I don't know what that is.

**Comment by mahdaen** [comment]
:D yep, mind map.

Well, feature is something that some peoples need it, and some peoples don't need it. When feature exist, peoples who don't need it can simply hide/disable the feature. But if the feature is not exist, what the peoples who need it can do? They only can ask the developer, or find another apps. Just opinion ;)

**Comment by prefersC** [comment]
You are absolutely right. I imagine they'll add something, just because everybody else has something, at it wouldn't bother me at all.

**Comment by rjeady** [comment]
If finder/windows explorer (please remember typora is cross-platform) is sufficient then should the file->open dialog be removed as well?

For me, including a simple file tree browser would mean I don't need to go hunting through my open Explorer windows whenever I want to switch to another note in my notebook folder. Plus it would save relaunching the application every time, which is quite slow because typora is a web app.

I think this would require a tabbed interface for multiple open documents to really work, though.

**Comment by prefersC** [comment]
Perhaps the concern is that simple is often misleading. A simple tree that just opens files? Renames them? Copies them? Moves? Deletes? Sorts? Then what?

From what I've see in Typora, it's unlikely the developers would want to add something, only to leave it wanting. 

No doubt, they would create something that's entirely optional to use, and I wouldn't use it, so I my comments really don't help this conversation very much.

**Comment by jhildenbiddle** [comment]
$0.02:

Agreed that a file/folder navigator within Typora does not need to recreate the functionality of Finder.

As @prefersC mentioned:

> I prefer tools sets supported by multiple, single function apps. I avoid nasty, behemoth applications that take files for ransom

Agreed. My desire for a file/folder navigator within Typora is specifically to allow me to abandon Evernote: an application that does way more than I need and stores my notes in a proprietary format. I frequently reference multiple notes while writing (file navigation) and I group my notes by subject matter (folder navigation). Typora addresses the proprietary format issues be storing data as Markdown, but the lack of a file/folder navigator makes referencing other files a laborious multi-window affair. Consider an application like Sublime Text (or any other text-editor used for development) and imagine having to manage separate windows for each file you're working with or need to reference along with one or more Finder windows to manage those files. Ugh.

What I would like to see is a "good enough" implementation that simply allows me to remain within the Typora writing environment.  Here is my proposal:

- Provide acess to the file/folder navigator in the same location as the Table of Contents panel
- Allow the navigator to be pinned to the left/right side
- Allow the Table of Content panel to be pinned to the left/right side
- Selecting a file in the navigator will load the document into the main view (single left-click)
- Documents with unsaved changes will display a small indicator next to the file name in the navigator.
- Each document maintains its own undo/redo state
- Right-clicking a file/folder in the navigator will display a context menu with basic file operators (rename, delete, duplicate)

This implementation intentionally removes the need for a tabbed interface. The idea is to allow multiple files to be open at one time (indicated visually within the navigator) while maintaining a clean single-window writing environment. For those that like Typora as-is, you'll never notice the difference.

**Comment by prefersC** [comment]
I’ll take one more stab at this, because I think it's helpful.


I suggest  anyone that works on projects with lots of files, to structure their projects in a mind map. It's easy, only takes a day to setup, and uses OPML, so you can always switch tools later if you want, and not lose any work. Open standards rock!


The other advantage, on a single map, you can easily access numerous projects, including all the details.


Setting up a mind map basically consists of creating a topic/node, give it the name of your project, then start adding child topics/nodes, and drag/drop or cmd+K to attach a file.


Once it's setup, you can expand, collapse, navigate, and so forth. You are no longer obligated to view your thoughts as files in a tree structure. You can create loops, add callouts, attach notes, synopsis, images, any kind of link.


Think of it as a project viewer. Think of OPML as a project file. Then go get an OPML editor.


Like John said, that's my $0.02 as well. Now I'm done.

**Comment by numbcoder** [comment]
File tree panel +1

**Comment by n3bulous** [comment]
@prefersC I agree w/ you about not wanting applications taking over files, but take a look at what [lightpaper](lightpaper.42squares.in) does.  It's a tabbed ui and a "project" manager allowing adding folders to the sidebar nav.  All it does is proxy the filesystem for easy access.

**Comment by vassudanagunta** [comment]
It really comes down to how important it is for Typora to be a *project editor* as opposed to a *single file editor*. 

I agree that for multi-document writing projects this would be useful, but since there is a work-around (native file browser), it is more important that Typora becomes rock solid and more feature complete as a markdown text editor first.

**Comment by vassudanagunta** [comment]
Another possibility is for Typora to become available as a plugin for Atom, obviating the need for its own file browser. This might also address much of the need for issue #162. Since Typora, I believe, is also written in Javascript, this should be possible. @abnerlee is it possible?

**Comment by prefersC** [comment]
Not Atom. Works perfect as is with mind map like iThoughts.

**Comment by vassudanagunta** [comment]
@prefersC I think it is a mind map is a great idea, but not for everyone. Using Typora as an Atom plugin would be optional. It would still function stand-alone. 

I don't know if my idea is the best approach, but one would inherit all of the multi-file project management features of Atom as well as allow one to work easily on projects that are not Markdown only. Not only that, Typora might get a huge following from the already huge Atom user base.

The world is so much better when people can combine the tools they like to use, and each tool can be best of breed. The alternative is for a lot of duplicated code, i.e. someone creating an Atom plugin that behaves like Typora rather than Typora working with Atom.

**Comment by prefersC** [comment]
iThoughts is for everybody working on more than one file. It's a joke to setup a project, requires zero skill, and can do tons of useful stuff. I would recommending trying it first to see if it meets your needs.

**Comment by mattstibbs** [comment]
My vote for a simple file browser is so that I can use it with documentation projects. 

I currently use Finder etc. and that's fine, and a lack of file pane will not stop me from using Typora - however it would just streamline my workflow if I could easily click between different files in the project.

Often writing markdown documentation for publication sites involves working across several files as opposed to working in one single file - much like code development.

**Comment by irmowan** [comment]
Support the issue, Typora is my major Markdown editor, some other ones like TextNut has no shortcuts or clean theme. But one file browser is an useful feature, like YoudaoNode, EverNode. I want to make Typora to be my notebook, so... I vote for this feature.

**Comment by sumyungguy** [comment]
I'd like to see a files sidebar too. A window should be able to open a folder of text files, but also to open files from multiple arbitrary places in the filesystem, as a kind of replacement for the typical horizontal "tabbed" interface. Each window should be able to be saved as a "project" window, so you can easily reopen the same set of files, even if they're not in the same folder.

You can look at TextWrangler and Sublime Text for some ideas about how both a file/folder navigator interface and a "files from anywhere" vertical tab interface can both be done in the same application. One of the reasons I gave up on Atom was that it _only_ had the file/folder navigator aspect. That's great for programmers, when all your files are in a folder hierarchy. But for general text editing purposes, it's too restrictive. That was a long time ago, maybe it's better now...

**Comment by schmeisers** [comment]
Another +1 for this.  Two things would make Typora a killer notes app...
A file browser that replaced the currently open file with a newly selected file from the browser and a global insert image into local folder setting.

**Comment by solarce** [comment]
This is something that I find myself wanting more and more, as I use Typora more frequently, and it seems to be a common source of new issues (from the perspective of someone who watches this repository). 

@abnerlee, would you be willing/able to offer some insight into the relative priority of this as a feature?

- if it's gonna happen at all? maybe it doesn't
- if it's post-1.0
  - maybe a hint at when we can expect 1.0 (I'm sure I'm not the only one who's ready to give you their money),
- maybe it's just not a UI/UX thing you want to add to Typora at the moment? that's understandable and knowing it helps us better figure out where Typora fits in our _personal toolboxes_, if you will

Overall, thanks for an awesome product that's been in the _free Beta_ period for a while now.

**Comment by abnerlee** [comment]
@solarce It's a pre-1.0 feature for simple file navigation.

But maybe some features, such as full-text search or multi-tab for Windows/Linux, will be post-1.0 or be implemented in future product.

**Comment by aloboa** [comment]
For me the side panel with the directory tree + some basic functionality (renaming, moving..) is a must.
I'm using zim now, which has this functionality but it does not interpret markdown
http://zim-wiki.org/screenshots.html
And this is an screenshot of my own notebook
![screenshotzim](https://cloud.githubusercontent.com/assets/6074054/24291416/2a08521c-1089-11e7-87d3-2228065d9747.png)

Basically, I'm looking for a zim-like tool, but able to deal with markdown.

**Comment by initstring** [comment]
Agree that this would be a killer feature. I'm currently using Atom for note taking, as I prefer markdown and need the integrated tree view to support my particular workflow.

Just found Typora today - love it, and would switch full time if this comes to fruition.

Thanks!

**Comment by woohling** [comment]
So any upcoming news about this feature? Love Typora and its simplicity. And a file folder menu on the left would be a huge help for most users.

**Comment by stupidinabox** [comment]
I was here to request the same feature. One other thing that I felt was needed is the ability to open linked file(local file) by clicking on the document. Otherwise great tool.

**Comment by UltimateRandom** [comment]
I would love some sidebar like Sublime Text

**Comment by matteomac** [comment]
+1 , im looking for something to use crossplatform, and i would go withi typora for all its features, but a files tree on my side is required for a fast usage

**Comment by lpld** [comment]
+1 Yes, please!

**Comment by bobtheguitar** [comment]
+1 Essential!

**Comment by ekul00** [comment]
I came here to make the same suggestion. One of the main benefits for me would be being able to jump into related files and make minor changes or grab links etc., without needing to touch the mouse.

In my view, one of the best examples of implementing a folder/ project view is the Sublime Text way of opening a folder as a project, and of course there are many similar implementations in other products. 

For search/ filtering, I like the Notational Velocity/ nvAlt approach. The two approaches differ especially for keyboard navigation between files: Sublime lets you flip between open files from tab to tab, nvAlt has no tabs or open files, but lets you navigate between files going up and down the file list (whether or not a search filter is applied), changing the content of the one content view in the window. Both work well for different use cases.

**Comment by abnerlee** [comment]
I'm closing this since Typora now ready has a simple "files" panel. And we are still keeping improving that.

Please open new issue for new related requirements.

**Comment by prefersC** [comment]
I was so wrong about this. I use the navigator often. Nice work!

**Comment by woohling** [comment]
After searching for a long time finding where is the 'files' panel, found it on the top right position on the window, a small 'tab' icon. And finally there's a navigator.

**Comment by JianCheng** [comment]
I also searched for a while to find the 'file panel'.
For those people who use linux version like me, click 'view' menu -> 'file tree'. 

Nice work. Thanks.

**Comment by TechIsCool** [comment]
Does anyone know how to open typora with a folder from the CLI on Mac. I can open files just fine.

**Comment by thehackercat** [comment]
+1
