### ISSUE TITLE
How to highlight mermaid code?

### ISSUE THREAD

**Issue by Serious54088** [typora/typora-issues#5769]
Hi, 

I want to paste a piece of mermaid code into a code block and highlight the code text with mermaid syntax. 

However, using **```mermaid** to hold the code text will render and draw it as a chart, which is not what I want. 

Is there a solution?

**Comment by matt-stomper** [comment]
Hi,

I found that you can add the code fence ``` then when you can type the code language, you can type mermaid.
![image](https://github.com/typora/typora-issues/assets/6627675/74322c07-87c4-4736-9bb0-d3c037ccd420)

![image](https://github.com/typora/typora-issues/assets/6627675/aa617496-8a4d-474e-be72-d8c370d74840)

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!

**Comment by abnerlee** [comment]
You can wrap it into a code block with markdown language syntax as work around. 

~~~
```markdown
```mermaid
[code]
```
```
~~~

We could add languages like "mermaid-text", but it makes syntax go away when you export or publish the md file because other markdown engines cannot read "mermaid-text" lang type. So we currently do not have plans to specifically add lang name for mermaid but not renders it.
