### ISSUE TITLE
Please provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [typora/typora-issues#583]
So Typora is a minimalistic editor. But the installation on Linux is anything but.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

For testing purposes, I have prepared a Typroa AppImage:
https://bintray.com/probono/AppImages/Typora/_latestVersion#files

**Comment by disanvparean** [comment]
That's a great idea. Thank you for your AppImage. I hope the team will use it.
It's was really sad not to be capable of using Typora on Fedora :'( :+1:

**Comment by probonopd** [comment]
Ping!

**Comment by Wenzel** [comment]
@probonopd thank you so much for this AppImage !
I was able to download and test Typora in no time.

**Comment by fbruetting** [comment]
Yes, let’s all download more-or-less random files from the internet, mark them executable and run them… are you people crazy?!?!

Please provide a Flatpak instead!

**Comment by probonopd** [comment]
> Yes, let’s all download more-or-less random files from the internet, mark them executable and run them…

Downloading an official file from the original application author is way less "random" and running without installation nor root is less crazy than you apparently think. It's how it has been working on other desktop OSes for decades.

See what Linus Torvalds has to say: https://plus.google.com/+LinusTorvalds/posts/WyrATKUnmrS

**Comment by fbruetting** [comment]
Yes, not in this case (maybe), but the people would get used to it and will do this also with random files. And yes, as you mentioned – you see on windows systems what the consequences are, congrats.

With Flatpak, you have to download the runtime just once for every single program that uses it. That’s really not a big deal at all and drastically improves security and safety. In fact, you complain about the runtime in Flatpak having to be downloaded once – while you advise people to use AppImage, where you have the runtime in every single(!) file. Where is the logic?

But yes, in 2015 AppImage was the best solution, so I understand Linus’ comment. But Flatpak now fixes the drawbacks of AppImage.

**Comment by probonopd** [comment]
> But Flatpak now fixes the drawbacks of AppImage.

Not at all. But that discussion is off-topic here.

**Comment by fbruetting** [comment]
At least it fixes the most serious issue via sandboxing – and this discussion is perfectly valid here, in my opinion.

**Comment by KurtPfeifle** [comment]
@abnerlee 
Ping...

**Comment by AeliusSaionji** [comment]
>> But Flatpak now fixes the drawbacks of AppImage.  

> Not at all. But that discussion is off-topic here.

Using the better solution which achieves the same desired result is very topical.

If upstream wants to provide both flatpak + appimage, that's up to them. Practically speaking, it just makes more sense to adopt flatpak and call it a day.

**Comment by probonopd** [comment]
> Using the better solution which achieves the same desired result is very topical.

@AeliusSaionji there is no "better" solution. AppImage is designed to fulfill very specific needs, and Flatpak does not fulfill most of them.

**Comment by fbruetting** [comment]
You tell us that in every thread, yet you never point out real arguments. Honestly, you should stop arguing against Flatpak without having _anything_ comparable. I really don’t understand how you’re doing that. AppImage is a joke, compared to what Flatpak is (and will be) capable of.

**Comment by fbruetting** [comment]
You tell us that in every thread, yet you never point out real arguments. Honestly, you should stop arguing against Flatpak without having _anything_ comparable. I really don’t understand how you’re doing that. AppImage is a joke, compared to what Flatpak is (and will be) capable of. Yet, I’d still like to thank you for your work! ;)

**Comment by KurtPfeifle** [comment]
@fbruetting wrote:

> *"You tell us that in every thread, yet you never point out real arguments."*

For those who *want* to see, it is there in plain sight. Look at the following table. It is located in the [AppImage wiki](https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison). If you ...

* ....find any factual mistakes in this table, or 
* ....know how to correctly fill in missing entries ('tbc' / 'tbd'),
* ....have new items which contribute to a more complete picture, 

...you are invited to submit corrections:

![Comparison table: AppImage, Snap, Flatpack](https://i.stack.imgur.com/ixMzs.jpg "Comparison table: AppImage, Snap, Flatpack")

**Comment by AeliusSaionji** [comment]
Wow, I was going to just stay out of this because I can see some mild benefit for having a contained portable version of the program on systems where you don't have root access,

but that chart is hot garbage. Skimming through, several obvious points are blatantly "I did no actual research" levels of wrong, and many of the points are painfully distorted such that you frame not having a thing as a negative, when in fact the lack of said thing is either a subjective or objective benefit.

I think you just showed your hand as the dishonest "I just want to win this argument" type person. I am not impressed.

**Comment by KurtPfeifle** [comment]
@AeliusSaionji, so please ***you*** impress ***me*** by contributing your research results and help correct that chart, or produce an alternative one (where you also invite others to add to and/or correct it).

Which point(s) specifically  -- which are NOT explicitely marked as 'tbc' / 'tbd'! --   fit your *"I did no actual research"* rating?

**Comment by fbruetting** [comment]
I have some few points about that list:

- Main advantage of Flatpaks is a defined environment for everybody, AppImage seems not to have that, as otherwise every AppImage has to bundle the half SDK/runtime.
- Additionally, Flatpak binaries should be much smaller, as there is one SDK/runtime for several programs.
- Also it can break through Sandboxes via portals – what is the point in trying to sell “running without a sandbox” as a positive argument?
- I also don’t see an advantage in the ability to exchange sandboxes…?
- The cross at “running without root access” is bullshit, as if you restrict it that far to the installation, you won’t even have access to a machine without root access. 🙄 And Flatpak already now gets preinstalled in quite some Distros.
- I also don’t know what the benefit of running without installation should be. It’s completely hassle-free in Flatpak.
- Then: NOT having to download an executable really is the benefit Linux has achieved in the past – and you REALLY(?!) try to also make this look as a feature? Are you insane?! For setting up a machine, I have a large list of programs, I give to DNF or Flatpak and most things are done. I’m not crazy and want do search for, and download each and every application from some random source, which could additionally be malware (Flatpaks are sources, build by a build server, and thus avoid these problems).
- Running unpacked… CONGRATULATIONS! You shup huge binaries and then argue, that they could be even larger? In current times of terabyte this also isn’t a real case. And running uncompressed also leads to more performance. Good luck in running something demanding from an archieve.
- A cross at air-gapped? I already installed LibreOffice-Flatpak from a file being offline. So what is the point?
- And no again, I really don’t want – or even feel the need – of running applications from network shares or disks. 😂
- Who actually felt the need for sharing an installed program and had a hard time not being able to download the source file? What ridiculous arguments are those…?!
- Why do I need an application being able to update itself (and it’s developer to implement that first), if I can run `flatpak update` instead? Please explain.
- And you for example list it being runnable in Fedora 12 as an argument? TOTALLY STUPID! EOL almost 10 years back!
- Also this out-of-the-box arguments? What are those? In the next years you will have >50 Flatpaks on about every distro. Then tell me, what doesn’t run out-of-the box, please? And what is the problem with `sudo apt install flatpak`? Stupid!
- Independency: Which part of Flatpak creates a dependency to Red Hat? I can build it by myself and install/run it… so?
- Not linked to a business case: The whole Linux is linked to businesses. Why do you think we have ~150 kernel devs (afaik)? You think they all work for free? They’re paid by businesses! But that is no case, as we all profit, if you don’t know.
- Distribution’s influence: Bullshit argument
- LibreOffice 5.4.3 was 140MB in size, for example. Listing 6.0.0.0-Alpha-1 with 570 MB is a **BULLSHIT** argument.
- And yeah, of course Flatpak is inpired by AppImage. I really see the analogy! BULLSHIT
- Oh yeah Electron, most bullshitty SDK we currently have! Really glad it doesn’t bundle Flatpak!


### My conclusion

Those arguments are not important by far the most part, and instead look like someone searched really hard for every little side-effect and tried to make it look like a feature. So you obviously aren’t able to list _real_ benefits, otherwise you would never need to do anything like that. This is also the case why probonopd never lists real arguments – because he has none of importance.

**Comment by probonopd** [comment]
> Main advantage of Flatpaks is a defined environment for everybody

True. AppImage does not have that.

> Additionally, I assume Flatpak binaries to be smaller

Please do actual tests. And please count a) the runtimes needed for the Flatpaks as well and b) consider that AppImages are never unpacked on the filesystem.

> what is the point in trying to sell “running without a sandbox” as a positive argument?

There are examples where applications do not work correctly when running in a sandbox, and application authors having no interest to go through the extra hassle of supporting a sandbox. Snappy examples also come to mind where the confinement needs to be disabled for it to work properly. Personally I think the _option_ do do something is almost always _positive_... I don't want a sandbox to be enforced on me. 

> The cross at “running without root access” is bullshit, as if you restrict it that far to the installation, you won’t even have access to a machine without root access.

Huh,... what? So how about people using computers in, say a university lab, or in a large corporation - in general, that people who just have a "regular user" account?

> And Flatpak already now gets preinstalled in quite some Distros.

But not all of them. Including major "mainstream" ones.

> I also don’t know what the benefit of running without installation should be.

Here are some:
* The system does not get changed. Adding applications does not cause other parts of the system to be updated or changed. I hear frequently from Krita users who are happy that they can now use the latest version of Krita without risking to mess up their KDE installation on the system (which may be optimized for different versions of libraries)
* The time it takes to install an application is not needed. Installing e.g., LibreOffice, can take considerable time

> It’s completely hassle-free in Flatpak.

Quite to the contrary, I really try one or twice a year but so far I never succeeded even once. Since all I ever run is Live ISO systems. (OK, my use case may be special, but I didn't claim otherwise. The fact remains - it does _not_ work for _me_.)

> Then: NOT having to download an executable really is the benefit Linux has achieved in the past – and you REALLY(?!) try to also make this look as a feature? Are you insane?!

Most Mac and Windows desktop users either get software by downloading it from the author's download page or from DVDs or CDs. Or by copying it on a USB stick, or copying it over the network. All of these use cases are easy with AppImage. In contrast, the traditional Linux model makes some of these unnecessarily hard. Take [Cura](https://ultimaker.com/en/products/ultimaker-cura-software) for example - the authors want users to fill in a short survey before the download starts. Again, easy with AppImage.

> For setting up a machine, I have a large list of programs, I give to DNF or Flatpak and most things are done. 

For setting up a machine, I launch the latest Live ISO and access (from the same disk I store all my AppImages on) or copy over (over the fast local network) my collected AppImages - done. I don't have to re-download them.

> I’m not crazy and want do search for, and download each and every application from some random source

The original upstream author is not "some random source". It is the authoritative, officially-supported, unchanged "original" version.

> which could additionally be malware (Flatpaks are sources, build by a build server, and thus avoid these problems

> Running unpacked… Congratulations! You ship huge binaries and then argue, that they could be even larger? In current times of terabytes this also isn’t a real case anymore. And running uncompressed also leads to a higher performance. Good luck in running something demanding from an archive.

Have you _actually tried_ it or are you making just general statements? CPU power also has gone up. No matter the size, somehow _my_ hard disks are _always_ full...

> I really don’t want – or even feel the need – of running applications from network shares or disks. 😂

I do.

> Who actually felt the need for sharing an installed program and had a hard time not being able to download the source file? What ridiculous arguments are those…?!

Imagine a collection of applications or, say, a large game (gigabytes). All the while you are in a location where you have no or only very limited connectivity. Like in a train. A situation in which _I am _all the time_.

> Is this even controllable, to stay at an older release in AppImage? Because I have two AppImages, and I never get asked before updating.

The author of a particular AppImage can control whether you get asked or not. (I personally don't want to be bugged by software.)

> And you for example list it being runnable in Fedora 12 as an argument? EOL is almost 10 years back! What is this?!

Agree, Ubuntu LTS 14.04 and CentOS 6 and 7 are probably more relevant these days.

> Also this out-of-the-box arguments? What are those? In the next years you will have >50 Flatpaks on about every distro. 

I can't imagine Ubuntu (the arguably most popular Linux desktop distribution) to do this anytime soon.

> Then tell me, what doesn’t run out-of-the box, please?

Flatpak itself needs to be set up, e.g., on Ubuntu. At least that was the case the last time I checked. Similar for many other distributions. And I am not gonna touch a package manager. Because it messes around in my base system. Which I prefer to be a factory-clean, read-only filesystem image.

> And what is the problem with sudo apt/dnf install flatpak?

Not remotely as easy as drag-and-drop in the file manager.

> Independency: Which part of Flatpak creates a dependency to Red Hat? I can build it by myself and share/install/run it… so?

You will be hard pressed _not_ to see that Flatpak and related technologies are closely linked to Red Hat employees, projects, and ecosystems than others. Which may not be a problem for _you_ but for _some_.

> Not linked to a business case: Whole Linux is linked to businesses. Why do you think we have ~150 kernel devs (afaik)? You think they all work for free? They’re paid by businesses!

There are also lots of examples of purely community (read: volunteer) based open source projects.

> Distribution’s influence: Bullshit argument

Please specify.

> LibreOffice 5.4.3 was 140MB in size, for example. Listing 6.0.0.0-Alpha-1 with 570 MB is a BULLSHIT argument.

Because?

> And yeah, of course Flatpak is inpired by AppImage. I really see the analogy! 😂

That'd be an oversimplification. Flatpak is inspired by Glick which was inspired by klik (the predecessor of AppImage).

> And yeah again! Electron, most bullshitty SDK we currently have!

That is your opinion, and you will probably have your reasons for that opinion. However when looking at applications I use, I noticed two facts:

* Almost all applications I use are cross-platform (Mac, Windows, Linux)
* Most of those (at least the newer ones) tend to be either written in Qt or Electron

> Those arguments are not important for by far the most part

Again, that is _your_ opinion. My guess is that _you_ are using your Linux desktop like a _Unix machine_, and possibly even are a _system administrator_. You probably have years of experience in _managing_ systems (and enjoy doing so).

Whereas I use _my_ Linux desktop like a _Mac_ (to get things done), don't want to have to _fiddle around_ with stuff, and am a _mere user_ (at least I try to be - some of the time).

**Comment by abnerlee** [comment]
merge to https://github.com/typora/typora-issues/issues/1457
