### ISSUE TITLE
copy multiple images

### ISSUE THREAD

**Issue by daerzi** [typora/typora-issues#6070]
问题：Typora 仅支持选中单个图片进行拷贝，不支持选择多张图片 或 全图文选中时拷贝。

![image](https://github.com/typora/typora-issues/assets/72557859/556b5435-ab7a-483c-b9b4-e68d7280cfaa)

场景：后期是否考虑对该功能有所支持，因为用 Typora 编写完 MarkDown 笔记后，想要拷贝到自己的博客很麻烦，图片需要自己一个一个复制粘贴。

建议：在选中所有图文时，右键 "复制/粘贴为" 选项下添加这一功能，Ctrl + C 默认情况下还是复制 MarkDown 源代码。
![image](https://github.com/typora/typora-issues/assets/72557859/511257c3-bbe5-4bd3-b110-70b78fffd335)

**Comment by abnerlee** [comment]
您可以使用菜单 → 格式 → 图像 → 将所有图像复制到...

或者，使用 ctrl+c 和 ctrl+v，它可以默认复制富文本 (https://support.typora.io/Copy-and-Paste#default-copy-behavior)

You can use menu → Format → Image → Copy all images to...

Or, use ctrl+c and ctrl+v, it can copy rich content instead of Markdown source (https://support.typora.io/Copy-and-Paste#default-copy-behavior)
