### ISSUE TITLE
Spellcheck doesn't work on Windows

### ISSUE THREAD

**Issue by coda1997** [typora/typora-issues#657]
It is unfortunate that spell check doesn't work on Windows 1703 after updating windows creator.
Even I install the newest typora again, but it doesn't work.

**Comment by abnerlee** [comment]
@coda1997 It is working in my testing, could you confirm spell check is enable from preference panel, and you are suing the latest version?

**Comment by ijesonchen** [comment]
I experienced the same problem. 
OS: WIN10 1703 / 1709
Typora: 0.9.38 beta
Spell check is enabled, but doesn't work

**Comment by abnerlee** [comment]
duplicate with https://github.com/typora/typora-issues/issues/870

@ijesonchen Did you enable it in preference panel?
are your using the 64bit or 32bit Windows/Typora?

Does spell check supported in other apps, like Chrome or notepad?

Could you try solution in https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/spell-checker-not-working-in-mail-or-word-windows/81bf53c4-f5c4-4920-aa91-0b5cb44d4ad2?auth=1 ?

**Comment by ijesonchen** [comment]
Well, I solved it.
Maybe the reason is my Win10 language set is Chinese and the spell check for English does not work.
So I add the English (United States) language pack in Windows Settings, and it works in Typora, and Win10 Mail, not Notepad.
Because I use the Chinese language, the detailed step maybe not totally correct:
Windows Settings, Datetime and Language, Location and Language, Add Language, then add English (United States).
Maybe you should select the added language, Option, then download some resource.
Hope that could help.
