### ISSUE TITLE
display equations that span multiple lines do not render

### ISSUE THREAD

**Issue by daviehh** [typora/typora-issues#666]
for example, `$$\begin{align}a&=b\\c&=d\end{align}$$` works but

```
$$\begin{align}
a&=b\\
c&=d
\end{align}$$
```
does not work.

Typora Version 0.9.9.9.4.2 (0.9.9.9.4.2)

**Comment by JamesMackerel** [comment]
I found some solution.
use \begin{align*}, just like this:
``` latex
$$
\begin{align*}
& \limx {(\frac 1 {x^2} - \frac 1 {x\tan x})} \tag{1} \\\\
 = & \limx {\frac{\tan x - x}{x^2\tan x}}  \tag{2}\\\\
 = & \limx {\frac{\tan x - x}{x^3}}  \tag{3}\\\\
\overset {L^\prime}{=} & \limx \frac {\sec^2 x -1} {3 x^2} \tag{4} \\\\
= &\limx \frac {\tan^2 x} {3x^2} \tag{5}\\\\
= &\limx \frac {x^2} {3x^2} \tag{6}\\\\
= &\frac 1 3 \tag{7}
\end{align*}
$$
```
But \begin{align} still doesn't work while it works well on other markdown editor.

**Comment by abnerlee** [comment]
Line breaks in inline math equations are not supported, only block math support line break, and the syntax is:
```
$$
content
$$
```

**Comment by JamesMackerel** [comment]
@abnerlee 
I think you have some misunderstanding about this bug/feature.
We didn't use inline math, and we did use block math, and the problem is not "line breaks take no effect", the problem is "math blocks using \begin {align} is not rendered". Math blocks should be rendered before we talk about line breakers.

**Comment by abnerlee** [comment]
In my testing \begin{align} works, as daviehh mentioned:
`$$\begin{align}a&=b\\c&=d\end{align}$$` works

**Comment by GandalfSaxe** [comment]
What is the difference really between inline math and a math block, if math block does not support multiple lines anyway?

**Comment by GandalfSaxe** [comment]
By the way, this doesn't work for me:

`$$\begin{align}a&=b\\c&=d\end{align}$$`

I get the error:

! Package amsmath Error: Erroneous nesting of equation structures;
(amsmath)                trying to recover with `aligned'.

This is unfortunate since if align cannot work in $$ HERE $$, then you can't see a preview of the multi-line math block :/

**Comment by GandalfSaxe** [comment]
Ok so `aligned` instead of `align`:

https://stackoverflow.com/questions/26049762/erroneous-nesting-of-equation-structures-in-using-beginalign-in-a-multi-l

https://github.com/jgm/pandoc/issues/3059

**Comment by CatOnly** [comment]
Similar problem on my article is span inlines do not render or render many times
For example I type text：
"将点 P 绕 $\vec u$ 旋转 $\theta$ 度"
It display:
"将点 P 绕   旋转  度" or 
"将点 P 绕 $\vec u$ 旋转 $\theta\theta\theta$ 度"

You can see the example problem many times in [this .md file](https://github.com/CatOnly/CrashNote/blob/master/LinearAlgebra/Part1.md) 

Typora version 0.9.9.18.1 (1088)

**Comment by a753255157** [comment]
Just

$$ \begin{align}
& \limx {(\frac 1 {x^2} - \frac 1 {x\tan x})} \tag{1} \\\\
= & \limx {\frac{\tan x - x}{x^2\tan x}}  \tag{2}\\\\
= & \limx {\frac{\tan x - x}{x^3}}  \tag{3}\\\\
\overset {L^\prime}{=} & \limx \frac {\sec^2 x -1} {3 x^2} \tag{4} \\\\
= &\limx \frac {\tan^2 x} {3x^2} \tag{5}\\\\
= &\limx \frac {x^2} {3x^2} \tag{6}\\\\
= &\frac 1 3 \tag{7}
\end{align} $$
