### ISSUE TITLE
Online/webapp version of typora

### ISSUE THREAD

**Issue by arieljannai** [typora/typora-issues#684]
Is there going to be an online version?
A webapp that can work offline (and be online for syncing) is also great (like [StackEdit](https://stackedit.io/))

**Comment by abnerlee** [comment]
Sorry, we do not have such plan before v1.0

**Comment by johnmathews** [comment]
It would be realllllly great if there was.

**Comment by schultzter** [comment]
I've tried several online Markdown editors for editing/saving documents on Google Drive but I would love it if Typora was available online to directly edit my files in Google Drive. I've tried StackEdit, Dillinger, and a few others but Typora is by far the best editor out there!!! 

Not just because it does away with two-pane editing but also because of all the left side bar navigation (killer feature) and extended Markdown support (i.e.: highlighting, tables, etc). 

I'm just looking for a notepad with some formatting that loads quickly - GDocs does not load quickly and GKeep has no formatting.
