### ISSUE TITLE
[Feature Request] Side-by-side view

### ISSUE THREAD

**Issue by aphirst** [typora/typora-issues#70]
Self-explanatory, really. It'd be nice to have an option for a side-by-side view of markdown source and rendered document, where presumably scrolling in one controls appropriately scrolling in the other.

**Comment by leewi9** [comment]
Well, I don’t think so. Personally I prefer What you see is what you get.

-- 
leewi9
Sent with Airmail

On March 1, 2016 at 7:48:53 PM, Adam Hirst (notifications@github.com) wrote:

Self-explanatory, really. It'd be nice to have an option for a side-by-side view of markdown source and rendered document, where presumably scrolling in one controls appropriately scrolling in the other.

**Comment by aphirst** [comment]
@leewi9 That's why I said "option" rather than "change"... :smile:

**Comment by abnerlee** [comment]
We do not have plans to support a Side-by-side view like mou or macdown, to make the hybrid view easy and good enough for users is our goal

**Comment by aphirst** [comment]
Alright. Thanks for clarification of the design goals.

**Comment by vonas** [comment]
I'd like to add something to the discussion.

Side-by-side view would be a great option for when you're doing stuff like writing out a sequence diagram with mermaid - which is what I am actually doing right now and is the reason why I came here. When the diagram get's a little long, you have to scroll up and down to see what you're typing and what you're getting.

You can already see the problem here: WYSIWYG (what you see is what you get) doesn't really apply anymore, since you're not directly changing the diagram, but you're writing text which get's translated to a diagram in a different place.

To sum it up, hybrid view in its current state is not "good enough" for sequence diagrams (to name an example, there will most definitely also be other cases). Here are a few solutions I could think of that would greatly improve the experience:

- Introduce side-by-side view like suggested by the OP
- Open a separate window for editing mermaid code or the like and only show the generated diagram in the original document. Like this you can move the mermaid editor window next to the markdown editor (or somewhere else) and still have the original editor be hybrid
- An idea I quite like: Instead of inserting the code editor at the top of generated diagram make it fixed to the bottom of the window. When you enter the diagram with your cursor (either click on it or enter it with the arrow keys) the second editor appears at the bottom of the window and the cursor is placed into it. Here's an illustration of what I mean:

### Before
![before](https://user-images.githubusercontent.com/24623262/75118393-0c43f300-567a-11ea-85ce-6b5e6dd32bc1.png)
### After
![after](https://user-images.githubusercontent.com/24623262/75118394-0f3ee380-567a-11ea-83ed-33646bad0bbc.png)

---

I hope you can see why a side-by-side view (or a variation) might be not a bad idea at all.
