### ISSUE TITLE
Exporting documents containing specific characters to PDF, incorrect characters are embedded.

### ISSUE THREAD

**Issue by ikemo3** [typora/typora-issues#740]
1. Input “更” (U+66F4).
2. Export > PDF
3. Open PDF file.

“更” is displayed properly, but embedded text is not “更” (U+66F4) but “更” (U+FF91).

U+FF91 is CJK Compatibility Ideographs from KS X 1001:1998
https://en.wikipedia.org/wiki/CJK_Compatibility_Ideographs

Only Windows version 0.9.29 is affected. Mac version 0.9.9.9.4.2 is not affected.
Only PDF output is affected. Word output is not affected.

**Comment by abnerlee** [comment]
@ikemo3 hi, thanks for the bug report and detailed explanation.

I tested in Window10 (Simplified Chinese Edition) with Typora 0.9.29, but when I select text from PDF, the copied char is correct (U+66F4), so I cannot reproduce this.

What is your Typora theme and system language? And could you attach the exported PDF here in case it is caused by PDF reader/render issue.

And, if you export as HTML, then print as PDF using Chrome, will this bug happen?

**Comment by ikemo3** [comment]
Sorry, this bug is not Typora's issue.

1. Open Typora's pdf with Adobe Acrobat Reader -> This bug is happen.
2. Open Typora's pdf with Google Chrome or Preview.app(Mac) -> This bug is not happen.

Therefore, this bug is of Adobe Acrobat Reader.
