### ISSUE TITLE
Letter-ordered lists

### ISSUE THREAD

**Issue by Airgunster** [typora/typora-issues#755]
Hi there,

Currently Typora is missing letter-ordered lists (i.e. `A) B) C)`), it will be very nice to have possibility to make letter-ordered lists.

Examples,

```
A) Text
B) Text
C) Text
```
```
a) Text
b) Text
c) Text
```
```
(a) Text
(b) Text
(c) Text
```
```
A. Text
B. Text
C. Text
```
```
a. Text
b. Text
c. Text
```

I guess it will be very easy to implement, could you please have a look and consider to implement?

#### System Information
OS: macOS Sierra 10.12.5
Typora: 0.9.9.9.4.2

Thanks a lot in advance!
Alexey

**Comment by lloyd094** [comment]
I just started running into this as well - especially when working with legal documents such as employee agreements, etc. I think it would be a great addition!

As a suggestion, it may be a smart thing to have some sort of code start so it makes it easier to distinguish? Such as: 
```
![abclist]{
a. etc etc etc
b. etc etc etc 2
c. Something here.
}[/abclist]
```
Just something to say: hey - I'm gonna use a letter list!

(Thanks for all the phenomenal work you do!)

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/369

**Comment by vr8hub** [comment]
Typora isn't missing this, _Markdown_ is missing this. This is an example of something I don't think Typora should be trying to blaze a trail in. If we want letter lists (and I agree they would be nice), we need to be petitioning CommonMark (e.g.), not Typora.

**Comment by vassudanagunta** [comment]
@vr8hub No, Markdown is missing nothing. It's job is to represent the fact that a set of items belong to an ordered list, not how that list is to be rendered.  

Whether an ordered list is rendered with numbers, letters or whatever is a rendering issue. So I looked it up. Guess what: [CSS list-style-type Property](https://www.w3schools.com/cssref/pr_list-style-type.asp).

@abnerlee please don't extend markdown for this. You are right, this is a #369 issue.

**Comment by vr8hub** [comment]
First, no one asked @abnerlee to extend markdown for this. I specifically said Typora should *not* be handling this. I said that Markdown itself should be the one to handle this.

And they can (and should, for Markdown purposes) be handled in the ol itself, where you can specify not only a starting point (which I also wish Markdown supported), but also whether it should use alpha or numbers. This isn't a rendering issue. It's as easy as 1. 2. 3. saying I want a numeric list, and A. B. C. saying I want an alpha list. Markdown doesn't support the latter, but IMO, it should.

**Comment by vassudanagunta** [comment]
Well, at least two people above asked for it, and @abnerlee labeled it with `markdown extension`. And no, it does not belong in Markdown.  Markdown allows you to select a starting point because that is a semantics issue, not a presentation (rendering) issue.  It's the very reason `*` is named "emphasis" rather than "italics", because one can choose a different rendering of emphasis (e.g. color). The fact that for HTML/CSS it's done in CSS and not in HTML follows this principle.

**Comment by vr8hub** [comment]
As I said above, Markdown does _not_ allow you to select a starting point. It doesn't matter what number you put on the first element, Markdown starts an ordered list with 1. It does that by design. I don't like that particular design, but it's part of the charm. ("You don't have to worry about the sequencing, Markdown will take care of that for you.")

Markdown further turns that into a straight `<ol>` in the output. Since ol's default is numeric, then it turns into a numeric list. And that's it's reason for being — that's why Markdown uses numbers to represent an ordered list, _because it's intended to be used for numeric lists._ Sure, you can turn all of your numeric lists into alpha lists with CSS, but then your physical representation in your raw file (1. 2. 3.) doesn't match your physical representation in your output (A. B. C.) which is confusing at best and suicidal at worst.

Further, that doesn't actually address this issue, because it turns *all* ilsts into alpha. We don't want them all to be alpha. We want to choose which ones are numeric and which ones are alpha. _**In Markdown.**_ (And we want the raw source type to match the output type, e.g. if it's 1. 2. 3. in raw source, it should be numeric list in the output.) All Markdown has to do is allow A. B. C. to represent an alpha list, and it generates an `<ol type="a">`. We could still format that however we wanted, but it would have generated an alpha list by default, which is what we want. (If it really wanted to get wild, it could allow I. II. III. to specify a Roman numerical list, with a type="I").

I realize there are complexities involved, but that's why we have computers. Markdown should be generating the *kind* of list (numeric, alpha), and the CSS control the formatting of those kinds of lists.

We could argue all night (where I am), but I'm not going to. :) Feel free to have the last word. We (or I at least) will agree to disagree on this.

**Comment by vassudanagunta** [comment]
> As I said above, Markdown does not allow you to select a starting point.

Actually CommonMark/GFM support specifying as starting number. Read the spec. 

And, with all due respect, I don't agree with the rest of what you wrote. There is a difference between using numbers to indicate order and using numbers to indicate representation of order. You are making an assumption that I doubt Gruber made. 

Gruber's own words:

```
It’s important to note that the actual numbers you use to mark the list have no effect on the HTML output Markdown produces. The HTML Markdown produces from the above list is:

<ol>
<li>Bird</li>
<li>McHale</li>
<li>Parish</li>
</ol>
```

But the best place for you to push your idea isn't here, but with the [CommonMark community](talk.commonmark.org?u=vas).

**Comment by martzell** [comment]
Markdown fancy lists extension allows different list types. example lists extension below continues the numbering through whole document.

https://pandoc.org/MANUAL.html#ordered-lists

**Comment by abnerlee** [comment]
#2448

**Comment by yifengd** [comment]
Is anything happening on this front? It seems like this is pretty much standard in pandoc already.
