### ISSUE TITLE
Anomalies with formatting shortcuts

### ISSUE THREAD

**Issue by waahto** [typora/typora-issues#82]
## 1

Pressing `cmd+i` inside empty quotation marks "" makes this happen:

```
Pressing `cmd+i` inside empty quotation *marks ""* makes this happen
```

Ie. it emphasizes the previous word and the quotation if the quotation marks are the last characters in the document. If they're not (you're writing in the middle of the text), then it emphasized the next word. Should also happen with other formatters.
## 2

Pressing `cmd+i`twice after text gives you this:

```
Pressing `cmd+i`twice after text gives you *this:***
```
## X

While we are here, could you change the shortcut for strike to something more standardish like `cmd+k`which works in non-en/us keyboards?

**Comment by AlexPasternak** [comment]
Cmd-K, or some close variant, is typically for a link and this is pretty common across apps. Outlook, Confluence, etc. I wouldn't change it to this.

Btw, do you know that you can customize your shortcuts via the Keyboard system preference item. E.g., step 4 here. So just change it to whatever you'd like: http://computers.tutsplus.com/tutorials/how-to-set-up-custom-keyboard-shortcuts-on-your-mac--mac-176

**Comment by waahto** [comment]
Oh bugger. I was thinking FocusWriter, which uses `cmd+K`but then again, it's not a md-editor. Still, the shortcut keys should use letters first and foremost.

Big thanks for the link! I'll probably have a dozen mods made by the end of the week :)

**Comment by abnerlee** [comment]
@waahto Thanks for the bug report. BTW, what's your keyboard's type/layout?

For `cmd+k`, however, that is used for inserting link in most mac apps, like TextEdit.app, so we will keep using it for hyperlink

**Comment by waahto** [comment]
I'm using Finnish layout. Although they're sometimes used, characters /, \, ~, [, ], <, >, `, ´ don't work as shortcuts as I need to press a modified key for them.

**Comment by disrupted** [comment]
sorry for continuing an older thread but I am experiencing similar issues on a German Apple keyboard. For example I've set my List Indent/Outdent shortcuts to `cmd+´` and `cmd+ß`, because the keys are right next to each other and I am using the same pattern in Sublime.
The strange thing is that those shortcuts not only **trigger the indent commands but also the heading formatting (h5 & h6)**. I've tried using `cmd+"+"` instead with the same result. other "normal" key combinations like `cmd+d`/`cmd+f` that I tried would work but I want to use the special keys for this. It seems like a bug to me but maybe there's some hidden setting to turn other key bindings off / to overwrite them or some sort of workaround. please let me know how you are dealing with this.

**Comment by abnerlee** [comment]
So we should also make ""indent/outdent" available for customized shortcut keys.

**Comment by abnerlee** [comment]
shortcut key for string/emphasis in quoted string seems already fixed. 

Custom shortcut keys is also supported - > http://support.typora.io/Custom-Key-Binding/
