### ISSUE TITLE
0.9.33 on win10 can not display normaly

### ISSUE THREAD

**Issue by iadaking** [typora/typora-issues#856]
0.9.33 on win10 can not display normaly,
when i open typora whe window is black 
as i drag the window some times the result can be ok

**Comment by abnerlee** [comment]
@iadaking Could you send us (<hi@typoira.io>) thetypora.log file in `C:\Users\{username}\AppData\Roaming\Typora`?

**Comment by abnerlee** [comment]
I cannot reproduce this. 

Someone met a similar issue that "About" window is empty, and he fixed it by re-install Typora. Could you try that approach or tell me a way to reproduce it.

**Comment by cwdy** [comment]
I met the same issue, either 32 bit or 64 bit for windows. I installed the typora on my laptop under windows10 home OS. But it displayed all black. I tried typing text in the editor field which keep in black, but actully the text was input successfully, because when I Ctrl+A & Ctrl+C, I successfully pasted the text I have input. By the way, i have reinstalled the typora 3 times over different bit version for windows.

**Comment by XinyuDu** [comment]
> I met the same issue, either 32 bit or 64 bit for windows. I installed the typora on my laptop under windows10 home OS. But it displayed all black. I tried typing text in the editor field which keep in black, but actully the text was input successfully, because when I Ctrl+A & Ctrl+C, I successfully pasted the text I have input. By the way, i have reinstalled the typora 3 times over different bit version for windows.

exactly what i met.
