### ISSUE TITLE
typora heading 5 shortcut not work

### ISSUE THREAD

**Issue by yangzhl** [typora/typora-issues#867]
I am using debian9,and this problem has exsisted for several version. heading 5 shortcut ctrl+5 just doesn't work

**Comment by abnerlee** [comment]
May relates to https://github.com/typora/typora-issues/issues/796

**Comment by abnerlee** [comment]
move to https://github.com/typora/typora-issues/issues/796

**Comment by yechs** [comment]
@yangzhl Do you by any chance use fcitx (e.g. for typing Chinese)? `Ctrl + 5` is the global shortcut key for fcitx to reload its config. Deleting that global shortcut solves my problem.

@abnerlee I think [the official wiki](http://support.typora.io/Shortcut-Keys/#q-shortcut-keys-does-not-work-on-ubuntu) could probably document this behavior (since lots of Chinese users are using Typora). I would be happy to open a PR for this.

**Comment by accordionmaster** [comment]
> @yangzhl Do you by any chance use fcitx (e.g. for typing Chinese)? `Ctrl + 5` is the global shortcut key for fcitx to reload its config. Deleting that global shortcut solves my problem.
> 
> @abnerlee I think [the official wiki](http://support.typora.io/Shortcut-Keys/#q-shortcut-keys-does-not-work-on-ubuntu) could probably document this behavior (since lots of Chinese users are using Typora). I would be happy to open a PR for this.

Thank you, it works!

**Comment by yechs** [comment]
> Thank you, it works!

Glad to be of help!
