### ISSUE TITLE
Commercial license copy

### ISSUE THREAD

**Issue by prime-optimus** [typora/typora-issues#890]
I know from #394 that typora is commercial license. But can you please provide a copy of license for review purposes?

**Comment by abnerlee** [comment]
There will be one in the v1.0 release

**Comment by Dod9er** [comment]
Do you already know if it will get a subscription-based fee ?

**Comment by abnerlee** [comment]
> Do you already know if it will get a subscription-based fee ?
No, lifetime license, maybe plus paid upgrade.

**Comment by Dod9er** [comment]
Thank you very much. Good to hear this, I will be happy to purchase a license with the final release.

**Comment by LeBaux** [comment]
Just dropping by to add my 2 cents - I hope, typora isn't going to end up like [write](https://writeapp.co/). The moment it went commercial tons of users abandoned it. I don't remember exactly how it went down ([and they disabled archiving so I can't look it up](https://writeapp.co/robots.txt)), but I know it had ton of happy users, good press and after they dropped the paid version tons of people just went looking for alternatives, including myself. The reason was that initial offering was 60USD/Year for a premium. Totally disconnected from reality. It took them some time to get back from the high horse and now it is 20USD initial one time payment and 5USD after a year for sync and updates. Now this seems more like a fair price, but the damage is done. I wouldn't dare to tell you how to run your business decisions, I'm just offering this as a cautionary tale.

> No, lifetime license, maybe plus paid upgrade.

As much as love the concept of one time payment, it is just bad business practice plain and simple. I steer away from software that has no continuous stream of revenue/funding. At the same time, I know people hate subscriptions. When you want money, there is never a solution for everyone.

If I may propose one alternative, try funding the project with [patreon](https://www.patreon.com/). You can start today, the app might be not polished but it is already solid and it proved to be working for youtubers, streamers, artists and all kinds of people so it is worth a shot. If it doesn't work? No harm done, one blog post explaining why.

My point is, I'm using 10-20 pieces of "donationware" and spending more than 1USD/Month/app is just too much for me. I'm not greedy, I just don't earn that much and as many of us, I also have lot of expenses but at the same time I understand devs need to eat. But for some, it is 2USD, for others 5. Or maybe we are all broke and you will at least know in advance.

Splitting the app, making it freemium or premium always takes the toll on number of users, so consider this approach. Or don't. In the end, I hope it works out for you and this is a commercial success. With bit of shame I have to admit, I'll look elsewhere if the final app is going to be expensive or more than a dozen bucks a year.

**Comment by My1** [comment]
well paid updates will be the stream of income when new big versions come out, so far so obvious.

the thing is that subscription is a really ugly way of licensing "normal software".

for Services like e.g. a VPN or whatever it makes sense to run a subscription.

and paying to be able to use a new version of "normal software" also makes a lot of sense (as long as the bug fixes are included within the initial payment. for obvious reaons in my opinion).

but if a software just decides I cant even use the old version I got because I dont pay anymore that's annoying and ugly, and to make it worse, if the company would go down someday, chances are I cant use that thing ever again.

**Comment by nickbe** [comment]
If I may add my own opinion here.... Right now I install Typora as well as Mark Text. 
As much as I like Typora, I'm always looking for free versions for software I use on every PC that comes across my way. And there are lot's of them over the years. 
So for example whenever I'm working on a clients computer I tend to use markdown for various reasons. And every time I have to decide what to use. On the one hand I'd like to spread the work about Typora, but also I don't want to be surprised by a strict license and payment request one day. Or even worse by a software that sudddenly stops working to accounce I have to pay to continue using it. 
By working on many computers a strict PC based license would definetely end Typora for me. Simply for practical, but also for monetary reasons. So I think you should consider something completely free as well as commercial.
It never easy to split a list of features, so that some will want to pay and others may simply continue to work with their Typora version like their used to. But it will also be a good way to honour all those users who helped you to find bugs and improve typora over the years.
I think both parts of a community should feel comfortable with such a project. My point is that sooner or later you have to decide what the licenses and versions will look like. Better sooner because the farther Typora goes with its version numbers, the more I find myself avoiding it because of the upcoming and unknown license thing. For most people, steering into the unknown is a no go. And using a program for so long as we used typora surely makes many of us wondering what's coming and somehow fearing the outcome - and then looking for a permanent alternative. And that is something you should avoid at all cost.
