### ISSUE TITLE
General Issues with Task lists

### ISSUE THREAD

**Issue by dsfranzi** [typora/typora-issues#908]
I there,

I'd like to address several issues I came across when using Task Lists in Typora.

Version: 0.9.36

Task Lists in Typora seem to be rendered only with a trailing space. It seems like the markdown parser expects some text after the checkbox, but what if I want to use single checkboxes e.g. in Tables?

This brings me to my next issue: Task checkboxes don't seem to work in Tables. Either the checkbox isn't rendered at all or it's rendered in a completely wrong table cell.

Last but not least, it would be nice to use task checkboxes not only in lists with minuses, but in all kinds of lists, like at GitHub.

Greetings,
Franz

**Comment by abnerlee** [comment]
> Last but not least, it would be nice to use task checkboxes not only in lists with minuses, but in all kinds of lists, like at GitHub.

duplicate with https://github.com/typora/typora-issues/issues/643

> Task checkboxes don't seem to work in Tables.

I tried in github, it seems tasks are only support in lists, for example

```
# [x] this is done

> [x] this is done
```

will not work. Also, for other markdown engines/parsers that support markdown, it seems task also does not work in table.

I will close this since Typora is an editor for a common markup language -- markdown, we are less likely to design some syntax that can only be supported in Typora.
