### ISSUE TITLE
Upgrade Typora to 0.9.37 (beta),I can't use the css to auto numbering for headings

### ISSUE THREAD

**Issue by scauzhh** [typora/typora-issues#940]
my system is Ubuntu16.04,It work well to auto numbering for headings with css before upgrade to 0.9.37 (beta).Now,the number of \<h1> label is wrong.

**Comment by elskewe** [comment]
I have the same problem with Windows 7.

**Comment by lechuanhuang** [comment]
An interesting thing is that when exported as HTML with CSS, Firefox 57.0b7 and Edge 40.15063.674.0 will render the numbering correctly, while Typora 0.9.37 beta and Chrome 61.0.3163.100 will fail. Looks like a CSS engine problem.

Firefox
![Firefox](https://user-images.githubusercontent.com/26637740/31557436-af844e46-b016-11e7-9343-3a3e917ce947.png)

Edge
![Edge](https://user-images.githubusercontent.com/26637740/31557435-af71967a-b016-11e7-9b40-22f340c728da.PNG)

Chrome
![Chrome](https://user-images.githubusercontent.com/26637740/31557434-af58b1a0-b016-11e7-9313-48074280864f.PNG)

Typora
![Typora](https://user-images.githubusercontent.com/26637740/31557437-af91308e-b016-11e7-87b6-9749cecded10.PNG)

**Comment by lechuanhuang** [comment]
OK, so I found the problem.

In `base.css` (found in installation directory `C:\Program Files\Typora\resources\app\style`), look for the styling for `#write`:

```
#write {
      margin: 0px auto;
      height: auto;
      width: inherit;
      word-break: normal;
      word-wrap: break-word;
      position: relative;
      padding-bottom: 70px;
      white-space: pre-wrap;
      overflow-x: visible;
      contain: content;
    }
```

The last item `contain: content;` is the culprit. `contain` can take several values (https://developer.mozilla.org/en-US/docs/Web/CSS/contain). It is `style`, which is included in `content` that is causing the problem (most likely a scoping one?).

A temporary solution is to tweak the auto numbering stylesheet (http://support.typora.io/Auto-Numbering/). At the very top, instead of:
```
#write {
    counter-reset: h1
}
```

use:

```
#write {
  counter-reset: h1;
  contain: layout paint;
}
```

And auto numbering should work.

Apparently Firefox and Typora treats `contain: style` differently. I do not have enough expertise to comment on this, though.

**Comment by abnerlee** [comment]
should be fixed in new release
