### ISSUE TITLE
Can't Open on Windows

### ISSUE THREAD

**Issue by rore256** [typora/typora-issues#947]
Hi, just finished installing on Windows 10. 64x version. I can't open the app though, tried opening in admin, didn't work, tried opening in CMD, didn't work.

**Comment by lloyd094** [comment]
Are you getting any sort of errors? Have you tried to uninstall and reinstall? What were the steps you took to install it?

**Comment by abnerlee** [comment]
could you attach logs following http://support.typora.io/Report-Bugs/

after you double click typora.exe, could you see the process in Task Manager?

**Comment by JuergenGutsch** [comment]
I had the same problem after auto updating to the latest version. (Windows 10 x64)
I got no process in the Task Manager and no log entries.

After reinstalling, it works again as expected. Maybe the latest update is somehow broken, because the previous auto updates worked well and the new installation does too.

**Comment by lloyd094** [comment]
Glad to see the reinstall worked - sometimes updates just get borked, and it's hard to tell what happened.

**Comment by ponderwa** [comment]
Did anyone solve the problem?   I've met the same thing.
