### ISSUE TITLE
Tabs replaced by spaces on save cause issues with pandoc and latex

### ISSUE THREAD

**Issue by aarpon** [typora/typora-issues#948]
If I create indented bullet-point lists like this:

* Item1
    * SubItem1
        * SubSubItem 1

indenting with tabs, Typora replaces them with spaces on saving. 

I use Pandoc and convert the Typora markdown documents to latex and via xelatex I build my pdfs. The indentation of the items in the list above gets flattened in the final PDF when the tabs are replaced with spaces. If I replace the spaces with tabs in the original Markdown file using another editor, then the PDF is correctly rendered.

I tried changing the number of spaces in the Typora settings, but this does not seem to help.

Am I missing some configuration option? 

Thanks.

**Comment by aarpon** [comment]
I made the tab indentation in the source code mode, but I am positive that it did not stick on saving.

**Comment by vassudanagunta** [comment]
Whatever you do, please make sure default behvior conforms with CommonMark/GFM (per issue #369).

**Comment by abnerlee** [comment]
relates https://github.com/typora/typora-issues/issues/579

**Comment by abnerlee** [comment]
Fixed in new release. 

Tab indentation made under source code mode will be kept. Also, we provided indent option (tab) in preferences panel -> Editor -> Indent Size on Save.

**Comment by rfrazue** [comment]
Hi,

I am currently using Typora 0.9.50.
When set the new configuration to 'tab' in 'preferences panel -> Editor -> Indent Size on Save' item lists in the source code of the md file are still indented by 2 whitespaces instead of tabs.
Is this a known issue solved in a future version or is there a bug in this new feature?
Would it be better if I would create a new issue?

I would really like to see that fixed - typora seems to be the tool I was always looking for (especially regarding how it deals with tables!).

Thanks for listening!

Cheers
rfrazue

**Comment by abnerlee** [comment]
They are default indents when you create list from menu or shortcut key or list items by tab/shift+tab.

If you input whitespace manually or existing sources, they won't get converted. Prettify existing source code would be included in https://github.com/typora/typora-issues/issues/1316

**Comment by kopax** [comment]
I have still this issue https://github.com/jgm/pandoc/issues/5802

Do you know how I can get proper `\hspace`?
