### ISSUE TITLE
Should auto-close inline code ` character

### ISSUE THREAD

**Issue by AlexPasternak** [typora/typora-issues#95]
I was excited to hear that auto-close was added for single, double quotes, etc. But unfortunately it does not close the inline code character `

I realize this is firmly in the "improvement request" category. But this would be a great to start formatting what you're typing immediately as inline code, as a rich editor.

Currently if you want to see the inline code "live", you have to hit ` twice, then left-arrow back to be between the characters.

**Comment by montogeek** [comment]
Would be awesome if you write the word, then selected it and press ` to surround the word

**Comment by vassudanagunta** [comment]
@montogeek To be consistent then doing the same with * should result in italicizing a word. I'm not sure that is a good idea, because normal expectation of typing a character without any meta keys (CMD, ALT or CTRL) is that it replaces the selected text. 

It would be better if we simply had a simply keyboard shortcut, such as CMD-`

**Comment by abnerlee** [comment]
move to #246
