### ISSUE TITLE
What features will be introduced next?

### ISSUE THREAD

**Issue by geeeeeeeeek** [typora/typora-issues#97]
Since `typora` is in beta now. I wonder what features will be introduced in your release version? And do you have a time schedule?

**Comment by geeeeeeeeek** [comment]
And I noticed that in this image, traffic lights are inlined with the background. Any update on that too?

![image](https://cloud.githubusercontent.com/assets/7262715/13805239/35669b8a-eb8e-11e5-87f7-b6fcd16097a8.png)

**Comment by abnerlee** [comment]
We do have ideas which feature we want in in release version. 

But we don't want to follow it strictly, since some can be include after the release, and some will be added into our task list according to user feedback and our concerns.

And we do not have a time schedule, since usually programmers cannot finish his/her job before the deadline they made.
