### ISSUE TITLE
Add tag to Heading 1 & Heading 2

### ISSUE THREAD

**Issue by luissquall** [typora/typora-issues#98]
The small tag, for instance [h3], that appears when you are on headings 3, 4... is a small but great indicator of what kind of heading you are working on and it's missing from headings 1 & 2. 
![image](https://cloud.githubusercontent.com/assets/28030/13818801/ec303d12-eb5c-11e5-9f11-64001b379333.png)

In long documents is hard to differentiate between h1 & h2.

**Comment by MrJasper** [comment]
Change the color of border-bottom may help:
![sample](https://cloud.githubusercontent.com/assets/15362491/13836389/c6812830-ec3b-11e5-8346-19a04f36448c.PNG)

**Comment by vassudanagunta** [comment]
I see two related problems:

**1. It is very hard to see what heading level you have.**

As @luissquall says, the small tag is impossible to see, especially on a laptop with reduced contrast, and we don't get any indication for H1 and H2.

**2. Changing the heading level is inconsistent between when the heading is first created and when it is later modified.**

When you first type a header, one can see the header level (i.e. the number of `#`'s) and changes the header level by adding or removing `#`'s. But once you hit ENTER the markup is forever hidden. Editing an existing header is an entirely different experience! One is forced to us the Edit menu or remember the keyboard shortcut (which btw doesn't work when first entering the heading). 

Typora already has the precedent of showing markup when editing: when the cursor is placed in italicized or bold text, the `*`'s are shown. I recommend that the same thing be down for headers. The `#`s can be shown in the margin if preferred.

**Comment by AlexPasternak** [comment]
That's a great suggestion, I've had similar issues but wasn't thinking about a good solution. Showing the number of # when editing it would solve it very nicely.

**Comment by leewi9** [comment]
Well I don't think so. If you toggle the outline view, you can see structure very well organized.

As you can guys see, Typora still has many unsolved bugs some of them very critical and in my opinion we should focus on these bugs instead of enhancements.


2016年5月7日 +0800 08:35 AlexPasternak<notifications@github.com>，写道：

**Comment by leewi9** [comment]
From my humble opinion, I do not likeshowing #'s when the cursor is in a heading, which I think will affect the pure beautiful hybrid view and writing experience, in other words I don't want to see symbols like # appear when I'm writing.


2016年5月7日 +0800 09:02 Vas Sudanagunta<notifications@github.com>，写道：

**Comment by vassudanagunta** [comment]
I've thought about this and @leewi9 is right. Typora's strength is as a WYSIWYG editor. If one can't distinguish between heading levels, then that is the fault of the CSS. **Otherwise, what is the point of having different heading levels?!**

Which makes me wonder, given what I said in my first comment above, whether Typora should show `*`'s and other markdown markup when the cursor is placed within. It is rather inconsistent, and it results in weird behavior such as the paragraph your are editing shifting around as it has to rewrap when you move the cursor into a marked up segment.

**Comment by abnerlee** [comment]
It is a css style thing. We will not add tag in H1, H2 by default.

**Comment by hitzhangjie** [comment]
@abnerlee If I want to add tag for H1, H2 in CSS, how could I make it?
Can you show a CSS snippet to help us?

**Comment by abnerlee** [comment]
@hitzhangjie use `h1:before`
